In [1]:
import polars as pl
import os

In [2]:
DATASET_PATH = "/group/pmc021/amunif/epi-thesis/workflow/12_E066 with 5 common histones/dataset"

In [3]:
# Open the features file
test_df = pl.read_parquet(os.path.join(DATASET_PATH, 'E066_exp_histones.parquet'))
test_df

shape: (19_645, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ gene_id    ┆ H3K9ac     ┆ H3K9ac_wc ┆ H3K9ac_le ┆ … ┆ H3K27me3  ┆ H3K27me3_ ┆ H3K27me3_ ┆ E066   │
│ ---        ┆ ---        ┆ ---       ┆ n         ┆   ┆ ---       ┆ wc        ┆ len       ┆ ---    │
│ str        ┆ list[f64]  ┆ u32       ┆ ---       ┆   ┆ list[f64] ┆ ---       ┆ ---       ┆ f64    │
│            ┆            ┆           ┆ u32       ┆   ┆           ┆ u32       ┆ u32       ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ ENSG000000 ┆ [3.18521,  ┆ 38        ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 73.205 │
│ 00003      ┆ 3.18521, … ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆ 1.92092]   ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 3         ┆ 100       ┆ 0.191  │
│ 00005      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 2.29406]  ┆           ┆           ┆        │
│ ENSG000000 ┆ [4.46174,  ┆ 67        ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 52.609 │
│ 00419      ┆ 4.46174, … ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆ 0.0]       ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 48        ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 4.733  │
│ 00457      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.942  │
│ 00460      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.212  │
│ 59658      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 20        ┆ 100       ┆ 0.0    │
│ 59664      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.071  │
│ 59680      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 67        ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.0    │
│ 59717      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.0    │
│ 59752      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [4]:
test_df.columns

['gene_id',
 'H3K9ac',
 'H3K9ac_wc',
 'H3K9ac_len',
 'H3K9me3',
 'H3K9me3_wc',
 'H3K9me3_len',
 'H3K4me3',
 'H3K4me3_wc',
 'H3K4me3_len',
 'H3K27ac',
 'H3K27ac_wc',
 'H3K27ac_len',
 'H3K27me3',
 'H3K27me3_wc',
 'H3K27me3_len',
 'E066']

In [5]:
# Select only the gene_id with histones count
gene_histone_count_df = test_df.select([
     'gene_id',
     'H3K9ac_wc',
     'H3K9me3_wc',
     'H3K4me3_wc',
     'H3K27ac_wc',
     'H3K27me3_wc',
     'E066'
])

In [6]:
gene_histone_count_df

shape: (19_645, 7)
┌─────────────────┬───────────┬────────────┬────────────┬────────────┬─────────────┬────────┐
│ gene_id         ┆ H3K9ac_wc ┆ H3K9me3_wc ┆ H3K4me3_wc ┆ H3K27ac_wc ┆ H3K27me3_wc ┆ E066   │
│ ---             ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ ---         ┆ ---    │
│ str             ┆ u32       ┆ u32        ┆ u32        ┆ u32        ┆ u32         ┆ f64    │
╞═════════════════╪═══════════╪════════════╪════════════╪════════════╪═════════════╪════════╡
│ ENSG00000000003 ┆ 38        ┆ 0          ┆ 31         ┆ 41         ┆ 0           ┆ 73.205 │
│ ENSG00000000005 ┆ 0         ┆ 20         ┆ 0          ┆ 0          ┆ 3           ┆ 0.191  │
│ ENSG00000000419 ┆ 67        ┆ 8          ┆ 47         ┆ 35         ┆ 0           ┆ 52.609 │
│ ENSG00000000457 ┆ 48        ┆ 0          ┆ 41         ┆ 52         ┆ 0           ┆ 4.733  │
│ ENSG00000000460 ┆ 0         ┆ 29         ┆ 0          ┆ 0          ┆ 0           ┆ 0.942  │
│ …               ┆ …         ┆ …          ┆ …          ┆ …          ┆ …           ┆ …      │
│ ENSG00000259658 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.212  │
│ ENSG00000259664 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 20          ┆ 0.0    │
│ ENSG00000259680 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.071  │
│ ENSG00000259717 ┆ 67        ┆ 0          ┆ 54         ┆ 100        ┆ 0           ┆ 0.0    │
│ ENSG00000259752 ┆ 0         ┆ 24         ┆ 19         ┆ 0          ┆ 0           ┆ 0.0    │
└─────────────────┴───────────┴────────────┴────────────┴────────────┴─────────────┴────────┘

In [8]:
gene_histone_count_df.write_csv("E066 with histone count.csv")