In [1]:
import pandas as pd

In [3]:
columns = ['chrom', 'chromStart', 'chromeEnd', 'name']

nucleosome_df = pd.read_csv('dataset/HepG2_Male.nucleosome.peak.bed', sep="\t", header=None, names=columns)

nucleosome_df.head()

    chr   start     end  chr_id
0  chrY  808018  808158  chrY_1
1  chrY  811561  811701  chrY_2
2  chrY  816706  816846  chrY_3
3  chrY  823658  823798  chrY_4
4  chrY  826128  826268  chrY_5

In [4]:
nucleosome_df['chr'].unique()

array(['chrY', 'chrX', 'chr13', 'chr12', 'chr11', 'chr10', 'chr17',
       'chr16', 'chr15', 'chr14', 'chr19', 'chr18', 'chrM', 'chr22',
       'chr20', 'chr21', 'chr7', 'chr6', 'chr5', 'chr4', 'chr3', 'chr2',
       'chr1', 'chr9', 'chr8'], dtype=object)

In [5]:
nucleosome_df.shape

(14217405, 4)

In [6]:
nucleosome_df.describe()

              start           end
count  1.421740e+07  1.421740e+07
mean   8.037889e+07  8.037903e+07
std    5.549418e+07  5.549418e+07
min    2.100000e+01  1.610000e+02
25%    3.495895e+07  3.495909e+07
50%    7.134798e+07  7.134812e+07
75%    1.162271e+08  1.162272e+08
max    2.492404e+08  2.492406e+08