# Import required library

In [1]:
import epi_utils as eu
import pandas as pd
import pyranges as pr
import glob
from tqdm.auto import tqdm

In [2]:
chrom_list = pd.read_csv("dataset/chrom_list.csv")["Chromosome"].to_list()

# Splitting Histone Data

In [3]:
# Load histone file
histone_df = eu.load_histone_files()
display(histone_df.head())

   chrom  chromStart  chromEnd       name  length     type
0  chr10      119808    119954  chr10_173     146  h3k4me3
1  chr10      119956    120102  chr10_174     146  h3k4me3
2  chr10      122100    122246  chr10_185     146  h3k4me3
3  chr10      122308    122454  chr10_186     146  h3k4me3
4  chr10      180346    180492  chr10_489     146  h3k4me3

In [4]:
for chrom in tqdm(chrom_list):
    df = histone_df[histone_df['chrom'] == chrom]
    print(f"Processing {chrom} with {len(df.index)} data")
    df.to_csv("dataset/histone/" + chrom + ".csv", index=False)

  0%|          | 0/24 [00:00<?, ?it/s]

Processing chr1 with 30373 data
Processing chr2 with 24677 data
Processing chr3 with 19425 data
Processing chr4 with 14442 data
Processing chr5 with 16617 data
Processing chr6 with 18508 data
Processing chr7 with 16546 data
Processing chr8 with 13445 data
Processing chr9 with 13472 data
Processing chr10 with 14519 data
Processing chr11 with 15712 data
Processing chr12 with 15929 data
Processing chr13 with 7811 data
Processing chr14 with 10687 data
Processing chr15 with 10076 data
Processing chr16 with 13046 data
Processing chr17 with 16532 data
Processing chr18 with 6333 data
Processing chr19 with 15234 data
Processing chr20 with 8065 data
Processing chr21 with 4116 data
Processing chr22 with 6634 data
Processing chrX with 6424 data
Processing chrY with 463 data

# Splitting NCBI RefSeq Data

## Load the NCBI Ref Seq Data

In [5]:
hg19ncbiRefSeq_df = eu.load_ncbiRefSeq()
display(hg19ncbiRefSeq_df.head())

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,transcript_id,gene_name,exon_number,exon_id,tss
0,chrMT,ncbiRefSeq.2021-05-17,transcript,15955,16023,.,-,.,TRNP,rna-TRNP,TRNP,NaN,NaN,16023
1,chrMT,ncbiRefSeq.2021-05-17,exon,15955,16023,.,-,.,TRNP,rna-TRNP,TRNP,1,rna-TRNP.1,16023
2,chrMT,ncbiRefSeq.2021-05-17,transcript,15887,15953,.,+,.,TRNT,rna-TRNT,TRNT,NaN,NaN,15887
3,chrMT,ncbiRefSeq.2021-05-17,exon,15887,15953,.,+,.,TRNT,rna-TRNT,TRNT,1,rna-TRNT.1,15887
4,chrMT,ncbiRefSeq.2021-05-17,transcript,14746,15887,.,+,.,CYTB,YP_003024038.1,CYTB,NaN,NaN,14746

In [6]:
display(hg19ncbiRefSeq_df.shape)

(2093542, 14)

In [9]:
hg19ncbiRefSeq_df_chromlist = hg19ncbiRefSeq_df["Chromosome"].unique().tolist()

## Splitting into each `Chromosome`

In [10]:
print(f"Splitting into {len(hg19ncbiRefSeq_df_chromlist)} files.")

for chrom in tqdm(hg19ncbiRefSeq_df_chromlist):
    df = hg19ncbiRefSeq_df[hg19ncbiRefSeq_df['Chromosome'] == chrom]
    print(f"Processing {chrom} with {len(df.index)} data")
    df.to_csv(f"dataset/ncbiRefSeq/raw/{chrom}.csv", index=False)

Splitting into 244 files.

  0%|          | 0/244 [00:00<?, ?it/s]

Processing chrMT with 107 data
Processing chr17_ctg5_hap1 with 2092 data
Processing chr4_ctg9_hap1 with 257 data
Processing chr6_ssto_hap7 with 11042 data
Processing chr6_qbl_hap6 with 13477 data
Processing chr6_mcf_hap5 with 12916 data
Processing chr6_mann_hap4 with 11791 data
Processing chr6_dbb_hap3 with 13190 data
Processing chr6_cox_hap2 with 13957 data
Processing chr6_apd_hap1 with 4572 data
Processing chrX_jh159150_fix with 5358 data
Processing chrX_jh806600_fix with 1968 data
Processing chrX_jh806599_fix with 64 data
Processing chrX_jh806598_fix with 77 data
Processing chrX_jh806597_fix with 1020 data
Processing chrX_jh806596_fix with 154 data
Processing chrX_jh806603_fix with 15 data
Processing chrX_jh806602_fix with 85 data
Processing chrX_jh806601_fix with 447 data
Processing chrX_jh806588_fix with 13 data
Processing chrX_jh720455_fix with 29 data
Processing chrX_jh806595_fix with 173 data
Processing chrX_jh806594_fix with 213 data
Processing chrX_jh806593_fix with 482 data
Processing chrX_jh720454_fix with 396 data
Processing chrX_jh720453_fix with 93 data
Processing chrX_jh806592_fix with 584 data
Processing chrX_jh806591_fix with 730 data
Processing chrX_jh806587_fix with 2710 data
Processing chrX_jh806590_fix with 3440 data
Processing chrX_kb021648_fix with 581 data
Processing chrX_jh806589_fix with 15 data
Processing chrX_jh720452_fix with 157 data
Processing chrX_jh720451_fix with 87 data
Processing chrX_gl877877_fix with 2 data
Processing chr22_jh806586_fix with 544 data
Processing chr22_kb663609_alt with 98 data
Processing chr22_gl383582_alt with 117 data
Processing chr22_gl383583_alt with 15 data
Processing chr22_jh720449_fix with 253 data
Processing chr22_jh806585_fix with 5 data
Processing chr22_jh806584_fix with 4 data
Processing chr21_ke332506_fix with 248 data
Processing chr21_gl383581_alt with 140 data
Processing chr21_gl383580_alt with 66 data
Processing chr21_gl383579_alt with 10 data
Processing chr20_gl582979_fix with 61 data
Processing chr20_kb663608_fix with 8 data
Processing chr19_gl949753_alt with 2220 data
Processing chr19_gl949752_alt with 3078 data
Processing chr19_gl949751_alt with 1404 data
Processing chr19_gl949750_alt with 1377 data
Processing chr19_gl949749_alt with 1353 data
Processing chr19_gl949748_alt with 1397 data
Processing chr19_gl949747_alt with 1966 data
Processing chr19_gl949746_alt with 2777 data
Processing chr19_kb021647_fix with 3230 data
Processing chr19_ke332505_fix with 1089 data
Processing chr19_gl383574_alt with 575 data
Processing chr19_gl383576_alt with 23 data
Processing chr19_gl383575_alt with 122 data
Processing chr19_gl383573_alt with 120 data
Processing chr19_gl582977_fix with 100 data
Processing chr19_jh159149_fix with 171 data
Processing chr18_gl383572_alt with 11 data
Processing chr18_gl383571_alt with 9 data
Processing chr18_gl383570_alt with 2 data
Processing chr18_gl383567_alt with 42 data
Processing chr17_jh636061_fix with 192 data
Processing chr17_jh591186_fix with 275 data
Processing chr17_gl383566_alt with 6 data
Processing chr17_jh159144_fix with 861 data
Processing chr17_gl383558_fix with 463 data
Processing chr17_jh720447_fix with 162 data
Processing chr17_gl582976_fix with 1275 data
Processing chr17_gl383564_alt with 119 data
Processing chr17_jh159147_alt with 42 data
Processing chr17_jh159148_alt with 44 data
Processing chr17_jh159146_alt with 290 data
Processing chr17_gl383559_fix with 170 data
Processing chr17_gl383560_fix with 572 data
Processing chr17_kb021646_fix with 369 data
Processing chr17_jh159145_fix with 416 data
Processing chr17_ke332502_fix with 4 data
Processing chr17_gl383561_fix with 33 data
Processing chr17_gl383562_fix with 21 data
Processing chr17_gl383563_alt with 125 data
Processing chr17_jh806582_fix with 143 data
Processing chr16_gl383557_alt with 76 data
Processing chr16_jh720446_fix with 464 data
Processing chr16_gl383556_alt with 192 data
Processing chr15_jh720445_fix with 85 data
Processing chr15_gl383555_alt with 512 data
Processing chr15_gl383554_alt with 259 data
Processing chr14_kb021645_fix with 1564 data
Processing chr13_gl582975_fix with 31 data
Processing chr12_gl383548_fix with 30 data
Processing chr12_gl383551_alt with 2 data
Processing chr12_kb663607_fix with 268 data
Processing chr12_gl383553_alt with 81 data
Processing chr12_gl383552_alt with 4 data
Processing chr12_gl383550_alt with 81 data
Processing chr12_gl877876_alt with 214 data
Processing chr12_gl949745_alt with 198 data
Processing chr12_jh720444_fix with 1473 data
Processing chr12_gl877875_alt with 94 data
Processing chr12_gl582974_fix with 94 data
Processing chr11_jh159138_fix with 795 data
Processing chr11_jh720443_fix with 874 data
Processing chr11_jh159140_fix with 695 data
Processing chr11_jh159142_fix with 1526 data
Processing chr11_jh159139_fix with 74 data
Processing chr11_jh159141_fix with 108 data
Processing chr11_jh159143_fix with 282 data
Processing chr11_jh806581_fix with 141 data
Processing chr11_gl949744_fix with 29 data
Processing chr11_jh159137_alt with 33 data
Processing chr11_jh159136_alt with 75 data
Processing chr11_gl582973_fix with 39 data
Processing chr11_jh591185_fix with 237 data
Processing chr11_jh591184_fix with 107 data
Processing chr10_jh806580_fix with 61 data
Processing chr10_jh591182_fix with 230 data
Processing chr10_ke332501_fix with 97 data
Processing chr10_jh591183_fix with 454 data
Processing chr10_kb663606_fix with 707 data
Processing chr10_jh591181_fix with 4064 data
Processing chr10_gl383546_alt with 226 data
Processing chr10_gl383545_alt with 24 data
Processing chr10_gl383543_fix with 438 data
Processing chr10_jh636060_fix with 231 data
Processing chr10_gl877873_fix with 46 data
Processing chr9_gl383538_fix with 84 data
Processing chr9_gl383537_fix with 99 data
Processing chr9_jh806578_fix with 3 data
Processing chr9_jh806577_fix with 2 data
Processing chr9_gl339450_fix with 850 data
Processing chr9_jh806579_fix with 119 data
Processing chr9_kb663605_fix with 5 data
Processing chr9_gl383542_alt with 2 data
Processing chr9_gl383541_alt with 74 data
Processing chr9_gl383540_alt with 26 data
Processing chr9_jh636059_fix with 274 data
Processing chr9_gl383539_alt with 2 data
Processing chr8_gl383536_fix with 757 data
Processing chr8_gl383535_fix with 1590 data
Processing chr8_jh159135_fix with 115 data
Processing chr8_ke332500_fix with 688 data
Processing chr8_gl949743_fix with 93 data
Processing chr7_gl582971_fix with 1290 data
Processing chr7_gl383534_alt with 184 data
Processing chr7_jh636058_fix with 661 data
Processing chr7_gl582968_fix with 510 data
Processing chr7_gl582972_fix with 337 data
Processing chr7_jh159134_fix with 6140 data
Processing chr7_ke332499_fix with 57 data
Processing chr7_gl582969_fix with 25 data
Processing chr7_gl582970_fix with 42 data
Processing chr6_ke332498_fix with 17 data
Processing chr6_jh636056_fix with 359 data
Processing chr6_kb663604_fix with 161 data
Processing chr6_gl383533_alt with 4 data
Processing chr6_jh636057_fix with 149 data
Processing chr6_jh806576_fix with 84 data
Processing chr5_gl383531_alt with 2 data
Processing chr5_ke332497_fix with 501 data
Processing chr5_jh159133_fix with 856 data
Processing chr5_gl339449_alt with 1854 data
Processing chr5_gl949742_alt with 19 data
Processing chr4_gl877872_fix with 132 data
Processing chr4_gl383527_alt with 78 data
Processing chr4_gl582967_fix with 22 data
Processing chr4_gl383529_alt with 787 data
Processing chr4_ke332496_fix with 444 data
Processing chr3_gl383526_alt with 20 data
Processing chr3_gl383525_fix with 101 data
Processing chr3_jh159131_fix with 11 data
Processing chr3_gl383524_fix with 53 data
Processing chr3_ke332495_fix with 536 data
Processing chr3_gl383523_fix with 756 data
Processing chr3_jh159132_fix with 658 data
Processing chr3_jh636055_alt with 173 data
Processing chr2_gl877870_fix with 27 data
Processing chr2_gl383522_alt with 171 data
Processing chr2_gl582966_alt with 71 data
Processing chr2_gl877871_fix with 122 data
Processing chr2_kb663603_fix with 474 data
Processing chr2_gl383521_alt with 11 data
Processing chr1_gl383517_fix with 2 data
Processing chr1_gl383516_fix with 32 data
Processing chr1_jh806575_fix with 5 data
Processing chr1_jh636054_fix with 959 data
Processing chr1_jh806573_fix with 2 data
Processing chr1_gl383520_alt with 158 data
Processing chr1_gl383519_alt with 531 data
Processing chr1_gl383518_alt with 223 data
Processing chr1_jh636052_fix with 10886 data
Processing chr1_jh636053_fix with 575 data
Processing chr1_gl949741_fix with 146 data
Processing chr1_jh806574_fix with 3 data
Processing chrUn_gl000241 with 10 data
Processing chrUn_gl000236 with 2 data
Processing chrUn_gl000235 with 3 data
Processing chrUn_gl000231 with 6 data
Processing chrUn_gl000230 with 4 data
Processing chrUn_gl000229 with 2 data
Processing chrUn_gl000228 with 43 data
Processing chrUn_gl000224 with 4 data
Processing chrUn_gl000220 with 30 data
Processing chrUn_gl000219 with 8 data
Processing chrUn_gl000218 with 13 data
Processing chrUn_gl000215 with 2 data
Processing chrUn_gl000213 with 43 data
Processing chrUn_gl000212 with 17 data
Processing chrUn_gl000211 with 20 data
Processing chrY with 8468 data
Processing chrX with 59333 data
Processing chr22 with 39819 data
Processing chr21 with 20311 data
Processing chr20 with 42015 data
Processing chr19 with 95761 data
Processing chr18 with 34398 data
Processing chr17_gl000205_random with 4 data
Processing chr17 with 94307 data
Processing chr16 with 73227 data
Processing chr15 with 62803 data
Processing chr14 with 56060 data
Processing chr13 with 35299 data
Processing chr12 with 105694 data
Processing chr11 with 116373 data
Processing chr10 with 93765 data
Processing chr9 with 80498 data
Processing chr8 with 76169 data
Processing chr7_gl000195_random with 53 data
Processing chr7 with 96481 data
Processing chr6 with 97005 data
Processing chr5 with 82697 data
Processing chr4_gl000194_random with 27 data
Processing chr4_gl000193_random with 9 data
Processing chr4 with 79002 data
Processing chr3 with 130850 data
Processing chr2 with 149205 data
Processing chr1_gl000192_random with 64 data
Processing chr1 with 179608 data

## Combining similar `Chromosome`

In [11]:
# Flatten the glob result
def flatten_concatenation(matrix):
    flat_list = []
    for row in matrix:
        flat_list += row
    return flat_list

In [12]:
for chrom in tqdm(chrom_list):
    print(f"Processing chromosome: {chrom}")
    file_list = []
    file_list.append(glob.glob(f"dataset/ncbiRefSeq/raw/{chrom}.csv"))
    file_list.append(glob.glob(f"dataset/ncbiRefSeq/raw/{chrom}_*.csv"))
    flat_file_list = flatten_concatenation(file_list)

    data = []
    for filename in flat_file_list:
        print(f"Processing file: {filename}")
        df = pd.read_csv(filename)
        data.append(df)

    df_out = pd.concat(data, axis=0, ignore_index=False)
    df_out.to_csv(f"dataset/ncbiRefSeq/merged/{chrom}.csv", index=False)

print("Splitting ncbiRefSeq FINISHED!")

  0%|          | 0/24 [00:00<?, ?it/s]

Processing chromosome: chr1
Processing file: dataset/ncbiRefSeq/raw/chr1.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_gl000192_random.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_gl383516_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_gl383517_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_gl383518_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_gl383519_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_gl383520_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_gl949741_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_jh636052_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_jh636053_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_jh636054_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_jh806573_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_jh806574_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr1_jh806575_fix.csv
Processing chromosome: chr2
Processing file: dataset/ncbiRefSeq/raw/chr2.csv
Processing file: dataset/ncbiRefSeq/raw\chr2_gl383521_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr2_gl383522_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr2_gl582966_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr2_gl877870_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr2_gl877871_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr2_kb663603_fix.csv
Processing chromosome: chr3
Processing file: dataset/ncbiRefSeq/raw/chr3.csv
Processing file: dataset/ncbiRefSeq/raw\chr3_gl383523_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr3_gl383524_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr3_gl383525_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr3_gl383526_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr3_jh159131_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr3_jh159132_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr3_jh636055_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr3_ke332495_fix.csv
Processing chromosome: chr4
Processing file: dataset/ncbiRefSeq/raw/chr4.csv
Processing file: dataset/ncbiRefSeq/raw\chr4_ctg9_hap1.csv
Processing file: dataset/ncbiRefSeq/raw\chr4_gl000193_random.csv
Processing file: dataset/ncbiRefSeq/raw\chr4_gl000194_random.csv
Processing file: dataset/ncbiRefSeq/raw\chr4_gl383527_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr4_gl383529_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr4_gl582967_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr4_gl877872_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr4_ke332496_fix.csv
Processing chromosome: chr5
Processing file: dataset/ncbiRefSeq/raw/chr5.csv
Processing file: dataset/ncbiRefSeq/raw\chr5_gl339449_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr5_gl383531_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr5_gl949742_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr5_jh159133_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr5_ke332497_fix.csv
Processing chromosome: chr6
Processing file: dataset/ncbiRefSeq/raw/chr6.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_apd_hap1.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_cox_hap2.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_dbb_hap3.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_gl383533_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_jh636056_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_jh636057_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_jh806576_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_kb663604_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_ke332498_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_mann_hap4.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_mcf_hap5.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_qbl_hap6.csv
Processing file: dataset/ncbiRefSeq/raw\chr6_ssto_hap7.csv
Processing chromosome: chr7
Processing file: dataset/ncbiRefSeq/raw/chr7.csv
Processing file: dataset/ncbiRefSeq/raw\chr7_gl000195_random.csv
Processing file: dataset/ncbiRefSeq/raw\chr7_gl383534_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr7_gl582968_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr7_gl582969_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr7_gl582970_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr7_gl582971_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr7_gl582972_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr7_jh159134_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr7_jh636058_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr7_ke332499_fix.csv
Processing chromosome: chr8
Processing file: dataset/ncbiRefSeq/raw/chr8.csv
Processing file: dataset/ncbiRefSeq/raw\chr8_gl383535_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr8_gl383536_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr8_gl949743_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr8_jh159135_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr8_ke332500_fix.csv
Processing chromosome: chr9
Processing file: dataset/ncbiRefSeq/raw/chr9.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_gl339450_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_gl383537_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_gl383538_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_gl383539_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_gl383540_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_gl383541_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_gl383542_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_jh636059_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_jh806577_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_jh806578_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_jh806579_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr9_kb663605_fix.csv
Processing chromosome: chr10
Processing file: dataset/ncbiRefSeq/raw/chr10.csv
Processing file: dataset/ncbiRefSeq/raw\chr10_gl383543_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr10_gl383545_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr10_gl383546_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr10_gl877873_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr10_jh591181_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr10_jh591182_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr10_jh591183_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr10_jh636060_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr10_jh806580_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr10_kb663606_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr10_ke332501_fix.csv
Processing chromosome: chr11
Processing file: dataset/ncbiRefSeq/raw/chr11.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_gl582973_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_gl949744_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh159136_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh159137_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh159138_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh159139_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh159140_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh159141_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh159142_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh159143_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh591184_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh591185_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh720443_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr11_jh806581_fix.csv
Processing chromosome: chr12
Processing file: dataset/ncbiRefSeq/raw/chr12.csv
Processing file: dataset/ncbiRefSeq/raw\chr12_gl383548_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr12_gl383550_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr12_gl383551_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr12_gl383552_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr12_gl383553_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr12_gl582974_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr12_gl877875_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr12_gl877876_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr12_gl949745_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr12_jh720444_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr12_kb663607_fix.csv
Processing chromosome: chr13
Processing file: dataset/ncbiRefSeq/raw/chr13.csv
Processing file: dataset/ncbiRefSeq/raw\chr13_gl582975_fix.csv
Processing chromosome: chr14
Processing file: dataset/ncbiRefSeq/raw/chr14.csv
Processing file: dataset/ncbiRefSeq/raw\chr14_kb021645_fix.csv
Processing chromosome: chr15
Processing file: dataset/ncbiRefSeq/raw/chr15.csv
Processing file: dataset/ncbiRefSeq/raw\chr15_gl383554_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr15_gl383555_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr15_jh720445_fix.csv
Processing chromosome: chr16
Processing file: dataset/ncbiRefSeq/raw/chr16.csv
Processing file: dataset/ncbiRefSeq/raw\chr16_gl383556_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr16_gl383557_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr16_jh720446_fix.csv
Processing chromosome: chr17
Processing file: dataset/ncbiRefSeq/raw/chr17.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_ctg5_hap1.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_gl000205_random.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_gl383558_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_gl383559_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_gl383560_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_gl383561_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_gl383562_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_gl383563_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_gl383564_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_gl383566_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_gl582976_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_jh159144_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_jh159145_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_jh159146_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_jh159147_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_jh159148_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_jh591186_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_jh636061_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_jh720447_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_jh806582_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_kb021646_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr17_ke332502_fix.csv
Processing chromosome: chr18
Processing file: dataset/ncbiRefSeq/raw/chr18.csv
Processing file: dataset/ncbiRefSeq/raw\chr18_gl383567_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr18_gl383570_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr18_gl383571_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr18_gl383572_alt.csv
Processing chromosome: chr19
Processing file: dataset/ncbiRefSeq/raw/chr19.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl383573_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl383574_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl383575_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl383576_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl582977_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl949746_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl949747_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl949748_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl949749_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl949750_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl949751_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl949752_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_gl949753_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_jh159149_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_kb021647_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr19_ke332505_fix.csv
Processing chromosome: chr20
Processing file: dataset/ncbiRefSeq/raw/chr20.csv
Processing file: dataset/ncbiRefSeq/raw\chr20_gl582979_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr20_kb663608_fix.csv
Processing chromosome: chr21
Processing file: dataset/ncbiRefSeq/raw/chr21.csv
Processing file: dataset/ncbiRefSeq/raw\chr21_gl383579_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr21_gl383580_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr21_gl383581_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr21_ke332506_fix.csv
Processing chromosome: chr22
Processing file: dataset/ncbiRefSeq/raw/chr22.csv
Processing file: dataset/ncbiRefSeq/raw\chr22_gl383582_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr22_gl383583_alt.csv
Processing file: dataset/ncbiRefSeq/raw\chr22_jh720449_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr22_jh806584_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr22_jh806585_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr22_jh806586_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chr22_kb663609_alt.csv
Processing chromosome: chrX
Processing file: dataset/ncbiRefSeq/raw/chrX.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_gl877877_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh159150_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh720451_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh720452_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh720453_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh720454_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh720455_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806587_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806588_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806589_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806590_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806591_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806592_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806593_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806594_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806595_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806596_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806597_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806598_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806599_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806600_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806601_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806602_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_jh806603_fix.csv
Processing file: dataset/ncbiRefSeq/raw\chrX_kb021648_fix.csv
Processing chromosome: chrY
Processing file: dataset/ncbiRefSeq/raw/chrY.csv
Splitting ncbiRefSeq FINISHED!

# Counting Histone in TSS

In [ ]:
# Counting chrY
chrom = 'chrY'

histone_chr_df = pd.read_csv(f"dataset/histone/{chrom}.csv")
ncbiRefSeq_chr_df = pd.read_csv(f"dataset/ncbiRefSeq/merged/{chrom}.csv")

display(histone_chr_df.head())
print(histone_chr_df.shape)
display(ncbiRefSeq_chr_df.head())
print(ncbiRefSeq_chr_df.shape)

In [ ]:
tqdm.pandas()

In [ ]:
# Counting Histone
ncbiRefSeq_chr_df.loc[:, "histone_count"] = ncbiRefSeq_chr_df.progress_apply(\
                            lambda row: eu.count_histone(histone_chr_df, row), axis=1)

In [ ]:
display(ncbiRefSeq_chr_df.head())

In [ ]:
ncbiRefSeq_chr_df.to_csv(f"dataset/histone_count/{chrom}.csv", index=False)

In [ ]:
ax = ncbiRefSeq_chr_df.hist(column=["histone_count"])

In [ ]:
histone_path = "dataset/histone/"
ncbiRefSeq_path = "dataset/ncbiRefSeq/merged/"
output_path = "dataset/histone_count/"

In [ ]:
# chrUn and chrMT histone count should be 0

chrom = 'chrMT'

# Reading file
ncbiRefSeq_chr_df = pd.read_csv(f"{ncbiRefSeq_path}{chrom}.csv")

# Histone count = 0
ncbiRefSeq_chr_df.loc[:, "histone_count"] = 0
display(ncbiRefSeq_chr_df.head())

# Saving the result
ncbiRefSeq_chr_df.to_csv(f"{output_path}{chrom}.csv", index=False)

In [ ]:
# Run the counting_histone.py to get the result
# Getting all the results back to dataframe

file_list = []
file_list.append(glob.glob(f"{output_path}*.csv"))
flat_file_list = flatten_concatenation(file_list)
print(flat_file_list)

In [ ]:
data = []
for filename in tqdm(flat_file_list):
    df = pd.read_csv(filename)
    data.append(df)

df_out = pd.concat(data, axis=0, ignore_index=False)
df_out.to_csv(f"{output_path}histone_count.csv", index=False)

In [ ]:
display(df_out.head())
display(df_out.shape)

In [ ]:
ax = df_out.hist(column=["histone_count"])

In [ ]:
# Check the frequency of each histone count
df_out.groupby(['histone_count']).size().reset_index(name='counts')

# Splitting HepG2 data

## Loading and Preparing the Data

In [13]:
# Loading HepG2 data
hepg2_exp = pd.read_csv("dataset/GSM3718064_HepG2_exp.txt", sep="\t")

In [14]:
# Splitting chromosome name and the position
hepg2_exp[["chrom", "chromPos"]] = hepg2_exp["locus"].str.split(':', expand=True)
display(hepg2_exp.head())

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,log2(fold_change),test_stat,p_value,q_value,significant,chrom,chromPos
0,XLOC_000001,XLOC_000001,OR4F5,chr1:69090-70008,hepg2_hr2,hepg2_hr3,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no,chr1,69090-70008
1,XLOC_000002,XLOC_000002,"LOC100132062,LOC100133331",chr1:323891-328581,hepg2_hr2,hepg2_hr3,NOTEST,0.047392,0.034159,-0.472389,0.000000,1.00000,1.000000,no,chr1,323891-328581
2,XLOC_000003,XLOC_000003,OR4F29,chr1:367658-368597,hepg2_hr2,hepg2_hr3,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no,chr1,367658-368597
3,XLOC_000004,XLOC_000004,LOC643837,chr1:761585-794889,hepg2_hr2,hepg2_hr3,OK,2.468570,2.805800,0.184736,0.455074,0.63585,0.999565,no,chr1,761585-794889
4,XLOC_000005,XLOC_000005,-,chr1:840263-843900,hepg2_hr2,hepg2_hr3,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no,chr1,840263-843900

In [15]:
# Splitting start and end position
hepg2_exp[["chromStart", "chromEnd"]] = hepg2_exp["chromPos"].str.split('-', expand=True)
display(hepg2_exp.head())

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,log2(fold_change),test_stat,p_value,q_value,significant,chrom,chromPos,chromStart,chromEnd
0,XLOC_000001,XLOC_000001,OR4F5,chr1:69090-70008,hepg2_hr2,hepg2_hr3,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no,chr1,69090-70008,69090,70008
1,XLOC_000002,XLOC_000002,"LOC100132062,LOC100133331",chr1:323891-328581,hepg2_hr2,hepg2_hr3,NOTEST,0.047392,0.034159,-0.472389,0.000000,1.00000,1.000000,no,chr1,323891-328581,323891,328581
2,XLOC_000003,XLOC_000003,OR4F29,chr1:367658-368597,hepg2_hr2,hepg2_hr3,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no,chr1,367658-368597,367658,368597
3,XLOC_000004,XLOC_000004,LOC643837,chr1:761585-794889,hepg2_hr2,hepg2_hr3,OK,2.468570,2.805800,0.184736,0.455074,0.63585,0.999565,no,chr1,761585-794889,761585,794889
4,XLOC_000005,XLOC_000005,-,chr1:840263-843900,hepg2_hr2,hepg2_hr3,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no,chr1,840263-843900,840263,843900

In [16]:
# Correcting the Data Types
hepg2_exp = hepg2_exp.astype({'chromStart': 'int32', 'chromEnd': 'int32'})

In [30]:
hepg2_exp.columns.values

array(['test_id', 'gene_id', 'gene', 'locus', 'sample_1', 'sample_2',
       'status', 'value_1', 'value_2', 'log2(fold_change)', 'test_stat',
       'p_value', 'q_value', 'significant', 'chrom', 'chromPos',
       'chromStart', 'chromEnd'], dtype=object)

In [31]:
hepg2_exp_selected = hepg2_exp[['test_id', 'gene_id', 'gene', 'locus', 'sample_1', 'sample_2',
       'status', 'value_1', 'value_2', 'log2(fold_change)', 'test_stat',
       'p_value', 'q_value', 'significant', 'chrom', 'chromStart', 'chromEnd']]

In [32]:
display(hepg2_exp_selected)

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,log2(fold_change),test_stat,p_value,q_value,significant,chrom,chromStart,chromEnd
0,XLOC_000001,XLOC_000001,OR4F5,chr1:69090-70008,hepg2_hr2,hepg2_hr3,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no,chr1,69090,70008
1,XLOC_000002,XLOC_000002,"LOC100132062,LOC100133331",chr1:323891-328581,hepg2_hr2,hepg2_hr3,NOTEST,0.047392,0.034159,-0.472389,0.000000,1.00000,1.000000,no,chr1,323891,328581
2,XLOC_000003,XLOC_000003,OR4F29,chr1:367658-368597,hepg2_hr2,hepg2_hr3,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no,chr1,367658,368597
3,XLOC_000004,XLOC_000004,LOC643837,chr1:761585-794889,hepg2_hr2,hepg2_hr3,OK,2.468570,2.805800,0.184736,0.455074,0.63585,0.999565,no,chr1,761585,794889
4,XLOC_000005,XLOC_000005,-,chr1:840263-843900,hepg2_hr2,hepg2_hr3,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no,chr1,840263,843900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30027,XLOC_030028,XLOC_030028,-,chrY:13319431-13324829,hepg2_hr2,hepg2_hr3,OK,0.337879,0.457897,0.438516,1.137930,0.25685,0.999565,no,chrY,13319431,13324829
30028,XLOC_030029,XLOC_030029,-,chrY:13325034-13326120,hepg2_hr2,hepg2_hr3,NOTEST,0.396888,0.357658,-0.150148,0.000000,1.00000,1.000000,no,chrY,13325034,13326120
30029,XLOC_030030,XLOC_030030,-,chrY:13331089-13332358,hepg2_hr2,hepg2_hr3,OK,0.477227,0.127331,-1.906090,-1.861920,0.12490,0.999565,no,chrY,13331089,13332358
30030,XLOC_030031,XLOC_030031,-,chrY:15053270-15053343,hepg2_hr2,hepg2_hr3,OK,123998.000000,71768.700000,-0.788894,-2.116040,0.04075,0.999565,no,chrY,15053270,15053343
30031,XLOC_030032,XLOC_030032,-,chrY:59001259-59003893,hepg2_hr2,hepg2_hr3,OK,0.456876,0.412647,-0.146892,-0.291421,0.76840,0.999565,no,chrY,59001259,59003893

In [ ]:
# # Find the gene's length
# hepg2_exp["gene_length"] = hepg2_exp["chromEnd"] - hepg2_exp["chromStart"]
# display(hepg2_exp)

In [ ]:
# # Find the gene length distribution
# ax = hepg2_exp.hist(column=["gene_length"])

In [ ]:
# # Find the frequency of gene length
# hepg2_exp.groupby(['gene_length']).size().reset_index(name='counts')

In [ ]:
# hepg2_exp.groupby(['gene_length'])['gene_length'].size().reset_index(name='counts').to_csv("dataset/HepG2/gene_length.csv", index=False)

## Splitting into each Chromosome

In [33]:
hepg2_chromlist = hepg2_exp_selected["chrom"].unique().tolist()
display(hepg2_chromlist)

['chr1',
 'chr10',
 'chr11',
 'chr12',
 'chr13',
 'chr14',
 'chr15',
 'chr16',
 'chr17',
 'chr17_ctg5_hap1',
 'chr17_gl000205_random',
 'chr18',
 'chr19',
 'chr19_gl000209_random',
 'chr1_gl000191_random',
 'chr2',
 'chr20',
 'chr21',
 'chr22',
 'chr3',
 'chr4',
 'chr4_ctg9_hap1',
 'chr4_gl000194_random',
 'chr5',
 'chr6',
 'chr6_apd_hap1',
 'chr6_cox_hap2',
 'chr6_dbb_hap3',
 'chr6_mann_hap4',
 'chr6_mcf_hap5',
 'chr6_qbl_hap6',
 'chr6_ssto_hap7',
 'chr7',
 'chr8',
 'chr9',
 'chrM',
 'chrUn_gl000211',
 'chrUn_gl000212',
 'chrUn_gl000218',
 'chrUn_gl000219',
 'chrUn_gl000220',
 'chrUn_gl000222',
 'chrUn_gl000223',
 'chrUn_gl000228',
 'chrX',
 'chrY']

In [34]:
print(f"Splitting into {len(hepg2_chromlist)} files.")

num_file = 1

for chrom in tqdm(hepg2_chromlist):
    df = hepg2_exp_selected[hepg2_exp_selected['chrom'] == chrom]
    print(f"File {num_file}: Processing {chrom} with {len(df.index)} data")
    df.to_csv(f"dataset/HepG2/raw/{chrom}.csv", index=False)
    num_file+=1

Splitting into 46 files.

  0%|          | 0/46 [00:00<?, ?it/s]

File 1: Processing chr1 with 2867 data
File 2: Processing chr10 with 1181 data
File 3: Processing chr11 with 1618 data
File 4: Processing chr12 with 1395 data
File 5: Processing chr13 with 542 data
File 6: Processing chr14 with 1030 data
File 7: Processing chr15 with 984 data
File 8: Processing chr16 with 1149 data
File 9: Processing chr17 with 1581 data
File 10: Processing chr17_ctg5_hap1 with 22 data
File 11: Processing chr17_gl000205_random with 1 data
File 12: Processing chr18 with 454 data
File 13: Processing chr19 with 1711 data
File 14: Processing chr19_gl000209_random with 8 data
File 15: Processing chr1_gl000191_random with 1 data
File 16: Processing chr2 with 1880 data
File 17: Processing chr20 with 785 data
File 18: Processing chr21 with 419 data
File 19: Processing chr22 with 656 data
File 20: Processing chr3 with 1581 data
File 21: Processing chr4 with 1137 data
File 22: Processing chr4_ctg9_hap1 with 6 data
File 23: Processing chr4_gl000194_random with 1 data
File 24: Processing chr5 with 1328 data
File 25: Processing chr6 with 1558 data
File 26: Processing chr6_apd_hap1 with 96 data
File 27: Processing chr6_cox_hap2 with 190 data
File 28: Processing chr6_dbb_hap3 with 178 data
File 29: Processing chr6_mann_hap4 with 149 data
File 30: Processing chr6_mcf_hap5 with 174 data
File 31: Processing chr6_qbl_hap6 with 178 data
File 32: Processing chr6_ssto_hap7 with 158 data
File 33: Processing chr7 with 1424 data
File 34: Processing chr8 with 1101 data
File 35: Processing chr9 with 1217 data
File 36: Processing chrM with 1 data
File 37: Processing chrUn_gl000211 with 1 data
File 38: Processing chrUn_gl000212 with 1 data
File 39: Processing chrUn_gl000218 with 1 data
File 40: Processing chrUn_gl000219 with 1 data
File 41: Processing chrUn_gl000220 with 2 data
File 42: Processing chrUn_gl000222 with 2 data
File 43: Processing chrUn_gl000223 with 2 data
File 44: Processing chrUn_gl000228 with 13 data
File 45: Processing chrX with 1113 data
File 46: Processing chrY with 135 data

## Combining similar chromosome

In [35]:
for chrom in tqdm(chrom_list):
    print(f"Processing chromosome: {chrom}")
    file_list = []
    file_list.append(glob.glob(f"dataset/HepG2/raw/{chrom}.csv"))
    file_list.append(glob.glob(f"dataset/HepG2/raw/{chrom}_*.csv"))
    flat_file_list = flatten_concatenation(file_list)

    data = []
    for filename in flat_file_list:
        print(f"Processing file: {filename}")
        df = pd.read_csv(filename)
        data.append(df)

    df_out = pd.concat(data, axis=0, ignore_index=False)
    df_out.to_csv(f"dataset/HepG2/merged/{chrom}.csv", index=False)

print("Splitting HepG2 FINISHED!")

  0%|          | 0/24 [00:00<?, ?it/s]

Processing chromosome: chr1
Processing file: dataset/HepG2/raw/chr1.csv
Processing file: dataset/HepG2/raw\chr1_gl000191_random.csv
Processing chromosome: chr2
Processing file: dataset/HepG2/raw/chr2.csv
Processing chromosome: chr3
Processing file: dataset/HepG2/raw/chr3.csv
Processing chromosome: chr4
Processing file: dataset/HepG2/raw/chr4.csv
Processing file: dataset/HepG2/raw\chr4_ctg9_hap1.csv
Processing file: dataset/HepG2/raw\chr4_gl000194_random.csv
Processing chromosome: chr5
Processing file: dataset/HepG2/raw/chr5.csv
Processing chromosome: chr6
Processing file: dataset/HepG2/raw/chr6.csv
Processing file: dataset/HepG2/raw\chr6_apd_hap1.csv
Processing file: dataset/HepG2/raw\chr6_cox_hap2.csv
Processing file: dataset/HepG2/raw\chr6_dbb_hap3.csv
Processing file: dataset/HepG2/raw\chr6_mann_hap4.csv
Processing file: dataset/HepG2/raw\chr6_mcf_hap5.csv
Processing file: dataset/HepG2/raw\chr6_qbl_hap6.csv
Processing file: dataset/HepG2/raw\chr6_ssto_hap7.csv
Processing chromosome: chr7
Processing file: dataset/HepG2/raw/chr7.csv
Processing chromosome: chr8
Processing file: dataset/HepG2/raw/chr8.csv
Processing chromosome: chr9
Processing file: dataset/HepG2/raw/chr9.csv
Processing chromosome: chr10
Processing file: dataset/HepG2/raw/chr10.csv
Processing chromosome: chr11
Processing file: dataset/HepG2/raw/chr11.csv
Processing chromosome: chr12
Processing file: dataset/HepG2/raw/chr12.csv
Processing chromosome: chr13
Processing file: dataset/HepG2/raw/chr13.csv
Processing chromosome: chr14
Processing file: dataset/HepG2/raw/chr14.csv
Processing chromosome: chr15
Processing file: dataset/HepG2/raw/chr15.csv
Processing chromosome: chr16
Processing file: dataset/HepG2/raw/chr16.csv
Processing chromosome: chr17
Processing file: dataset/HepG2/raw/chr17.csv
Processing file: dataset/HepG2/raw\chr17_ctg5_hap1.csv
Processing file: dataset/HepG2/raw\chr17_gl000205_random.csv
Processing chromosome: chr18
Processing file: dataset/HepG2/raw/chr18.csv
Processing chromosome: chr19
Processing file: dataset/HepG2/raw/chr19.csv
Processing file: dataset/HepG2/raw\chr19_gl000209_random.csv
Processing chromosome: chr20
Processing file: dataset/HepG2/raw/chr20.csv
Processing chromosome: chr21
Processing file: dataset/HepG2/raw/chr21.csv
Processing chromosome: chr22
Processing file: dataset/HepG2/raw/chr22.csv
Processing chromosome: chrX
Processing file: dataset/HepG2/raw/chrX.csv
Processing chromosome: chrY
Processing file: dataset/HepG2/raw/chrY.csv
Splitting HepG2 FINISHED!

## Changing 'chrM' into 'chrMT' (NOT REQUIRED)

In [ ]:
import os

hepg2_chrMT = pd.read_csv("dataset/HepG2/merged/chrM.csv")
hepg2_chrMT.head()

In [ ]:
hepg2_chrMT["chrom"] = "chrMT"
hepg2_chrMT.head()

In [ ]:
hepg2_chrMT.to_csv(f"dataset/HepG2/merged/chrMT.csv", index=False)

# Counting Gene Expression in the +/-2k from TSS

In [ ]:
from tqdm.auto import tqdm
tqdm.pandas()

In [ ]:
def count_gene(gene_df, row, threshold = 0.8, tss_length = 4000):
    tss = row["tss"]
    hist_df = gene_df.loc[  # Inside the +/- 2k from TSS
                             (((gene_df["chromStart"] >= tss - 2000) & (gene_df["chromEnd"] <= tss + 2000)) |
                             
                             # Intersect with -2k or +2 from TSS
                             (((gene_df["chromEnd"] - (tss - 2000))/tss_length).between(threshold, 1.0)) |
                             ((((tss + 2000) - gene_df["chromStart"])/tss_length).between(threshold, 1.0))) |
                             
                             # TSS inside the gene
                             ((tss + 2000 <= gene_df["chromEnd"]) & (tss - 2000 >= gene_df["chromStart"]))
                        ]
    
    return len(hist_df.index)

In [ ]:
# Counting chr1
chrom = 'chr1'

gene_chr_df = pd.read_csv(f"dataset/HepG2/merged/{chrom}.csv")
ncbiRefSeq_chr_df = pd.read_csv(f"dataset/histone_count/{chrom}.csv")

display(gene_chr_df.head())
print(gene_chr_df.shape)
display(ncbiRefSeq_chr_df.head())
print(ncbiRefSeq_chr_df.shape)

In [ ]:
# Counting Gene
ncbiRefSeq_chr_df.loc[:, "gene_count"] = ncbiRefSeq_chr_df.progress_apply(\
                            lambda row: count_gene(gene_chr_df, row), axis=1)

In [ ]:
display(ncbiRefSeq_chr_df.head())

In [ ]:
ax = ncbiRefSeq_chr_df.hist(column=["gene_count"])

In [ ]:
ncbiRefSeq_chr_df.groupby(['gene_count']).size().reset_index(name='counts')

In [ ]:
ncbiRefSeq_chr_df.groupby(['gene_count']).size().reset_index(name='counts').\
        to_csv(f"dataset/gene_count/gene_count_{chrom}.csv", index=False)

In [ ]:
ncbiRefSeq_chr_df[(ncbiRefSeq_chr_df['gene_count'] >= 4) & (ncbiRefSeq_chr_df['histone_count'] > 20)]

In [ ]:
ncbiRefSeq_chr_df.groupby(['histone_count', 'gene_count']).size().reset_index(name='counts')

In [ ]:
ncbiRefSeq_chr_df.groupby(['histone_count', 'gene_count']).size().reset_index(name='counts').\
    to_csv(f"dataset/histone_gene_count.csv", index=False)