In [1]:
import pandas as pd
import numpy as np

from tqdm.auto import tqdm

In [2]:
tqdm.pandas()

# Data Preparation

## Load Data

In [4]:
# Read the CSV file
mylist = []

for chunk in pd.read_csv('gene_exp.csv', chunksize=20000):
    mylist.append(chunk)

gene_exp_df = pd.concat(mylist, axis = 0)
del mylist

In [5]:
display(gene_exp_df.head())
display(gene_exp_df.shape)

,h_chrom,h_chromStart,h_chromEnd,h_value_1,n_strand,tss,tss_start,tss_end,h3k4me3,h3k9ac,h3k9me3,h3k27ac,h3k27me3
0,chr1,69090,70008,0.000000,+,65418,63418,67418,"0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...."
1,chr1,323891,328581,0.047392,+,323891,321891,325891,"0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...."
2,chr1,367658,368597,0.000000,+,367658,365658,369658,"0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...."
3,chr1,761585,794889,2.468570,+,762970,760970,764970,"0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...."
4,chr1,761585,794889,2.468570,+,762970,760970,764970,"0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0....","0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0...."

(59366, 13)

In [1]:
59366 * 4000 * 5

1187320000

## Convert into array column

In [6]:
# Convert string representation back to arrays
gene_exp_df.loc[:, 'h3k4me3']  = gene_exp_df['h3k4me3'].apply(lambda x: np.array(list(map(float, x.split(',')))))
gene_exp_df.loc[:, 'h3k9ac']   = gene_exp_df['h3k9ac'].apply(lambda x: np.array(list(map(float, x.split(',')))))
gene_exp_df.loc[:, 'h3k9me3']  = gene_exp_df['h3k9me3'].apply(lambda x: np.array(list(map(float, x.split(',')))))
gene_exp_df.loc[:, 'h3k27ac']  = gene_exp_df['h3k27ac'].apply(lambda x: np.array(list(map(float, x.split(',')))))
gene_exp_df.loc[:, 'h3k27me3'] = gene_exp_df['h3k27me3'].apply(lambda x: np.array(list(map(float, x.split(',')))))

In [8]:
display(gene_exp_df.head())
display(gene_exp_df.shape)

,h_chrom,h_chromStart,h_chromEnd,h_value_1,n_strand,tss,tss_start,tss_end,h3k4me3,h3k9ac,h3k9me3,h3k27ac,h3k27me3
0,chr1,69090,70008,0.000000,+,65418,63418,67418,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,chr1,323891,328581,0.047392,+,323891,321891,325891,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,chr1,367658,368597,0.000000,+,367658,365658,369658,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,chr1,761585,794889,2.468570,+,762970,760970,764970,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,chr1,761585,794889,2.468570,+,762970,760970,764970,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

(59366, 13)

In [9]:
gene_exp_df.to_parquet("gene_exp.parquet")

ArrowMemoryError: realloc of size 973078528 failed

## Explode array column into columns

In [8]:
# Convert the array column into a DataFrame, each array element becomes a column
h3k4me3_df = pd.DataFrame(gene_exp_df['h3k4me3'].tolist())
h3k4me3_df.columns = [f'h3k4me3_{i}' for i in range(h3k4me3_df.shape[1])]
display(h3k4me3_df.head())

,h3k4me3_0,h3k4me3_1,h3k4me3_2,h3k4me3_3,h3k4me3_4,h3k4me3_5,h3k4me3_6,h3k4me3_7,h3k4me3_8,h3k4me3_9,...,h3k4me3_3990,h3k4me3_3991,h3k4me3_3992,h3k4me3_3993,h3k4me3_3994,h3k4me3_3995,h3k4me3_3996,h3k4me3_3997,h3k4me3_3998,h3k4me3_3999
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
h3k9ac_df = pd.DataFrame(gene_exp_df['h3k9ac'].tolist())
h3k9ac_df.columns = [f'h3k9ac_{i}' for i in range(h3k9ac_df.shape[1])]
display(h3k9ac_df.head())

In [ ]:
h3k9me3_df = pd.DataFrame(gene_exp_df['h3k9me3'].tolist())
h3k9me3_df.columns = [f'h3k9me3_{i}' for i in range(h3k9me3_df.shape[1])]
display(h3k9me3_df.head())

In [ ]:
h3k27ac_df = pd.DataFrame(gene_exp_df['h3k27ac'].tolist())
h3k27ac_df.columns = [f'h3k27ac_{i}' for i in range(h3k27ac_df.shape[1])]
display(h3k27ac_df.head())

In [ ]:
h3k27me3_df = pd.DataFrame(gene_exp_df['h3k27me3'].tolist())
h3k27me3_df.columns = [f'h3k27ac_{i}' for i in range(h3k27me3_df.shape[1])]
display(h3k27ac_df.head())

In [ ]:
# gene_exp_df = pd.concat([gene_exp_df.drop('h3k4me3', axis=1), h3k4me3_df], axis=1)
# display(gene_exp_df.head())

# XGBoost Modeling