In [15]:
import polars as pl
import os

from pathlib import Path

In [16]:
WORKING_PATH = Path('/group/pmc021/amunif/epi-thesis/workflow/17_Pairwise Ranking HepG2 GSE76344/')
DATASET_PATH = WORKING_PATH / 'dataset'
OUTPUT_PATH  = WORKING_PATH / 'output' / 'combined'

# Merge the experiment results

In [17]:
# Read all CSV into single dataframe
pl_df = pl.read_csv(OUTPUT_PATH / 'test' / "*-test-metrics.csv")

In [18]:
pl_df

shape: (620, 13)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬─────────┬────────────┐
│ model      ┆ seed ┆ histone_ma ┆ epochs_tra ┆ … ┆ test_preci ┆ test_recal ┆ test_f1 ┆ antisymmet │
│ ---        ┆ ---  ┆ rker       ┆ ined       ┆   ┆ sion       ┆ l          ┆ ---     ┆ ry         │
│ str        ┆ i64  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64     ┆ ---        │
│            ┆      ┆ str        ┆ i64        ┆   ┆ f64        ┆ f64        ┆         ┆ f64        │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪═════════╪════════════╡
│ DirectRank ┆ 1011 ┆ H3K4me3    ┆ 42         ┆ … ┆ 0.6434     ┆ 0.7231     ┆ 0.6809  ┆ 0.903      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7234     ┆ 0.6322     ┆ 0.6748  ┆ 0.752      │
│ gression   ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7039     ┆ 0.6384     ┆ 0.6696  ┆ 0.741      │
│ st         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7251     ┆ 0.6322     ┆ 0.6755  ┆ 0.751      │
│ DirectRank ┆ 123  ┆ H3K4me3    ┆ 46         ┆ … ┆ 0.6508     ┆ 0.7386     ┆ 0.6919  ┆ 0.902      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …       ┆ …          │
│ SVM_Linear ┆ 456  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.6401     ┆ 0.5903     ┆ 0.6142  ┆ 0.702      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ DirectRank ┆ 789  ┆ H3K4me3-H3 ┆ 100        ┆ … ┆ 0.681      ┆ 0.7296     ┆ 0.7045  ┆ 0.976      │
│ er         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.6802     ┆ 0.6331     ┆ 0.6558  ┆ 0.701      │
│ gression   ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7086     ┆ 0.7086     ┆ 0.7086  ┆ 0.763      │
│ st         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.6959     ┆ 0.5996     ┆ 0.6441  ┆ 0.678      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴─────────┴────────────┘

In [19]:
# Save the results by model 
MODEL_RESULT_FOLDER = OUTPUT_PATH / 'model_results'
os.makedirs(MODEL_RESULT_FOLDER, exist_ok=True)

for model_name in pl_df["model"].unique():
    pl_df.filter(pl_df["model"] == model_name).write_csv(MODEL_RESULT_FOLDER / f"{model_name}.csv", include_header=True)

In [20]:
# Save the results for all models and all seeds
pl_df.write_csv(OUTPUT_PATH / "GSE76344_all_results.csv", include_header=True)

In [31]:
summary_df = (
    pl_df
    .group_by(["histone_marker", "model"])
    .agg([
        pl.col("val_accuracy").mean().alias("val_accuracy_mean"),
        pl.col("val_accuracy").std().alias("val_accuracy_std"),
        pl.col("val_auc").mean().alias("val_auc_mean"),
        pl.col("val_auc").std().alias("val_auc_std"),
        pl.col("test_accuracy").mean().alias("test_accuracy_mean"),
        pl.col("test_accuracy").std().alias("test_accuracy_std"),
        pl.col("test_auc").mean().alias("test_auc_mean"),
        pl.col("test_auc").std().alias("test_auc_std"),
        pl.col("test_aucprc").mean().alias("test_aucprc_mean"),
        pl.col("test_aucprc").std().alias("test_aucprc_std"),
        pl.col("antisymmetry").mean().alias("antisymmetry_mean"),
        pl.col("antisymmetry").std().alias("antisymmetry_std")
    ])
    .sort(["histone_marker", "test_accuracy_mean"], descending=[False, True])
    .with_columns(pl.col(pl.Float64).round(4))
)

In [32]:
summary_df

shape: (124, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ model     ┆ val_accur ┆ val_accur ┆ … ┆ test_aucp ┆ test_aucp ┆ antisymme ┆ antisymm │
│ arker     ┆ ---       ┆ acy_mean  ┆ acy_std   ┆   ┆ rc_mean   ┆ rc_std    ┆ try_mean  ┆ etry_std │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K27ac   ┆ RandomFor ┆ 70.16     ┆ 1.6134    ┆ … ┆ 0.7434    ┆ 0.0226    ┆ 0.7262    ┆ 0.0101   │
│           ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ LogisticR ┆ 68.4      ┆ 1.8398    ┆ … ┆ 0.6744    ┆ 0.0205    ┆ 0.7192    ┆ 0.0109   │
│           ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ SVM_Linea ┆ 68.38     ┆ 1.8472    ┆ … ┆ 0.6743    ┆ 0.0199    ┆ 0.7112    ┆ 0.0192   │
│           ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ DirectRan ┆ 67.76     ┆ 2.2546    ┆ … ┆ 0.7219    ┆ 0.0192    ┆ 0.8722    ┆ 0.0043   │
│           ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac-H ┆ RandomFor ┆ 70.32     ┆ 2.4641    ┆ … ┆ 0.7534    ┆ 0.0201    ┆ 0.7504    ┆ 0.0076   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K9me3-H ┆ SVM_Linea ┆ 66.12     ┆ 1.8647    ┆ … ┆ 0.6647    ┆ 0.0252    ┆ 0.7178    ┆ 0.0206   │
│ 3K27ac-H3 ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27me3    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ RandomFor ┆ 65.04     ┆ 2.305     ┆ … ┆ 0.6607    ┆ 0.0257    ┆ 0.7394    ┆ 0.0209   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ DirectRan ┆ 64.04     ┆ 1.4639    ┆ … ┆ 0.6707    ┆ 0.0311    ┆ 0.8876    ┆ 0.0141   │
│ 3K27me3   ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ LogisticR ┆ 61.48     ┆ 1.1167    ┆ … ┆ 0.6298    ┆ 0.0233    ┆ 0.6616    ┆ 0.0261   │
│ 3K27me3   ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ SVM_Linea ┆ 61.24     ┆ 1.2462    ┆ … ┆ 0.6293    ┆ 0.0248    ┆ 0.6404    ┆ 0.0311   │
│ 3K27me3   ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
summary_df.write_csv(OUTPUT_PATH/ f"HepG2 GSE76344 Ranking.csv", include_header=True)

In [24]:
for model_name in summary_df["model"].unique():
    summary_df.filter(summary_df["model"] == model_name).write_csv(MODEL_RESULT_FOLDER / f"{model_name}_summary.csv", include_header=True)

# Merge the label distribution

In [25]:
# Read all label distribution CSV into single dataframe
label_df = pl.read_csv(OUTPUT_PATH / 'test' / "*-label-distribution.csv")

In [26]:
label_df

shape: (930, 7)
┌──────┬─────────────────────────────────┬───────┬───────┬───────┬───────┬────────────┐
│ seed ┆ histone_marker                  ┆ split ┆ label ┆ count ┆ total ┆ percentage │
│ ---  ┆ ---                             ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---        │
│ i64  ┆ str                             ┆ str   ┆ i64   ┆ i64   ┆ i64   ┆ f64        │
╞══════╪═════════════════════════════════╪═══════╪═══════╪═══════╪═══════╪════════════╡
│ 1011 ┆ H3K4me3                         ┆ Train ┆ 0     ┆ 4208  ┆ 8000  ┆ 52.6       │
│ 1011 ┆ H3K4me3                         ┆ Train ┆ 1     ┆ 3792  ┆ 8000  ┆ 47.4       │
│ 1011 ┆ H3K4me3                         ┆ Val   ┆ 0     ┆ 516   ┆ 1000  ┆ 51.6       │
│ 1011 ┆ H3K4me3                         ┆ Val   ┆ 1     ┆ 484   ┆ 1000  ┆ 48.4       │
│ 1011 ┆ H3K4me3                         ┆ Test  ┆ 0     ┆ 516   ┆ 1000  ┆ 51.6       │
│ …    ┆ …                               ┆ …     ┆ …     ┆ …     ┆ …     ┆ …          │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Train ┆ 1     ┆ 3743  ┆ 8000  ┆ 46.79      │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Val   ┆ 0     ┆ 535   ┆ 1000  ┆ 53.5       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Val   ┆ 1     ┆ 465   ┆ 1000  ┆ 46.5       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Test  ┆ 0     ┆ 523   ┆ 1000  ┆ 52.3       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Test  ┆ 1     ┆ 477   ┆ 1000  ┆ 47.7       │
└──────┴─────────────────────────────────┴───────┴───────┴───────┴───────┴────────────┘

In [27]:
# Make the summary by seed, split and label
label_summary_df = (
    label_df
    .group_by(['split', 'label'])
    .agg(pl.col('percentage').mean().round(2).alias('average_percentage_%'))
    .sort(['split', 'label'])
)

In [28]:
label_summary_df

shape: (6, 3)
┌───────┬───────┬──────────────────────┐
│ split ┆ label ┆ average_percentage_% │
│ ---   ┆ ---   ┆ ---                  │
│ str   ┆ i64   ┆ f64                  │
╞═══════╪═══════╪══════════════════════╡
│ Test  ┆ 0     ┆ 52.32                │
│ Test  ┆ 1     ┆ 47.68                │
│ Train ┆ 0     ┆ 52.72                │
│ Train ┆ 1     ┆ 47.28                │
│ Val   ┆ 0     ┆ 51.44                │
│ Val   ┆ 1     ┆ 48.56                │
└───────┴───────┴──────────────────────┘