In [8]:
import polars as pl
import os

from pathlib import Path

In [9]:
WORKING_PATH = Path('/group/pmc021/amunif/epi-thesis/workflow/17_Pairwise Ranking HepG2 GSE76344/')
DATASET_PATH = WORKING_PATH / 'dataset'
OUTPUT_PATH  = WORKING_PATH / 'output' / 'combined'

In [13]:
### Merge the results into single CSV file

# Read all CSV into single dataframe
pl_df = pl.read_csv(OUTPUT_PATH / 'test' / "*-test-metrics.csv")

In [14]:
pl_df

shape: (620, 12)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬─────────┬────────────┐
│ model      ┆ seed ┆ histone_ma ┆ epochs_tra ┆ … ┆ test_preci ┆ test_recal ┆ test_f1 ┆ antisymmet │
│ ---        ┆ ---  ┆ rker       ┆ ined       ┆   ┆ sion       ┆ l          ┆ ---     ┆ ry         │
│ str        ┆ i64  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64     ┆ ---        │
│            ┆      ┆ str        ┆ i64        ┆   ┆ f64        ┆ f64        ┆         ┆ f64        │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪═════════╪════════════╡
│ DirectRank ┆ 1011 ┆ H3K4me3    ┆ 42         ┆ … ┆ 0.6434     ┆ 0.7231     ┆ 0.6809  ┆ 0.903      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7234     ┆ 0.6322     ┆ 0.6748  ┆ 0.752      │
│ gression   ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7039     ┆ 0.6384     ┆ 0.6696  ┆ 0.741      │
│ st         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7251     ┆ 0.6322     ┆ 0.6755  ┆ 0.751      │
│ DirectRank ┆ 123  ┆ H3K4me3    ┆ 46         ┆ … ┆ 0.6508     ┆ 0.7386     ┆ 0.6919  ┆ 0.902      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …       ┆ …          │
│ SVM_Linear ┆ 456  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.6401     ┆ 0.5903     ┆ 0.6142  ┆ 0.702      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ DirectRank ┆ 789  ┆ H3K4me3-H3 ┆ 100        ┆ … ┆ 0.681      ┆ 0.7296     ┆ 0.7045  ┆ 0.976      │
│ er         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.6802     ┆ 0.6331     ┆ 0.6558  ┆ 0.701      │
│ gression   ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7086     ┆ 0.7086     ┆ 0.7086  ┆ 0.763      │
│ st         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.6959     ┆ 0.5996     ┆ 0.6441  ┆ 0.678      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴─────────┴────────────┘

In [15]:
summary_df = (
    pl_df
    .group_by(["histone_marker", "model"])
    .agg([
        pl.col("val_accuracy").mean().alias("val_accuracy_mean"),
        pl.col("val_accuracy").std().alias("val_accuracy_std"),
        pl.col("val_auc").mean().alias("val_auc_mean"),
        pl.col("val_auc").std().alias("val_auc_std"),
        pl.col("test_accuracy").mean().alias("test_accuracy_mean"),
        pl.col("test_accuracy").std().alias("test_accuracy_std"),
        pl.col("test_auc").mean().alias("test_auc_mean"),
        pl.col("test_auc").std().alias("test_auc_std"),
    ])
    .sort(["histone_marker", "test_accuracy_mean"], descending=[False, True])
    .with_columns(pl.col(pl.Float64).round(4))
)

In [18]:
summary_df

shape: (124, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ model     ┆ val_accur ┆ val_accur ┆ … ┆ test_accu ┆ test_accu ┆ test_auc_ ┆ test_auc │
│ arker     ┆ ---       ┆ acy_mean  ┆ acy_std   ┆   ┆ racy_mean ┆ racy_std  ┆ mean      ┆ _std     │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K27ac   ┆ RandomFor ┆ 70.16     ┆ 1.6134    ┆ … ┆ 70.9      ┆ 1.9545    ┆ 0.7828    ┆ 0.0197   │
│           ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ LogisticR ┆ 68.4      ┆ 1.8398    ┆ … ┆ 68.22     ┆ 1.63      ┆ 0.7266    ┆ 0.0215   │
│           ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ SVM_Linea ┆ 68.38     ┆ 1.8472    ┆ … ┆ 68.1      ┆ 2.1783    ┆ 0.7276    ┆ 0.0208   │
│           ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ DirectRan ┆ 67.76     ┆ 2.2546    ┆ … ┆ 67.6      ┆ 1.2629    ┆ 0.7612    ┆ 0.0215   │
│           ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac-H ┆ RandomFor ┆ 70.32     ┆ 2.4641    ┆ … ┆ 70.46     ┆ 2.3115    ┆ 0.7861    ┆ 0.0224   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K9me3-H ┆ SVM_Linea ┆ 66.12     ┆ 1.8647    ┆ … ┆ 66.3      ┆ 2.1691    ┆ 0.7075    ┆ 0.0206   │
│ 3K27ac-H3 ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27me3    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ RandomFor ┆ 65.04     ┆ 2.305     ┆ … ┆ 65.92     ┆ 2.2554    ┆ 0.7088    ┆ 0.0308   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ DirectRan ┆ 64.04     ┆ 1.4639    ┆ … ┆ 64.26     ┆ 2.3586    ┆ 0.7088    ┆ 0.0334   │
│ 3K27me3   ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ LogisticR ┆ 61.48     ┆ 1.1167    ┆ … ┆ 63.3      ┆ 2.1737    ┆ 0.6719    ┆ 0.0248   │
│ 3K27me3   ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ SVM_Linea ┆ 61.24     ┆ 1.2462    ┆ … ┆ 62.76     ┆ 1.9629    ┆ 0.6717    ┆ 0.0253   │
│ 3K27me3   ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [19]:
summary_df.write_csv(OUTPUT_PATH/ f"HepG2 GSE76344 Ranking.csv", include_header=True)