In [1]:
# Import required libraries
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, random_split

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import numpy as np

from datetime import datetime
import time

In [2]:
current_time = datetime.now().strftime("%Y%m%d%H%M%S")

progress_file = f'/group/pmc021/amunif/epi-thesis/workflow/04. Neural Network/gpu_test_{current_time}.txt'
dataset_path = "/group/pmc021/amunif/epi-thesis/dataset/"

In [3]:
# Prepare the progress file
current_time = datetime.now().strftime("%Y%m%d%H%M%S")
progress_file = f'progress_conv1d_{current_time}.txt'

In [4]:
'''
User defined functions
'''
def load_large_csv(file_name, chunksize=20000):
    # Read the CSV file
    mylist = []

    for chunk in pd.read_csv(file_name, chunksize = chunksize):
        mylist.append(chunk)

    df = pd.concat(mylist, axis = 0)
    
    del mylist
    return df

def save_progress(file_name, message):
    with open(file_name, 'a+') as file:
        file.write(message + "\n")

In [5]:
X = pd.read_csv(f"{dataset_path}histone_features.csv", nrows=100)
X.head()

,h3k4me3_0,h3k4me3_1,h3k4me3_2,h3k4me3_3,h3k4me3_4,h3k4me3_5,h3k4me3_6,h3k4me3_7,h3k4me3_8,h3k4me3_9,...,h3k27me3_3990,h3k27me3_3991,h3k27me3_3992,h3k27me3_3993,h3k27me3_3994,h3k27me3_3995,h3k27me3_3996,h3k27me3_3997,h3k27me3_3998,h3k27me3_3999
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
y = pd.read_csv(f"{dataset_path}value_1_df.csv", nrows=100)
y.head()

   h_value_1
0   0.000000
1   0.047392
2   0.000000
3   2.468570
4   2.468570

In [7]:
# Convert to numpy
X_np = X.to_numpy()
y_np = y.to_numpy()

In [8]:
# Split the data into training and testing
X_train_np, X_test_np, y_train_np, y_test_np = train_test_split(X_np, y_np, test_size=0.2, random_state=42)

In [9]:
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = torch.device('cpu')
print(f'Using device: {device}')
save_progress(progress_file, f'Using device: {device}')

Using device: cpu

In [10]:
# Convert NumPy arrays to PyTorch tensors
X_train_tensor = torch.tensor(X_train_np, dtype=torch.float32).unsqueeze(1).to(device)
y_train_tensor = torch.tensor(y_train_np, dtype=torch.float32).to(device)
X_test_tensor = torch.tensor(X_test_np, dtype=torch.float32).unsqueeze(1).to(device)
y_test_tensor = torch.tensor(y_test_np, dtype=torch.float32).to(device)

In [11]:
# Create TensorDataset for training and testing sets
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [12]:
# Create a DataLoader
train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False)

In [13]:
# Create CNN1D class
class HighDimCNN1D(nn.Module):
    def __init__(self, input_size):
        super(HighDimCNN1D, self).__init__()
        self.conv1 = nn.Conv1d(in_channels=1, out_channels=64, kernel_size=3, stride=1, padding=1)
        self.pool = nn.MaxPool1d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv1d(in_channels=64, out_channels=128, kernel_size=3, stride=1, padding=1)
        self.pool2 = nn.MaxPool1d(kernel_size=2, stride=2)
        self.conv3 = nn.Conv1d(in_channels=128, out_channels=256, kernel_size=3, stride=1, padding=1)
        self.pool3 = nn.MaxPool1d(kernel_size=2, stride=2)
        
        # Calculate the size after the convolution and pooling layers
        conv_output_size = input_size // 8  # Adjust this based on the number of pooling layers
        
        self.fc1 = nn.Linear(256 * conv_output_size, 512)
        self.fc2 = nn.Linear(512, 1)

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool2(torch.relu(self.conv2(x)))
        x = self.pool3(torch.relu(self.conv3(x)))
        x = x.view(x.size(0), -1)  # Flatten the tensor
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [14]:
'''
Training
'''
input_size = 20000  # Number of features in the input
model = HighDimCNN1D(input_size=input_size).to(device)

# Loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [15]:
# Training loop
num_epochs = 100
for epoch in range(num_epochs): 
    start_time = time.time()
    
    model.train()
    for inputs, targets in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()
    
    end_time = time.time()
    elapsed_time = end_time - start_time
    message = f'Epoch {epoch+1}, Time:{elapsed_time},  Loss: {loss.item()}'
    print(message)
    save_progress(progress_file, message)

Epoch 1, Time:9.900192737579346,  Loss: 72.07600402832031
Epoch 2, Time:9.016405582427979,  Loss: 94.02281188964844
Epoch 3, Time:8.963927507400513,  Loss: 114.66342163085938
Epoch 4, Time:9.036563873291016,  Loss: 36.40781021118164
Epoch 5, Time:9.209375858306885,  Loss: 142.20452880859375
Epoch 6, Time:9.886991739273071,  Loss: 154.9363555908203
Epoch 7, Time:9.759503602981567,  Loss: 99.1627426147461
Epoch 8, Time:9.310348749160767,  Loss: 4672.125
Epoch 9, Time:10.286764144897461,  Loss: 100.20706176757812
Epoch 10, Time:9.275325775146484,  Loss: 32.572593688964844
Epoch 11, Time:9.483944177627563,  Loss: 73.63834381103516
Epoch 12, Time:9.33066439628601,  Loss: 82.30669403076172
Epoch 13, Time:9.116858720779419,  Loss: 101.18565368652344
Epoch 14, Time:9.423644304275513,  Loss: 60.01161575317383
Epoch 15, Time:8.730194807052612,  Loss: 20.763944625854492
Epoch 16, Time:8.358730792999268,  Loss: 16.92530632019043
Epoch 17, Time:8.262501001358032,  Loss: 4.232501029968262
Epoch 18, Time:8.370853185653687,  Loss: 21.17991828918457
Epoch 19, Time:8.232194423675537,  Loss: 19.77309226989746
Epoch 20, Time:8.225922584533691,  Loss: 11.751764297485352
Epoch 21, Time:8.205410480499268,  Loss: 5.031988143920898
Epoch 22, Time:8.027198076248169,  Loss: 10.070560455322266
Epoch 23, Time:8.21588945388794,  Loss: 4.280816078186035
Epoch 24, Time:8.158708572387695,  Loss: 0.8738868832588196
Epoch 25, Time:8.341963291168213,  Loss: 2.5751070976257324
Epoch 26, Time:8.292163372039795,  Loss: 0.7314161062240601
Epoch 27, Time:7.970699787139893,  Loss: 0.5697904825210571
Epoch 28, Time:8.262456893920898,  Loss: 0.2078481763601303
Epoch 29, Time:8.155769348144531,  Loss: 21.30874252319336
Epoch 30, Time:8.269408941268921,  Loss: 0.9477350115776062
Epoch 31, Time:8.717069149017334,  Loss: 1.8446651697158813
Epoch 32, Time:9.255623579025269,  Loss: 0.6626619696617126
Epoch 33, Time:9.02965521812439,  Loss: 0.6331683397293091
Epoch 34, Time:8.959538221359253,  Loss: 3.8828349113464355
Epoch 35, Time:8.62882399559021,  Loss: 0.8295720219612122
Epoch 36, Time:8.63657021522522,  Loss: 0.8049923181533813
Epoch 37, Time:8.719121217727661,  Loss: 1.7694050073623657
Epoch 38, Time:8.42726469039917,  Loss: 1.9236124753952026
Epoch 39, Time:8.590591192245483,  Loss: 0.5088068246841431
Epoch 40, Time:8.311510562896729,  Loss: 1.3557230234146118
Epoch 41, Time:8.181985855102539,  Loss: 0.5634040236473083
Epoch 42, Time:8.193777799606323,  Loss: 0.7015861868858337
Epoch 43, Time:8.395320177078247,  Loss: 3.587292432785034
Epoch 44, Time:8.527407884597778,  Loss: 0.5370520353317261
Epoch 45, Time:8.673669338226318,  Loss: 0.6312238574028015
Epoch 46, Time:8.331135749816895,  Loss: 7.25091552734375
Epoch 47, Time:8.487953901290894,  Loss: 0.6127268075942993
Epoch 48, Time:8.250485181808472,  Loss: 1.570274829864502
Epoch 49, Time:9.024268388748169,  Loss: 0.7132985591888428
Epoch 50, Time:8.955546140670776,  Loss: 0.7932057976722717
Epoch 51, Time:8.717576742172241,  Loss: 0.9484617710113525
Epoch 52, Time:8.260866403579712,  Loss: 0.677333414554596
Epoch 53, Time:8.38330602645874,  Loss: 0.7553108930587769
Epoch 54, Time:8.193692445755005,  Loss: 0.44134169816970825
Epoch 55, Time:8.115321397781372,  Loss: 1.8821489810943604
Epoch 56, Time:7.800687074661255,  Loss: 1.206751823425293
Epoch 57, Time:8.190099477767944,  Loss: 23.010501861572266
Epoch 58, Time:8.55946135520935,  Loss: 1.309304118156433
Epoch 59, Time:8.049150228500366,  Loss: 1.2914561033248901
Epoch 60, Time:8.38814377784729,  Loss: 1.229271411895752
Epoch 61, Time:8.028138399124146,  Loss: 0.5904424786567688
Epoch 62, Time:7.8412110805511475,  Loss: 1.6004812717437744
Epoch 63, Time:8.05968713760376,  Loss: 0.7019006013870239
Epoch 64, Time:8.4739670753479,  Loss: 7.7920074462890625
Epoch 65, Time:8.194574356079102,  Loss: 0.7298556566238403
Epoch 66, Time:9.003582239151001,  Loss: 0.651918888092041
Epoch 67, Time:8.468306541442871,  Loss: 11.067276000976562
Epoch 68, Time:8.558572053909302,  Loss: 2.1201987266540527
Epoch 69, Time:8.390373706817627,  Loss: 0.9367478489875793
Epoch 70, Time:8.297735691070557,  Loss: 1.1021676063537598
Epoch 71, Time:8.308154106140137,  Loss: 7.562895774841309
Epoch 72, Time:8.513510465621948,  Loss: 1.6625436544418335
Epoch 73, Time:8.51551604270935,  Loss: 3.5817227363586426
Epoch 74, Time:8.781903505325317,  Loss: 42.49588394165039
Epoch 75, Time:8.853725671768188,  Loss: 10.564441680908203
Epoch 76, Time:8.859503746032715,  Loss: 25.146751403808594
Epoch 77, Time:8.90678358078003,  Loss: 10.229412078857422
Epoch 78, Time:8.901154518127441,  Loss: 6.39744758605957
Epoch 79, Time:9.046911716461182,  Loss: 21.059511184692383
Epoch 80, Time:9.222760677337646,  Loss: 0.6520318388938904
Epoch 81, Time:9.102729797363281,  Loss: 0.9323084950447083
Epoch 82, Time:8.940136909484863,  Loss: 0.9890631437301636
Epoch 83, Time:9.243186950683594,  Loss: 2.24455189704895
Epoch 84, Time:9.312454462051392,  Loss: 22.31165313720703
Epoch 85, Time:9.294222593307495,  Loss: 9.536772727966309
Epoch 86, Time:9.08153510093689,  Loss: 11.99486255645752
Epoch 87, Time:9.06629204750061,  Loss: 12.471538543701172
Epoch 88, Time:9.227280139923096,  Loss: 3.776439666748047
Epoch 89, Time:8.66191816329956,  Loss: 19.977956771850586
Epoch 90, Time:8.600544691085815,  Loss: 0.45533487200737
Epoch 91, Time:8.596723079681396,  Loss: 0.9273302555084229
Epoch 92, Time:8.66760516166687,  Loss: 0.5616499185562134
Epoch 93, Time:8.591245651245117,  Loss: 0.394530326128006
Epoch 94, Time:8.479240655899048,  Loss: 0.5970747470855713
Epoch 95, Time:8.501628398895264,  Loss: 0.22244803607463837
Epoch 96, Time:8.630393028259277,  Loss: 0.5382289886474609
Epoch 97, Time:8.604860305786133,  Loss: 0.12390308082103729
Epoch 98, Time:8.722576379776001,  Loss: 0.7372482419013977
Epoch 99, Time:8.57918906211853,  Loss: 2.1534781455993652
Epoch 100, Time:8.473712682723999,  Loss: 0.9812496900558472

In [16]:
'''
Evaluation
'''
# Evaluation
model.eval()
total_loss = 0.0
all_targets = []
all_predictions = []

# Evaluate the model
with torch.no_grad():
    for inputs, targets in test_loader:
        inputs, targets = inputs.to(device), targets.to(device)
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        total_loss += loss.item()

        all_targets.extend(targets.cpu().numpy())
        all_predictions.extend(outputs.cpu().numpy())

print(f'Average loss on the test data: {total_loss/len(test_loader):.4f}')
save_progress(progress_file, f'Average loss on the test data: {total_loss/len(test_loader):.4f}')

Average loss on the test data: 2.7366

In [17]:
all_targets = np.array(all_targets)
all_predictions = np.array(all_predictions)

mse = mean_squared_error(all_targets, all_predictions)
rmse = np.sqrt(mse)
mae = mean_absolute_error(all_targets, all_predictions)
r2 = r2_score(all_targets, all_predictions)

print(f'MSE: {mse}')
print(f'RMSE: {rmse}')
print(f'MAE: {mae}')
print(f'R2 Score: {r2}')

save_progress(progress_file, f'MSE: {mse}')
save_progress(progress_file, f'RMSE: {rmse}')
save_progress(progress_file, f'MAE: {mae}')
save_progress(progress_file, f'R2 Score: {r2}')

MSE: 3.0826332569122314
RMSE: 1.7557429075241089
MAE: 1.3563512563705444
R2 Score: 0.9982960820198059

In [18]:
# Create a DataFrame with true values and predictions
results_df = pd.DataFrame({
    'y_test': all_targets.flatten(),
    'y_pred': all_predictions.flatten()
})

# Save the DataFrame to a CSV file
results_df.to_csv(f'predictions_conv1d_{current_time}.csv', index=False)

print(f"Predictions and true values saved to predictions_conv1d_{current_time}.csv.")

Predictions and true values saved to predictions_conv1d_20240704075429.csv.