In [1]:
import polars as pl
import os

from pathlib import Path

In [9]:
DONOR = 'donor_4'

In [10]:
WORKING_PATH = Path('/group/pmc021/amunif/epi-thesis/workflow/16_Pairwise Ranking Healthy Liver/')
DATASET_PATH = WORKING_PATH / 'dataset'/ DONOR
OUTPUT_PATH  = WORKING_PATH / 'output' / 'antisymmetric' / DONOR

In [11]:
### Merge the results into single CSV file

# Read all CSV into single dataframe
pl_df = pl.read_csv(OUTPUT_PATH / 'test' / "*.csv")

In [12]:
pl_df

shape: (155, 12)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬──────────┬───────────┐
│ seed ┆ histone_ma ┆ epochs_tra ┆ train_loss ┆ … ┆ val_auc_av ┆ test_accur ┆ test_auc ┆ antisymme │
│ ---  ┆ rker       ┆ ined       ┆ _avg       ┆   ┆ g          ┆ acy        ┆ ---      ┆ try       │
│ i64  ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64      ┆ ---       │
│      ┆ str        ┆ i64        ┆ f64        ┆   ┆ f64        ┆ f64        ┆          ┆ f64       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪══════════╪═══════════╡
│ 1011 ┆ H3K4me3    ┆ 39         ┆ 0.591      ┆ … ┆ 0.7103     ┆ 71.5       ┆ 0.7148   ┆ 0.888     │
│ 123  ┆ H3K4me3    ┆ 60         ┆ 0.5891     ┆ … ┆ 0.739      ┆ 71.6       ┆ 0.7169   ┆ 0.892     │
│ 42   ┆ H3K4me3    ┆ 44         ┆ 0.5919     ┆ … ┆ 0.733      ┆ 71.8       ┆ 0.7205   ┆ 0.883     │
│ 456  ┆ H3K4me3    ┆ 70         ┆ 0.5784     ┆ … ┆ 0.7397     ┆ 70.0       ┆ 0.7016   ┆ 0.876     │
│ 789  ┆ H3K4me3    ┆ 31         ┆ 0.5945     ┆ … ┆ 0.7087     ┆ 72.2       ┆ 0.7216   ┆ 0.865     │
│ …    ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …        ┆ …         │
│ 1011 ┆ H3K4me3-H3 ┆ 53         ┆ 0.5634     ┆ … ┆ 0.7172     ┆ 74.1       ┆ 0.7409   ┆ 0.935     │
│      ┆ K9ac-H3K9m ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│      ┆ e3-H3K27ac ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│      ┆ …          ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ 123  ┆ H3K4me3-H3 ┆ 61         ┆ 0.5615     ┆ … ┆ 0.7469     ┆ 74.3       ┆ 0.7436   ┆ 0.931     │
│      ┆ K9ac-H3K9m ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│      ┆ e3-H3K27ac ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│      ┆ …          ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ 42   ┆ H3K4me3-H3 ┆ 78         ┆ 0.5582     ┆ … ┆ 0.7541     ┆ 74.7       ┆ 0.7486   ┆ 0.941     │
│      ┆ K9ac-H3K9m ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│      ┆ e3-H3K27ac ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│      ┆ …          ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ 456  ┆ H3K4me3-H3 ┆ 100        ┆ 0.5415     ┆ … ┆ 0.7574     ┆ 72.9       ┆ 0.7298   ┆ 0.923     │
│      ┆ K9ac-H3K9m ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│      ┆ e3-H3K27ac ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│      ┆ …          ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│ 789  ┆ H3K4me3-H3 ┆ 80         ┆ 0.5552     ┆ … ┆ 0.725      ┆ 74.9       ┆ 0.7488   ┆ 0.927     │
│      ┆ K9ac-H3K9m ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│      ┆ e3-H3K27ac ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
│      ┆ …          ┆            ┆            ┆   ┆            ┆            ┆          ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴──────────┴───────────┘

In [13]:
summary_df = (
    pl_df
    .group_by("histone_marker")
    .agg([
        pl.col("val_accuracy_avg").mean().alias("val_accuracy_mean"),
        pl.col("val_accuracy_avg").std().alias("val_accuracy_std"),
        pl.col("test_accuracy").mean().alias("test_accuracy_mean"),
        pl.col("test_accuracy").std().alias("test_accuracy_std"),
    ])
    .sort("test_accuracy_mean", descending=True)
)

In [14]:
summary_df

shape: (31, 5)
┌───────────────────┬───────────────────┬──────────────────┬───────────────────┬───────────────────┐
│ histone_marker    ┆ val_accuracy_mean ┆ val_accuracy_std ┆ test_accuracy_mea ┆ test_accuracy_std │
│ ---               ┆ ---               ┆ ---              ┆ n                 ┆ ---               │
│ str               ┆ f64               ┆ f64              ┆ ---               ┆ f64               │
│                   ┆                   ┆                  ┆ f64               ┆                   │
╞═══════════════════╪═══════════════════╪══════════════════╪═══════════════════╪═══════════════════╡
│ H3K9ac-H3K9me3-H3 ┆ 73.49722          ┆ 1.586118         ┆ 74.42             ┆ 1.308434          │
│ K27ac-H3K27me…    ┆                   ┆                  ┆                   ┆                   │
│ H3K4me3-H3K9ac-H3 ┆ 73.85736          ┆ 2.024634         ┆ 74.3              ┆ 0.685565          │
│ K27ac-H3K27me…    ┆                   ┆                  ┆                   ┆                   │
│ H3K4me3-H3K9ac-H3 ┆ 73.8716           ┆ 1.803229         ┆ 74.18             ┆ 0.782304          │
│ K9me3-H3K27ac…    ┆                   ┆                  ┆                   ┆                   │
│ H3K9ac-H3K27ac-H3 ┆ 73.6301           ┆ 1.410558         ┆ 74.06             ┆ 1.46731           │
│ K27me3            ┆                   ┆                  ┆                   ┆                   │
│ H3K4me3-H3K9me3-H ┆ 73.60184          ┆ 1.655615         ┆ 73.98             ┆ 0.729383          │
│ 3K27ac            ┆                   ┆                  ┆                   ┆                   │
│ …                 ┆ …                 ┆ …                ┆ …                 ┆ …                 │
│ H3K4me3           ┆ 72.38308          ┆ 1.533923         ┆ 71.42             ┆ 0.837854          │
│ H3K9ac-H3K9me3    ┆ 71.88428          ┆ 1.754233         ┆ 71.38             ┆ 1.84716           │
│ H3K9me3-H3K27me3  ┆ 50.8642           ┆ 1.26342          ┆ 52.6              ┆ 0.894427          │
│ H3K9me3           ┆ 49.0978           ┆ 0.991719         ┆ 51.42             ┆ 0.683374          │
│ H3K27me3          ┆ 49.224            ┆ 1.422513         ┆ 50.38             ┆ 1.001             │
└───────────────────┴───────────────────┴──────────────────┴───────────────────┴───────────────────┘

In [15]:
summary_df.write_csv(OUTPUT_PATH/ f"{DONOR}.csv", include_header=True)