In [10]:
import polars as pl
import os

from pathlib import Path

In [11]:
DONOR = 'donor_4'
NUM_ITEMS = 10000

In [12]:
WORKING_PATH = Path('/group/pmc021/amunif/epi-thesis/workflow/16_Pairwise Ranking Healthy Liver/')
DATASET_PATH = WORKING_PATH / 'dataset'/ DONOR
OUTPUT_PATH  = WORKING_PATH / 'output' / str(NUM_ITEMS) / DONOR

In [13]:
### Merge the results into single CSV file

# Read all CSV into single dataframe
pl_df = pl.read_csv(OUTPUT_PATH / 'test' / "*.csv")

In [14]:
pl_df

shape: (155, 11)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬──────────┐
│ seed ┆ histone_ma ┆ epochs_tra ┆ train_loss ┆ … ┆ val_accura ┆ val_auc_av ┆ test_accu ┆ test_auc │
│ ---  ┆ rker       ┆ ined       ┆ _avg       ┆   ┆ cy_avg     ┆ g          ┆ racy      ┆ ---      │
│ i64  ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ f64      │
│      ┆ str        ┆ i64        ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64       ┆          │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪══════════╡
│ 1011 ┆ H3K4me3    ┆ 62         ┆ 0.5802     ┆ … ┆ 71.2065    ┆ 0.7139     ┆ 71.6      ┆ 0.7158   │
│ 123  ┆ H3K4me3    ┆ 39         ┆ 0.5896     ┆ … ┆ 73.7974    ┆ 0.739      ┆ 71.6      ┆ 0.7169   │
│ 42   ┆ H3K4me3    ┆ 78         ┆ 0.5824     ┆ … ┆ 73.1551    ┆ 0.7356     ┆ 71.8      ┆ 0.7205   │
│ 456  ┆ H3K4me3    ┆ 100        ┆ 0.5694     ┆ … ┆ 73.724     ┆ 0.7402     ┆ 70.7      ┆ 0.7087   │
│ 789  ┆ H3K4me3    ┆ 41         ┆ 0.5862     ┆ … ┆ 70.4073    ┆ 0.7061     ┆ 72.4      ┆ 0.7236   │
│ …    ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …        │
│ 1011 ┆ H3K4me3-H3 ┆ 54         ┆ 0.5571     ┆ … ┆ 71.1722    ┆ 0.7102     ┆ 73.6      ┆ 0.7359   │
│      ┆ K9ac-H3K9m ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│      ┆ e3-H3K27ac ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│      ┆ …          ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│ 123  ┆ H3K4me3-H3 ┆ 43         ┆ 0.5544     ┆ … ┆ 75.4395    ┆ 0.7521     ┆ 74.1      ┆ 0.7415   │
│      ┆ K9ac-H3K9m ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│      ┆ e3-H3K27ac ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│      ┆ …          ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│ 42   ┆ H3K4me3-H3 ┆ 95         ┆ 0.5457     ┆ … ┆ 76.2684    ┆ 0.7648     ┆ 73.8      ┆ 0.7392   │
│      ┆ K9ac-H3K9m ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│      ┆ e3-H3K27ac ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│      ┆ …          ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│ 456  ┆ H3K4me3-H3 ┆ 100        ┆ 0.5388     ┆ … ┆ 75.024     ┆ 0.7527     ┆ 73.4      ┆ 0.735    │
│      ┆ K9ac-H3K9m ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│      ┆ e3-H3K27ac ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│      ┆ …          ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│ 789  ┆ H3K4me3-H3 ┆ 56         ┆ 0.5526     ┆ … ┆ 72.5161    ┆ 0.7257     ┆ 75.0      ┆ 0.7499   │
│      ┆ K9ac-H3K9m ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│      ┆ e3-H3K27ac ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
│      ┆ …          ┆            ┆            ┆   ┆            ┆            ┆           ┆          │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴──────────┘

In [15]:
summary_df = (
    pl_df
    .group_by("histone_marker")
    .agg([
        pl.col("val_accuracy_avg").mean().alias("val_accuracy_mean"),
        pl.col("val_accuracy_avg").std().alias("val_accuracy_std"),
        pl.col("test_accuracy").mean().alias("test_accuracy_mean"),
        pl.col("test_accuracy").std().alias("test_accuracy_std"),
    ])
    .sort("test_accuracy_mean", descending=True)
)

In [16]:
summary_df

shape: (31, 5)
┌───────────────────┬───────────────────┬──────────────────┬───────────────────┬───────────────────┐
│ histone_marker    ┆ val_accuracy_mean ┆ val_accuracy_std ┆ test_accuracy_mea ┆ test_accuracy_std │
│ ---               ┆ ---               ┆ ---              ┆ n                 ┆ ---               │
│ str               ┆ f64               ┆ f64              ┆ ---               ┆ f64               │
│                   ┆                   ┆                  ┆ f64               ┆                   │
╞═══════════════════╪═══════════════════╪══════════════════╪═══════════════════╪═══════════════════╡
│ H3K9ac-H3K9me3-H3 ┆ 73.6559           ┆ 1.38498          ┆ 74.08             ┆ 1.080278          │
│ K27ac-H3K27me…    ┆                   ┆                  ┆                   ┆                   │
│ H3K9ac-H3K27ac-H3 ┆ 73.52056          ┆ 1.326337         ┆ 74.02             ┆ 0.779102          │
│ K27me3            ┆                   ┆                  ┆                   ┆                   │
│ H3K4me3-H3K9ac-H3 ┆ 74.08404          ┆ 2.146478         ┆ 73.98             ┆ 0.626099          │
│ K9me3-H3K27ac…    ┆                   ┆                  ┆                   ┆                   │
│ H3K9ac-H3K9me3-H3 ┆ 73.55582          ┆ 1.293899         ┆ 73.96             ┆ 1.123833          │
│ K27ac             ┆                   ┆                  ┆                   ┆                   │
│ H3K4me3-H3K9me3-H ┆ 73.4632           ┆ 1.999445         ┆ 73.84             ┆ 0.541295          │
│ 3K27ac            ┆                   ┆                  ┆                   ┆                   │
│ …                 ┆ …                 ┆ …                ┆ …                 ┆ …                 │
│ H3K9ac            ┆ 71.9412           ┆ 1.431197         ┆ 71.46             ┆ 1.532319          │
│ H3K9ac-H3K9me3    ┆ 71.9329           ┆ 1.507742         ┆ 71.3              ┆ 1.6109            │
│ H3K9me3-H3K27me3  ┆ 50.7856           ┆ 1.280173         ┆ 52.7              ┆ 0.821584          │
│ H3K9me3           ┆ 49.2126           ┆ 0.879311         ┆ 51.36             ┆ 1.230041          │
│ H3K27me3          ┆ 49.2948           ┆ 1.381087         ┆ 50.38             ┆ 1.001             │
└───────────────────┴───────────────────┴──────────────────┴───────────────────┴───────────────────┘

In [17]:
summary_df.write_csv(OUTPUT_PATH/ f"{DONOR}.csv", include_header=True)