In [38]:
import polars as pl
import os

from pathlib import Path

In [39]:
DONOR = 'donor_4'

In [40]:
WORKING_PATH = Path('/group/pmc021/amunif/epi-thesis/workflow/16_Pairwise Ranking Healthy Liver/')
DATASET_PATH = WORKING_PATH / 'dataset'/ DONOR
OUTPUT_PATH  = WORKING_PATH / 'output' / 'combined' / DONOR

In [41]:
### Merge the results into single CSV file

# Read all CSV into single dataframe
pl_df = pl.read_csv(OUTPUT_PATH / 'test' / "*-test-metrics.csv")

In [42]:
pl_df

shape: (620, 12)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬─────────┬────────────┐
│ model      ┆ seed ┆ histone_ma ┆ epochs_tra ┆ … ┆ test_preci ┆ test_recal ┆ test_f1 ┆ antisymmet │
│ ---        ┆ ---  ┆ rker       ┆ ined       ┆   ┆ sion       ┆ l          ┆ ---     ┆ ry         │
│ str        ┆ i64  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64     ┆ ---        │
│            ┆      ┆ str        ┆ i64        ┆   ┆ f64        ┆ f64        ┆         ┆ f64        │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪═════════╪════════════╡
│ DirectRank ┆ 1011 ┆ H3K4me3    ┆ 39         ┆ … ┆ 0.6984     ┆ 0.761      ┆ 0.7283  ┆ 0.888      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7523     ┆ 0.6534     ┆ 0.6994  ┆ 0.762      │
│ gression   ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7528     ┆ 0.6614     ┆ 0.7041  ┆ 0.767      │
│ st         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7506     ┆ 0.6534     ┆ 0.6986  ┆ 0.76       │
│ DirectRank ┆ 123  ┆ H3K4me3    ┆ 60         ┆ … ┆ 0.6891     ┆ 0.7703     ┆ 0.7274  ┆ 0.892      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …       ┆ …          │
│ SVM_Linear ┆ 456  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7315     ┆ 0.6502     ┆ 0.6885  ┆ 0.741      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ DirectRank ┆ 789  ┆ H3K4me3-H3 ┆ 80         ┆ … ┆ 0.7386     ┆ 0.7753     ┆ 0.7565  ┆ 0.927      │
│ er         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7477     ┆ 0.6421     ┆ 0.6909  ┆ 0.735      │
│ gression   ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.8027     ┆ 0.7038     ┆ 0.75    ┆ 0.831      │
│ st         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7483     ┆ 0.6382     ┆ 0.6888  ┆ 0.732      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴─────────┴────────────┘

In [43]:
summary_df = (
    pl_df
    .group_by(["histone_marker", "model"])
    .agg([
        pl.col("val_accuracy").mean().alias("val_accuracy_mean"),
        pl.col("val_accuracy").std().alias("val_accuracy_std"),
        pl.col("val_auc").mean().alias("val_auc_mean"),
        pl.col("val_auc").std().alias("val_auc_std"),
        pl.col("test_accuracy").mean().alias("test_accuracy_mean"),
        pl.col("test_accuracy").std().alias("test_accuracy_std"),
        pl.col("test_auc").mean().alias("test_auc_mean"),
        pl.col("test_auc").std().alias("test_auc_std"),
    ])
    .sort(["histone_marker", "test_accuracy_mean"], descending=[False, True])
    .with_columns(pl.col(pl.Float64).round(4))
)

In [44]:
summary_df

shape: (124, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ model     ┆ val_accur ┆ val_accur ┆ … ┆ test_accu ┆ test_accu ┆ test_auc_ ┆ test_auc │
│ arker     ┆ ---       ┆ acy_mean  ┆ acy_std   ┆   ┆ racy_mean ┆ racy_std  ┆ mean      ┆ _std     │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K27ac   ┆ RandomFor ┆ 73.68     ┆ 2.7662    ┆ … ┆ 74.94     ┆ 1.3465    ┆ 0.8301    ┆ 0.0154   │
│           ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ SVM_Linea ┆ 72.24     ┆ 2.5822    ┆ … ┆ 73.22     ┆ 1.4025    ┆ 0.8022    ┆ 0.016    │
│           ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ LogisticR ┆ 72.48     ┆ 2.7698    ┆ … ┆ 73.2      ┆ 1.3096    ┆ 0.802     ┆ 0.0169   │
│           ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ DirectRan ┆ 72.36     ┆ 2.0182    ┆ … ┆ 72.88     ┆ 0.9884    ┆ 0.8198    ┆ 0.0112   │
│           ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac-H ┆ RandomFor ┆ 73.66     ┆ 2.7144    ┆ … ┆ 75.02     ┆ 1.6769    ┆ 0.8315    ┆ 0.0153   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K9me3-H ┆ SVM_Linea ┆ 70.72     ┆ 2.543     ┆ … ┆ 71.26     ┆ 0.9182    ┆ 0.7704    ┆ 0.0168   │
│ 3K27ac-H3 ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27me3    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ RandomFor ┆ 53.62     ┆ 1.3442    ┆ … ┆ 52.68     ┆ 1.1925    ┆ 0.546     ┆ 0.0074   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ DirectRan ┆ 51.12     ┆ 1.0941    ┆ … ┆ 52.6      ┆ 0.8944    ┆ 0.554     ┆ 0.0188   │
│ 3K27me3   ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ SVM_Linea ┆ 52.84     ┆ 1.3012    ┆ … ┆ 51.12     ┆ 0.8815    ┆ 0.5125    ┆ 0.0086   │
│ 3K27me3   ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ LogisticR ┆ 52.46     ┆ 1.3183    ┆ … ┆ 50.94     ┆ 0.8792    ┆ 0.5125    ┆ 0.0096   │
│ 3K27me3   ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [45]:
summary_df.write_csv(OUTPUT_PATH/ f"{DONOR}.csv", include_header=True)