In [37]:
import polars as pl
import os

from pathlib import Path

In [38]:
DONOR = 'donor_3'

In [39]:
WORKING_PATH = Path('/group/pmc021/amunif/epi-thesis/workflow/16_Pairwise Ranking Healthy Liver/')
DATASET_PATH = WORKING_PATH / 'dataset'/ DONOR
OUTPUT_PATH  = WORKING_PATH / 'output' / 'combined' / DONOR

# Merge the experiment results

In [40]:
# Read all CSV into single dataframe
pl_df = pl.read_csv(OUTPUT_PATH / 'test' / "*-test-metrics.csv")

In [41]:
pl_df

shape: (620, 13)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬─────────┬────────────┐
│ model      ┆ seed ┆ histone_ma ┆ epochs_tra ┆ … ┆ test_preci ┆ test_recal ┆ test_f1 ┆ antisymmet │
│ ---        ┆ ---  ┆ rker       ┆ ined       ┆   ┆ sion       ┆ l          ┆ ---     ┆ ry         │
│ str        ┆ i64  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64     ┆ ---        │
│            ┆      ┆ str        ┆ i64        ┆   ┆ f64        ┆ f64        ┆         ┆ f64        │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪═════════╪════════════╡
│ DirectRank ┆ 1011 ┆ H3K4me3    ┆ 84         ┆ … ┆ 0.7035     ┆ 0.761      ┆ 0.7311  ┆ 0.894      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.75       ┆ 0.6335     ┆ 0.6868  ┆ 0.793      │
│ gression   ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7716     ┆ 0.6594     ┆ 0.7111  ┆ 0.775      │
│ st         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7541     ┆ 0.6355     ┆ 0.6897  ┆ 0.794      │
│ DirectRank ┆ 123  ┆ H3K4me3    ┆ 60         ┆ … ┆ 0.6917     ┆ 0.7663     ┆ 0.7271  ┆ 0.899      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …       ┆ …          │
│ SVM_Linear ┆ 456  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7231     ┆ 0.6502     ┆ 0.6847  ┆ 0.757      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ DirectRank ┆ 789  ┆ H3K4me3-H3 ┆ 67         ┆ … ┆ 0.7371     ┆ 0.7694     ┆ 0.7529  ┆ 0.96       │
│ er         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7483     ┆ 0.6561     ┆ 0.6992  ┆ 0.761      │
│ gression   ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7924     ┆ 0.7058     ┆ 0.7466  ┆ 0.842      │
│ st         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7432     ┆ 0.6501     ┆ 0.6935  ┆ 0.724      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴─────────┴────────────┘

In [42]:
# Save the results by model 
MODEL_RESULT_FOLDER = OUTPUT_PATH / 'model_results'
os.makedirs(MODEL_RESULT_FOLDER, exist_ok=True)

for model_name in pl_df["model"].unique():
    pl_df.filter(pl_df["model"] == model_name).write_csv(MODEL_RESULT_FOLDER / f"{model_name}.csv", include_header=True)

In [43]:
# Save the results for all models and all seeds
pl_df.write_csv(OUTPUT_PATH / f"{DONOR}_all_results.csv", include_header=True)

In [52]:
summary_df = (
    pl_df
    .group_by(["histone_marker", "model"])
    .agg([
        pl.col("val_accuracy").mean().alias("val_accuracy_mean"),
        pl.col("val_accuracy").std().alias("val_accuracy_std"),
        pl.col("val_auc").mean().alias("val_auc_mean"),
        pl.col("val_auc").std().alias("val_auc_std"),
        pl.col("test_accuracy").mean().alias("test_accuracy_mean"),
        pl.col("test_accuracy").std().alias("test_accuracy_std"),
        pl.col("test_auc").mean().alias("test_auc_mean"),
        pl.col("test_auc").std().alias("test_auc_std"),
        pl.col("test_aucprc").mean().alias("test_aucprc_mean"),
        pl.col("test_aucprc").std().alias("test_aucprc_std"),
        pl.col("antisymmetry").mean().alias("antisymmetry_mean"),
        pl.col("antisymmetry").std().alias("antisymmetry_std")
    ])
    .sort(["histone_marker", "test_accuracy_mean"], descending=[False, True])
    .with_columns(pl.col(pl.Float64).round(4))
)

In [53]:
summary_df

shape: (124, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ model     ┆ val_accur ┆ val_accur ┆ … ┆ test_aucp ┆ test_aucp ┆ antisymme ┆ antisymm │
│ arker     ┆ ---       ┆ acy_mean  ┆ acy_std   ┆   ┆ rc_mean   ┆ rc_std    ┆ try_mean  ┆ etry_std │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K27ac   ┆ RandomFor ┆ 74.46     ┆ 2.5696    ┆ … ┆ 0.826     ┆ 0.0175    ┆ 0.7988    ┆ 0.01     │
│           ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ LogisticR ┆ 73.14     ┆ 2.4089    ┆ … ┆ 0.7926    ┆ 0.0157    ┆ 0.7904    ┆ 0.0205   │
│           ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ SVM_Linea ┆ 73.16     ┆ 2.1197    ┆ … ┆ 0.7932    ┆ 0.0153    ┆ 0.7872    ┆ 0.0191   │
│           ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ DirectRan ┆ 73.28     ┆ 1.7655    ┆ … ┆ 0.8137    ┆ 0.0163    ┆ 0.8944    ┆ 0.0054   │
│           ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac-H ┆ RandomFor ┆ 74.32     ┆ 2.9828    ┆ … ┆ 0.8279    ┆ 0.0193    ┆ 0.8188    ┆ 0.0083   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K9me3-H ┆ SVM_Linea ┆ 70.26     ┆ 2.6444    ┆ … ┆ 0.7439    ┆ 0.0223    ┆ 0.7806    ┆ 0.0191   │
│ 3K27ac-H3 ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27me3    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ DirectRan ┆ 56.76     ┆ 1.7672    ┆ … ┆ 0.5805    ┆ 0.0134    ┆ 0.2964    ┆ 0.0176   │
│ 3K27me3   ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ RandomFor ┆ 57.42     ┆ 2.4763    ┆ … ┆ 0.5722    ┆ 0.0117    ┆ 0.2668    ┆ 0.0223   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ LogisticR ┆ 54.54     ┆ 1.717     ┆ … ┆ 0.5322    ┆ 0.0151    ┆ 0.2036    ┆ 0.0148   │
│ 3K27me3   ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ SVM_Linea ┆ 53.82     ┆ 1.4721    ┆ … ┆ 0.5274    ┆ 0.01      ┆ 0.138     ┆ 0.0246   │
│ 3K27me3   ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [54]:
summary_df.write_csv(OUTPUT_PATH/ f"{DONOR}_result_summary.csv", include_header=True)

In [55]:
for model_name in summary_df["model"].unique():
    summary_df.filter(summary_df["model"] == model_name).write_csv(MODEL_RESULT_FOLDER / f"{model_name}_summary.csv", include_header=True)

# Merge the label distribution

In [56]:
# Read all label distribution CSV into single dataframe
label_df = pl.read_csv(OUTPUT_PATH / 'test' / "*-label-distribution.csv")

In [57]:
label_df

shape: (930, 7)
┌──────┬─────────────────────────────────┬───────┬───────┬───────┬───────┬────────────┐
│ seed ┆ histone_marker                  ┆ split ┆ label ┆ count ┆ total ┆ percentage │
│ ---  ┆ ---                             ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---        │
│ i64  ┆ str                             ┆ str   ┆ i64   ┆ i64   ┆ i64   ┆ f64        │
╞══════╪═════════════════════════════════╪═══════╪═══════╪═══════╪═══════╪════════════╡
│ 1011 ┆ H3K4me3                         ┆ Train ┆ 0     ┆ 4082  ┆ 8000  ┆ 51.02      │
│ 1011 ┆ H3K4me3                         ┆ Train ┆ 1     ┆ 3918  ┆ 8000  ┆ 48.98      │
│ 1011 ┆ H3K4me3                         ┆ Val   ┆ 0     ┆ 518   ┆ 1000  ┆ 51.8       │
│ 1011 ┆ H3K4me3                         ┆ Val   ┆ 1     ┆ 482   ┆ 1000  ┆ 48.2       │
│ 1011 ┆ H3K4me3                         ┆ Test  ┆ 0     ┆ 498   ┆ 1000  ┆ 49.8       │
│ …    ┆ …                               ┆ …     ┆ …     ┆ …     ┆ …     ┆ …          │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Train ┆ 1     ┆ 3923  ┆ 8000  ┆ 49.04      │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Val   ┆ 0     ┆ 529   ┆ 1000  ┆ 52.9       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Val   ┆ 1     ┆ 471   ┆ 1000  ┆ 47.1       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Test  ┆ 0     ┆ 497   ┆ 1000  ┆ 49.7       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Test  ┆ 1     ┆ 503   ┆ 1000  ┆ 50.3       │
└──────┴─────────────────────────────────┴───────┴───────┴───────┴───────┴────────────┘

In [58]:
# Make the summary by seed, split and label
label_summary_df = (
    label_df
    .group_by(['split', 'label'])
    .agg(pl.col('percentage').mean().round(2).alias('average_percentage_%'))
    .sort(['split', 'label'])
)

In [59]:
label_summary_df

shape: (6, 3)
┌───────┬───────┬──────────────────────┐
│ split ┆ label ┆ average_percentage_% │
│ ---   ┆ ---   ┆ ---                  │
│ str   ┆ i64   ┆ f64                  │
╞═══════╪═══════╪══════════════════════╡
│ Test  ┆ 0     ┆ 50.72                │
│ Test  ┆ 1     ┆ 49.28                │
│ Train ┆ 0     ┆ 50.99                │
│ Train ┆ 1     ┆ 49.01                │
│ Val   ┆ 0     ┆ 52.04                │
│ Val   ┆ 1     ┆ 47.96                │
└───────┴───────┴──────────────────────┘