In [1]:
import polars as pl
import os

from pathlib import Path

In [2]:
DONOR = 'donor_4'

In [3]:
WORKING_PATH = Path('/group/pmc021/amunif/epi-thesis/workflow/16_Pairwise Ranking Healthy Liver/')
DATASET_PATH = WORKING_PATH / 'dataset'/ DONOR
OUTPUT_PATH  = WORKING_PATH / 'output' / 'combined' / DONOR

# Merge the experiment results

In [4]:
# Read all CSV into single dataframe
pl_df = pl.read_csv(OUTPUT_PATH / 'test' / "*-test-metrics.csv")

In [5]:
pl_df

shape: (620, 13)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬─────────┬────────────┐
│ model      ┆ seed ┆ histone_ma ┆ epochs_tra ┆ … ┆ test_preci ┆ test_recal ┆ test_f1 ┆ antisymmet │
│ ---        ┆ ---  ┆ rker       ┆ ined       ┆   ┆ sion       ┆ l          ┆ ---     ┆ ry         │
│ str        ┆ i64  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64     ┆ ---        │
│            ┆      ┆ str        ┆ i64        ┆   ┆ f64        ┆ f64        ┆         ┆ f64        │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪═════════╪════════════╡
│ DirectRank ┆ 1011 ┆ H3K4me3    ┆ 39         ┆ … ┆ 0.6984     ┆ 0.761      ┆ 0.7283  ┆ 0.888      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7523     ┆ 0.6534     ┆ 0.6994  ┆ 0.762      │
│ gression   ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7528     ┆ 0.6614     ┆ 0.7041  ┆ 0.767      │
│ st         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7506     ┆ 0.6534     ┆ 0.6986  ┆ 0.76       │
│ DirectRank ┆ 123  ┆ H3K4me3    ┆ 60         ┆ … ┆ 0.6891     ┆ 0.7703     ┆ 0.7274  ┆ 0.892      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …       ┆ …          │
│ SVM_Linear ┆ 456  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7315     ┆ 0.6502     ┆ 0.6885  ┆ 0.741      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ DirectRank ┆ 789  ┆ H3K4me3-H3 ┆ 80         ┆ … ┆ 0.7386     ┆ 0.7753     ┆ 0.7565  ┆ 0.927      │
│ er         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7477     ┆ 0.6421     ┆ 0.6909  ┆ 0.735      │
│ gression   ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.8027     ┆ 0.7038     ┆ 0.75    ┆ 0.831      │
│ st         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7483     ┆ 0.6382     ┆ 0.6888  ┆ 0.732      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴─────────┴────────────┘

In [6]:
# Save the results by model 
MODEL_RESULT_FOLDER = OUTPUT_PATH / 'model_results'
os.makedirs(MODEL_RESULT_FOLDER, exist_ok=True)

for model_name in pl_df["model"].unique():
    pl_df.filter(pl_df["model"] == model_name).write_csv(MODEL_RESULT_FOLDER / f"{model_name}.csv", include_header=True)

In [7]:
# Save the results for all models and all seeds
pl_df.write_csv(OUTPUT_PATH / f"{DONOR}_all_results.csv", include_header=True)

In [8]:
summary_df = (
    pl_df
    .group_by(["histone_marker", "model"])
    .agg([
        pl.col("val_accuracy").mean().alias("val_accuracy_mean"),
        pl.col("val_accuracy").std().alias("val_accuracy_std"),
        pl.col("val_auc").mean().alias("val_auc_mean"),
        pl.col("val_auc").std().alias("val_auc_std"),
        pl.col("test_accuracy").mean().alias("test_accuracy_mean"),
        pl.col("test_accuracy").std().alias("test_accuracy_std"),
        pl.col("test_auc").mean().alias("test_auc_mean"),
        pl.col("test_auc").std().alias("test_auc_std"),
        pl.col("test_aucprc").mean().alias("test_aucprc_mean"),
        pl.col("test_aucprc").std().alias("test_aucprc_std"),
        pl.col("antisymmetry").mean().alias("antisymmetry_mean"),
        pl.col("antisymmetry").std().alias("antisymmetry_std")
    ])
    .sort(["histone_marker", "test_accuracy_mean"], descending=[False, True])
    .with_columns(pl.col(pl.Float64).round(4))
)

In [9]:
summary_df

shape: (124, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ model     ┆ val_accur ┆ val_accur ┆ … ┆ test_aucp ┆ test_aucp ┆ antisymme ┆ antisymm │
│ arker     ┆ ---       ┆ acy_mean  ┆ acy_std   ┆   ┆ rc_mean   ┆ rc_std    ┆ try_mean  ┆ etry_std │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K27ac   ┆ RandomFor ┆ 73.68     ┆ 2.7662    ┆ … ┆ 0.8192    ┆ 0.0152    ┆ 0.7786    ┆ 0.0142   │
│           ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ SVM_Linea ┆ 72.24     ┆ 2.5822    ┆ … ┆ 0.7813    ┆ 0.0173    ┆ 0.7648    ┆ 0.0118   │
│           ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ LogisticR ┆ 72.48     ┆ 2.7698    ┆ … ┆ 0.7808    ┆ 0.0193    ┆ 0.7624    ┆ 0.0119   │
│           ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ DirectRan ┆ 72.36     ┆ 2.0182    ┆ … ┆ 0.8039    ┆ 0.0109    ┆ 0.8636    ┆ 0.0043   │
│           ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac-H ┆ RandomFor ┆ 73.66     ┆ 2.7144    ┆ … ┆ 0.8205    ┆ 0.0145    ┆ 0.788     ┆ 0.0088   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K9me3-H ┆ SVM_Linea ┆ 70.72     ┆ 2.543     ┆ … ┆ 0.7396    ┆ 0.0184    ┆ 0.743     ┆ 0.0181   │
│ 3K27ac-H3 ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27me3    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ RandomFor ┆ 53.62     ┆ 1.3442    ┆ … ┆ 0.5275    ┆ 0.008     ┆ 0.1066    ┆ 0.0128   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ DirectRan ┆ 51.12     ┆ 1.0941    ┆ … ┆ 0.5283    ┆ 0.0099    ┆ 0.1348    ┆ 0.0088   │
│ 3K27me3   ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ SVM_Linea ┆ 52.84     ┆ 1.3012    ┆ … ┆ 0.5082    ┆ 0.016     ┆ 0.0642    ┆ 0.0056   │
│ 3K27me3   ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ LogisticR ┆ 52.46     ┆ 1.3183    ┆ … ┆ 0.508     ┆ 0.0119    ┆ 0.0764    ┆ 0.0118   │
│ 3K27me3   ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
summary_df.write_csv(OUTPUT_PATH/ f"{DONOR}_result_summary.csv", include_header=True)

In [11]:
for model_name in summary_df["model"].unique():
    summary_df.filter(summary_df["model"] == model_name).write_csv(MODEL_RESULT_FOLDER / f"{model_name}_summary.csv", include_header=True)

# Merge the label distribution

In [12]:
# Read all label distribution CSV into single dataframe
label_df = pl.read_csv(OUTPUT_PATH / 'test' / "*-label-distribution.csv")

In [13]:
label_df

shape: (930, 7)
┌──────┬─────────────────────────────────┬───────┬───────┬───────┬───────┬────────────┐
│ seed ┆ histone_marker                  ┆ split ┆ label ┆ count ┆ total ┆ percentage │
│ ---  ┆ ---                             ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---        │
│ i64  ┆ str                             ┆ str   ┆ i64   ┆ i64   ┆ i64   ┆ f64        │
╞══════╪═════════════════════════════════╪═══════╪═══════╪═══════╪═══════╪════════════╡
│ 1011 ┆ H3K4me3                         ┆ Train ┆ 0     ┆ 4082  ┆ 8000  ┆ 51.02      │
│ 1011 ┆ H3K4me3                         ┆ Train ┆ 1     ┆ 3918  ┆ 8000  ┆ 48.98      │
│ 1011 ┆ H3K4me3                         ┆ Val   ┆ 0     ┆ 518   ┆ 1000  ┆ 51.8       │
│ 1011 ┆ H3K4me3                         ┆ Val   ┆ 1     ┆ 482   ┆ 1000  ┆ 48.2       │
│ 1011 ┆ H3K4me3                         ┆ Test  ┆ 0     ┆ 498   ┆ 1000  ┆ 49.8       │
│ …    ┆ …                               ┆ …     ┆ …     ┆ …     ┆ …     ┆ …          │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Train ┆ 1     ┆ 3923  ┆ 8000  ┆ 49.04      │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Val   ┆ 0     ┆ 529   ┆ 1000  ┆ 52.9       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Val   ┆ 1     ┆ 471   ┆ 1000  ┆ 47.1       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Test  ┆ 0     ┆ 497   ┆ 1000  ┆ 49.7       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Test  ┆ 1     ┆ 503   ┆ 1000  ┆ 50.3       │
└──────┴─────────────────────────────────┴───────┴───────┴───────┴───────┴────────────┘

In [14]:
# Make the summary by seed, split and label
label_summary_df = (
    label_df
    .group_by(['split', 'label'])
    .agg(pl.col('percentage').mean().round(2).alias('average_percentage_%'))
    .sort(['split', 'label'])
)

In [15]:
label_summary_df

shape: (6, 3)
┌───────┬───────┬──────────────────────┐
│ split ┆ label ┆ average_percentage_% │
│ ---   ┆ ---   ┆ ---                  │
│ str   ┆ i64   ┆ f64                  │
╞═══════╪═══════╪══════════════════════╡
│ Test  ┆ 0     ┆ 50.72                │
│ Test  ┆ 1     ┆ 49.28                │
│ Train ┆ 0     ┆ 50.99                │
│ Train ┆ 1     ┆ 49.01                │
│ Val   ┆ 0     ┆ 52.04                │
│ Val   ┆ 1     ┆ 47.96                │
└───────┴───────┴──────────────────────┘