In [1]:
import polars as pl
import os

In [2]:
DATASET_PATH = '/group/pmc021/amunif/epi-thesis/workflow/15_HepG2 from ENCODE/dataset/'

In [3]:
# Open the features file
test_df = pl.read_parquet(os.path.join(DATASET_PATH, 'E118_exp_histones.parquet'))
test_df

shape: (19_645, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ gene_id    ┆ H3K9ac     ┆ H3K9ac_wc ┆ H3K9ac_le ┆ … ┆ H3K27me3  ┆ H3K27me3_ ┆ H3K27me3_ ┆ E118   │
│ ---        ┆ ---        ┆ ---       ┆ n         ┆   ┆ ---       ┆ wc        ┆ len       ┆ ---    │
│ str        ┆ list[f64]  ┆ u32       ┆ ---       ┆   ┆ list[f64] ┆ ---       ┆ ---       ┆ f64    │
│            ┆            ┆           ┆ u32       ┆   ┆           ┆ u32       ┆ u32       ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ ENSG000000 ┆ [0.0, 0.0, ┆ 15        ┆ 100       ┆ … ┆ [0.0,     ┆ 4         ┆ 100       ┆ 49.983 │
│ 00003      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.0    │
│ 00005      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 40        ┆ 100       ┆ … ┆ [0.0,     ┆ 25        ┆ 100       ┆ 62.811 │
│ 00419      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 27        ┆ 100       ┆ … ┆ [0.0,     ┆ 15        ┆ 100       ┆ 2.646  │
│ 00457      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 3         ┆ 100       ┆ 3.373  │
│ 00460      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 3.25704]  ┆           ┆           ┆        │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 1.842  │
│ 59658      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.0    │
│ 59664      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.0    │
│ 59680      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 49        ┆ 100       ┆ 0.0    │
│ 59717      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 3.68552]  ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.072  │
│ 59752      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [4]:
test_df.columns

['gene_id',
 'H3K9ac',
 'H3K9ac_wc',
 'H3K9ac_len',
 'H3K9me3',
 'H3K9me3_wc',
 'H3K9me3_len',
 'H3K4me3',
 'H3K4me3_wc',
 'H3K4me3_len',
 'H3K27ac',
 'H3K27ac_wc',
 'H3K27ac_len',
 'H3K27me3',
 'H3K27me3_wc',
 'H3K27me3_len',
 'E118']

In [6]:
# Select only the gene_id with histones count
gene_histone_count_df = test_df.select([
     'gene_id',
     'H3K9ac_wc',
     'H3K9me3_wc',
     'H3K4me3_wc',
     'H3K27ac_wc',
     'H3K27me3_wc',
     'E118'
])

In [7]:
gene_histone_count_df

shape: (19_645, 7)
┌─────────────────┬───────────┬────────────┬────────────┬────────────┬─────────────┬────────┐
│ gene_id         ┆ H3K9ac_wc ┆ H3K9me3_wc ┆ H3K4me3_wc ┆ H3K27ac_wc ┆ H3K27me3_wc ┆ E118   │
│ ---             ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ ---         ┆ ---    │
│ str             ┆ u32       ┆ u32        ┆ u32        ┆ u32        ┆ u32         ┆ f64    │
╞═════════════════╪═══════════╪════════════╪════════════╪════════════╪═════════════╪════════╡
│ ENSG00000000003 ┆ 15        ┆ 0          ┆ 9          ┆ 11         ┆ 4           ┆ 49.983 │
│ ENSG00000000005 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.0    │
│ ENSG00000000419 ┆ 40        ┆ 0          ┆ 35         ┆ 25         ┆ 25          ┆ 62.811 │
│ ENSG00000000457 ┆ 27        ┆ 0          ┆ 29         ┆ 20         ┆ 15          ┆ 2.646  │
│ ENSG00000000460 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 3           ┆ 3.373  │
│ …               ┆ …         ┆ …          ┆ …          ┆ …          ┆ …           ┆ …      │
│ ENSG00000259658 ┆ 0         ┆ 0          ┆ 3          ┆ 0          ┆ 0           ┆ 1.842  │
│ ENSG00000259664 ┆ 0         ┆ 93         ┆ 0          ┆ 0          ┆ 0           ┆ 0.0    │
│ ENSG00000259680 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.0    │
│ ENSG00000259717 ┆ 0         ┆ 0          ┆ 34         ┆ 0          ┆ 49          ┆ 0.0    │
│ ENSG00000259752 ┆ 0         ┆ 72         ┆ 0          ┆ 0          ┆ 0           ┆ 0.072  │
└─────────────────┴───────────┴────────────┴────────────┴────────────┴─────────────┴────────┘

In [8]:
gene_histone_count_df = gene_histone_count_df.sort(['E118'], descending=True)

In [9]:
gene_histone_count_df.head(20)

shape: (20, 7)
┌─────────────────┬───────────┬────────────┬────────────┬────────────┬─────────────┬─────────┐
│ gene_id         ┆ H3K9ac_wc ┆ H3K9me3_wc ┆ H3K4me3_wc ┆ H3K27ac_wc ┆ H3K27me3_wc ┆ E118    │
│ ---             ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ ---         ┆ ---     │
│ str             ┆ u32       ┆ u32        ┆ u32        ┆ u32        ┆ u32         ┆ f64     │
╞═════════════════╪═══════════╪════════════╪════════════╪════════════╪═════════════╪═════════╡
│ ENSG00000145192 ┆ 48        ┆ 0          ┆ 44         ┆ 69         ┆ 10          ┆ 16876.5 │
│ ENSG00000163631 ┆ 16        ┆ 0          ┆ 2          ┆ 44         ┆ 0           ┆ 10195.4 │
│ ENSG00000081051 ┆ 45        ┆ 0          ┆ 2          ┆ 75         ┆ 0           ┆ 6424.55 │
│ ENSG00000158874 ┆ 87        ┆ 0          ┆ 74         ┆ 94         ┆ 37          ┆ 6207.16 │
│ ENSG00000111640 ┆ 55        ┆ 0          ┆ 54         ┆ 61         ┆ 19          ┆ 4943.83 │
│ …               ┆ …         ┆ …          ┆ …          ┆ …          ┆ …           ┆ …       │
│ ENSG00000115414 ┆ 62        ┆ 0          ┆ 47         ┆ 58         ┆ 25          ┆ 1846.18 │
│ ENSG00000132386 ┆ 38        ┆ 0          ┆ 34         ┆ 38         ┆ 8           ┆ 1805.06 │
│ ENSG00000156508 ┆ 60        ┆ 0          ┆ 49         ┆ 58         ┆ 13          ┆ 1778.65 │
│ ENSG00000118137 ┆ 61        ┆ 0          ┆ 56         ┆ 73         ┆ 15          ┆ 1648.48 │
│ ENSG00000118705 ┆ 40        ┆ 0          ┆ 38         ┆ 36         ┆ 25          ┆ 1503.77 │
└─────────────────┴───────────┴────────────┴────────────┴────────────┴─────────────┴─────────┘

In [11]:
gene_histone_count_df.write_csv("E118 with histone count.csv")