In [1]:
# Import required libraries
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, random_split

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import numpy as np

from datetime import datetime
import time

In [2]:
# Prepare the progress file
current_time = datetime.now().strftime("%Y%m%d%H%M%S")
progress_file = f'progress_conv1d_{current_time}.txt'

In [3]:
'''
User defined functions
'''
def load_large_csv(file_name, chunksize=20000):
    # Read the CSV file
    mylist = []

    for chunk in pd.read_csv(file_name, chunksize = chunksize):
        mylist.append(chunk)

    df = pd.concat(mylist, axis = 0)
    
    del mylist
    return df

def save_progress(file_name, message):
    with open(file_name, 'a+') as file:
        file.write(message + "\n")

In [4]:
X = pd.read_csv('s3://epi-thesis/histone_features.csv', nrows=100)
X.head()

,h3k4me3_0,h3k4me3_1,h3k4me3_2,h3k4me3_3,h3k4me3_4,h3k4me3_5,h3k4me3_6,h3k4me3_7,h3k4me3_8,h3k4me3_9,...,h3k27me3_3990,h3k27me3_3991,h3k27me3_3992,h3k27me3_3993,h3k27me3_3994,h3k27me3_3995,h3k27me3_3996,h3k27me3_3997,h3k27me3_3998,h3k27me3_3999
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
y = pd.read_csv('s3://epi-thesis/value_1_df.csv', nrows=100)
y.head()

   h_value_1
0   0.000000
1   0.047392
2   0.000000
3   2.468570
4   2.468570

In [6]:
# Convert to numpy
X_np = X.to_numpy()
y_np = y.to_numpy()

In [7]:
# Split the data into training and testing
X_train_np, X_test_np, y_train_np, y_test_np = train_test_split(X_np, y_np, test_size=0.2, random_state=42)

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
save_progress(progress_file, f'Using device: {device}')

In [9]:
# Convert NumPy arrays to PyTorch tensors
X_train_tensor = torch.tensor(X_train_np, dtype=torch.float32).unsqueeze(1).to(device)
y_train_tensor = torch.tensor(y_train_np, dtype=torch.float32).to(device)
X_test_tensor = torch.tensor(X_test_np, dtype=torch.float32).unsqueeze(1).to(device)
y_test_tensor = torch.tensor(y_test_np, dtype=torch.float32).to(device)

In [10]:
# Create TensorDataset for training and testing sets
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [11]:
# Create a DataLoader
train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False)

In [12]:
# Create CNN1D class
class HighDimCNN1D(nn.Module):
    def __init__(self, input_size):
        super(HighDimCNN1D, self).__init__()
        self.conv1 = nn.Conv1d(in_channels=1, out_channels=64, kernel_size=3, stride=1, padding=1)
        self.pool = nn.MaxPool1d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv1d(in_channels=64, out_channels=128, kernel_size=3, stride=1, padding=1)
        self.pool2 = nn.MaxPool1d(kernel_size=2, stride=2)
        self.conv3 = nn.Conv1d(in_channels=128, out_channels=256, kernel_size=3, stride=1, padding=1)
        self.pool3 = nn.MaxPool1d(kernel_size=2, stride=2)
        
        # Calculate the size after the convolution and pooling layers
        conv_output_size = input_size // 8  # Adjust this based on the number of pooling layers
        
        self.fc1 = nn.Linear(256 * conv_output_size, 512)
        self.fc2 = nn.Linear(512, 1)

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool2(torch.relu(self.conv2(x)))
        x = self.pool3(torch.relu(self.conv3(x)))
        x = x.view(x.size(0), -1)  # Flatten the tensor
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [13]:
'''
Training
'''
input_size = 20000  # Number of features in the input
model = HighDimCNN1D(input_size=input_size).to(device)

# Loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [14]:
# Training loop
num_epochs = 100
for epoch in range(num_epochs): 
    start_time = time.time()
    
    model.train()
    for inputs, targets in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()
    
    end_time = time.time()
    elapsed_time = end_time - start_time
    message = f'Epoch {epoch+1}, Time:{elapsed_time},  Loss: {loss.item()}'
    print(message)
    save_progress(progress_file, message)

/opt/conda/envs/pytorch/lib/python3.11/site-packages/torch/nn/modules/conv.py:306: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at /opt/conda/conda-bld/pytorch_1714328519311/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv1d(input, weight, bias, self.stride,

Epoch 1, Time:0.7083926200866699,  Loss: 108.62213134765625
Epoch 2, Time:0.3100762367248535,  Loss: 4457.66796875
Epoch 3, Time:0.30606770515441895,  Loss: 4600.53466796875
Epoch 4, Time:0.30097532272338867,  Loss: 4548.1201171875
Epoch 5, Time:0.30351853370666504,  Loss: 561.881591796875
Epoch 6, Time:0.3106963634490967,  Loss: 46.494564056396484
Epoch 7, Time:0.31006622314453125,  Loss: 585.4478759765625
Epoch 8, Time:0.3087425231933594,  Loss: 82.2025146484375
Epoch 9, Time:0.30556750297546387,  Loss: 70.03921508789062
Epoch 10, Time:0.3020663261413574,  Loss: 486.9620666503906
Epoch 11, Time:0.30739831924438477,  Loss: 96.37344360351562
Epoch 12, Time:0.3074049949645996,  Loss: 3677.598388671875
Epoch 13, Time:0.30702829360961914,  Loss: 8.784457206726074
Epoch 14, Time:0.3094182014465332,  Loss: 138.96405029296875
Epoch 15, Time:0.3050374984741211,  Loss: 45.37614822387695
Epoch 16, Time:0.3067965507507324,  Loss: 168.62033081054688
Epoch 17, Time:0.3043954372406006,  Loss: 25.321218490600586
Epoch 18, Time:0.30886030197143555,  Loss: 82.18254852294922
Epoch 19, Time:0.30788660049438477,  Loss: 13.49931526184082
Epoch 20, Time:0.30742621421813965,  Loss: 11.323559761047363
Epoch 21, Time:0.30915331840515137,  Loss: 5.014182090759277
Epoch 22, Time:0.30472350120544434,  Loss: 1.2208547592163086
Epoch 23, Time:0.3021245002746582,  Loss: 18.67374038696289
Epoch 24, Time:0.305267333984375,  Loss: 18.331836700439453
Epoch 25, Time:0.3099994659423828,  Loss: 0.310231477022171
Epoch 26, Time:0.3112647533416748,  Loss: 0.7338743209838867
Epoch 27, Time:0.30985212326049805,  Loss: 1.1675883531570435
Epoch 28, Time:0.3053317070007324,  Loss: 0.8934199810028076
Epoch 29, Time:0.3013739585876465,  Loss: 0.04854563623666763
Epoch 30, Time:0.30575132369995117,  Loss: 0.17565733194351196
Epoch 31, Time:0.3102853298187256,  Loss: 0.37773239612579346
Epoch 32, Time:0.3103036880493164,  Loss: 0.521163821220398
Epoch 33, Time:0.3077704906463623,  Loss: 0.5876773595809937
Epoch 34, Time:0.3045074939727783,  Loss: 0.8850868940353394
Epoch 35, Time:0.30124521255493164,  Loss: 0.6344579458236694
Epoch 36, Time:0.3043360710144043,  Loss: 0.36951881647109985
Epoch 37, Time:0.3109278678894043,  Loss: 0.4679272770881653
Epoch 38, Time:0.31197309494018555,  Loss: 0.25969237089157104
Epoch 39, Time:0.3098258972167969,  Loss: 0.6900932192802429
Epoch 40, Time:0.3055751323699951,  Loss: 0.6427966952323914
Epoch 41, Time:0.3020484447479248,  Loss: 0.6233484745025635
Epoch 42, Time:0.30487918853759766,  Loss: 19.20079803466797
Epoch 43, Time:0.30987095832824707,  Loss: 0.5389243960380554
Epoch 44, Time:0.31092357635498047,  Loss: 0.28725871443748474
Epoch 45, Time:0.31061410903930664,  Loss: 0.02729630656540394
Epoch 46, Time:0.30447840690612793,  Loss: 0.6124424934387207
Epoch 47, Time:0.30452775955200195,  Loss: 19.551342010498047
Epoch 48, Time:0.30434465408325195,  Loss: 0.5149585008621216
Epoch 49, Time:0.31035923957824707,  Loss: 0.4477112293243408
Epoch 50, Time:0.30977654457092285,  Loss: 0.3268786370754242
Epoch 51, Time:0.3092920780181885,  Loss: 0.14958764612674713
Epoch 52, Time:0.3055448532104492,  Loss: 0.2309306561946869
Epoch 53, Time:0.30214810371398926,  Loss: 0.7275779247283936
Epoch 54, Time:0.304229736328125,  Loss: 0.5982375144958496
Epoch 55, Time:0.31070494651794434,  Loss: 0.7305908203125
Epoch 56, Time:0.3103771209716797,  Loss: 0.40329211950302124
Epoch 57, Time:0.3094661235809326,  Loss: 0.7596158981323242
Epoch 58, Time:0.3054945468902588,  Loss: 0.4565005898475647
Epoch 59, Time:0.3048977851867676,  Loss: 23.358882904052734
Epoch 60, Time:0.30611443519592285,  Loss: 2.897613048553467
Epoch 61, Time:0.3097708225250244,  Loss: 0.6369276642799377
Epoch 62, Time:0.3112809658050537,  Loss: 6.1068549156188965
Epoch 63, Time:0.30979490280151367,  Loss: 13.22256851196289
Epoch 64, Time:0.30571579933166504,  Loss: 0.5032775402069092
Epoch 65, Time:0.30274295806884766,  Loss: 5.700062274932861
Epoch 66, Time:0.30800437927246094,  Loss: 0.6267752051353455
Epoch 67, Time:0.3076438903808594,  Loss: 0.8362028002738953
Epoch 68, Time:0.3087930679321289,  Loss: 20.563047409057617
Epoch 69, Time:0.3057272434234619,  Loss: 2.1604208946228027
Epoch 70, Time:0.30280518531799316,  Loss: 8.7330904006958
Epoch 71, Time:0.305675745010376,  Loss: 73.12870788574219
Epoch 72, Time:0.3092222213745117,  Loss: 10.810840606689453
Epoch 73, Time:0.31093716621398926,  Loss: 3.7601585388183594
Epoch 74, Time:0.3108212947845459,  Loss: 11.994802474975586
Epoch 75, Time:0.3052356243133545,  Loss: 2.916746139526367
Epoch 76, Time:0.30141282081604004,  Loss: 2.2405357360839844
Epoch 77, Time:0.30786752700805664,  Loss: 1.2480874061584473
Epoch 78, Time:0.30731964111328125,  Loss: 1.5995979309082031
Epoch 79, Time:0.3055388927459717,  Loss: 0.2977992296218872
Epoch 80, Time:0.307941198348999,  Loss: 0.37864449620246887
Epoch 81, Time:0.3056802749633789,  Loss: 19.89349365234375
Epoch 82, Time:0.30537939071655273,  Loss: 1.1051509380340576
Epoch 83, Time:0.31033921241760254,  Loss: 0.7850644588470459
Epoch 84, Time:0.3109300136566162,  Loss: 19.132719039916992
Epoch 85, Time:0.311387300491333,  Loss: 0.49910351634025574
Epoch 86, Time:0.3049192428588867,  Loss: 0.504520058631897
Epoch 87, Time:0.3074371814727783,  Loss: 0.6316967606544495
Epoch 88, Time:0.3090033531188965,  Loss: 0.29997485876083374
Epoch 89, Time:0.3101472854614258,  Loss: 0.23030221462249756
Epoch 90, Time:0.31014394760131836,  Loss: 0.760010302066803
Epoch 91, Time:0.30595993995666504,  Loss: 0.4996069669723511
Epoch 92, Time:0.3032376766204834,  Loss: 0.5645781755447388
Epoch 93, Time:0.31078147888183594,  Loss: 0.969731330871582
Epoch 94, Time:0.3105740547180176,  Loss: 3.9314870834350586
Epoch 95, Time:0.3123183250427246,  Loss: 0.12444990873336792
Epoch 96, Time:0.3059196472167969,  Loss: 62.56352615356445
Epoch 97, Time:0.3047513961791992,  Loss: 18.237173080444336
Epoch 98, Time:0.3107569217681885,  Loss: 1.161638855934143
Epoch 99, Time:0.3115689754486084,  Loss: 2.6830852031707764
Epoch 100, Time:0.31043243408203125,  Loss: 422.86773681640625

In [15]:
'''
Evaluation
'''
# Evaluation
model.eval()
total_loss = 0.0
all_targets = []
all_predictions = []

# Evaluate the model
with torch.no_grad():
    for inputs, targets in test_loader:
        inputs, targets = inputs.to(device), targets.to(device)
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        total_loss += loss.item()

        all_targets.extend(targets.cpu().numpy())
        all_predictions.extend(outputs.cpu().numpy())

print(f'Average loss on the test data: {total_loss/len(test_loader):.4f}')
save_progress(progress_file, f'Average loss on the test data: {total_loss/len(test_loader):.4f}')

Average loss on the test data: 27.4543

In [16]:
all_targets = np.array(all_targets)
all_predictions = np.array(all_predictions)

mse = mean_squared_error(all_targets, all_predictions)
rmse = np.sqrt(mse)
mae = mean_absolute_error(all_targets, all_predictions)
r2 = r2_score(all_targets, all_predictions)

print(f'MSE: {mse}')
print(f'RMSE: {rmse}')
print(f'MAE: {mae}')
print(f'R2 Score: {r2}')

save_progress(progress_file, f'MSE: {mse}')
save_progress(progress_file, f'RMSE: {rmse}')
save_progress(progress_file, f'MAE: {mae}')
save_progress(progress_file, f'R2 Score: {r2}')

MSE: 32.603797912597656
RMSE: 5.709973335266113
MAE: 3.3572497367858887
R2 Score: 0.9819781184196472

In [17]:
# Create a DataFrame with true values and predictions
results_df = pd.DataFrame({
    'y_test': all_targets.flatten(),
    'y_pred': all_predictions.flatten()
})

# Save the DataFrame to a CSV file
results_df.to_csv(f'predictions_conv1d_{current_time}.csv', index=False)

print(f"Predictions and true values saved to predictions_conv1d_{current_time}.csv.")

Predictions and true values saved to predictions_conv1d_20240703152628.csv.