In [1]:
import pandas as pd
import polars as pl
import os

In [2]:
DATASET_PATH = '../dataset/E003/'

# Gene Expression Dataset

In [3]:
import csv

def get_delimiter(file_path: str) -> str:
    with open(file_path, 'r') as csvfile:
        delimiter = str(csv.Sniffer().sniff(csvfile.read()).delimiter)
        return delimiter

In [4]:
get_delimiter(os.path.join(DATASET_PATH, "57epigenomes.RPKM.pc"))

'\t'

In [5]:
gene_exp = pl.read_csv(os.path.join(DATASET_PATH, "57epigenomes.RPKM.pc"), separator='\t', truncate_ragged_lines=True)

In [7]:
gene_exp.head(20)

shape: (20, 58)
┌─────────────────┬────────┬─────────┬────────┬───┬────────┬────────┬────────┬────────┐
│ gene_id         ┆ E000   ┆ E003    ┆ E004   ┆ … ┆ E122   ┆ E123   ┆ E127   ┆ E128   │
│ ---             ┆ ---    ┆ ---     ┆ ---    ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str             ┆ f64    ┆ f64     ┆ f64    ┆   ┆ f64    ┆ f64    ┆ f64    ┆ f64    │
╞═════════════════╪════════╪═════════╪════════╪═══╪════════╪════════╪════════╪════════╡
│ ENSG00000000003 ┆ 23.265 ┆ 43.985  ┆ 37.413 ┆ … ┆ 43.723 ┆ 0.267  ┆ 13.758 ┆ 15.818 │
│ ENSG00000000005 ┆ 0.872  ┆ 1.642   ┆ 6.498  ┆ … ┆ 0.0    ┆ 0.006  ┆ 0.0    ┆ 0.0    │
│ ENSG00000000419 ┆ 55.208 ┆ 35.259  ┆ 58.308 ┆ … ┆ 16.652 ┆ 73.719 ┆ 56.578 ┆ 56.371 │
│ ENSG00000000457 ┆ 3.237  ┆ 2.596   ┆ 2.345  ┆ … ┆ 2.549  ┆ 7.651  ┆ 4.967  ┆ 3.714  │
│ ENSG00000000460 ┆ 7.299  ┆ 6.649   ┆ 7.838  ┆ … ┆ 4.099  ┆ 22.103 ┆ 3.29   ┆ 2.491  │
│ …               ┆ …      ┆ …       ┆ …      ┆ … ┆ …      ┆ …      ┆ …      ┆ …      │
│ ENSG00000001626 ┆ 0.114  ┆ 0.353   ┆ 0.048  ┆ … ┆ 0.006  ┆ 0.005  ┆ 0.002  ┆ 0.048  │
│ ENSG00000001629 ┆ 16.841 ┆ 16.865  ┆ 15.977 ┆ … ┆ 11.318 ┆ 16.891 ┆ 24.447 ┆ 29.856 │
│ ENSG00000001630 ┆ 49.646 ┆ 113.334 ┆ 83.412 ┆ … ┆ 10.767 ┆ 16.93  ┆ 27.739 ┆ 17.899 │
│ ENSG00000001631 ┆ 11.932 ┆ 8.01    ┆ 9.417  ┆ … ┆ 4.217  ┆ 24.917 ┆ 11.335 ┆ 10.947 │
│ ENSG00000002016 ┆ 5.118  ┆ 3.299   ┆ 2.176  ┆ … ┆ 4.202  ┆ 4.655  ┆ 3.176  ┆ 2.848  │
└─────────────────┴────────┴─────────┴────────┴───┴────────┴────────┴────────┴────────┘

In [8]:
gene_exp.shape

(19795, 58)

In [9]:
gene_exp.median()

shape: (1, 58)
┌─────────┬───────┬───────┬───────┬───┬───────┬───────┬───────┬───────┐
│ gene_id ┆ E000  ┆ E003  ┆ E004  ┆ … ┆ E122  ┆ E123  ┆ E127  ┆ E128  │
│ ---     ┆ ---   ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str     ┆ f64   ┆ f64   ┆ f64   ┆   ┆ f64   ┆ f64   ┆ f64   ┆ f64   │
╞═════════╪═══════╪═══════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ null    ┆ 4.682 ┆ 3.329 ┆ 2.653 ┆ … ┆ 2.198 ┆ 1.606 ┆ 2.476 ┆ 2.147 │
└─────────┴───────┴───────┴───────┴───┴───────┴───────┴───────┴───────┘

In [10]:
gene_exp_E003 = gene_exp.select(["gene_id", "E003"])
gene_exp_E003.head()

shape: (5, 2)
┌─────────────────┬────────┐
│ gene_id         ┆ E003   │
│ ---             ┆ ---    │
│ str             ┆ f64    │
╞═════════════════╪════════╡
│ ENSG00000000003 ┆ 43.985 │
│ ENSG00000000005 ┆ 1.642  │
│ ENSG00000000419 ┆ 35.259 │
│ ENSG00000000457 ┆ 2.596  │
│ ENSG00000000460 ┆ 6.649  │
└─────────────────┴────────┘

In [11]:
E003_median = gene_exp_E003["E003"].median()
print(E003_median)

3.329

In [12]:
gene_exp_E003 = gene_exp_E003.with_columns(pl.when(gene_exp_E003["E003"] >= E003_median).then(1).otherwise(-1).alias('label'))

In [13]:
gene_exp_E003.head()

shape: (5, 3)
┌─────────────────┬────────┬───────┐
│ gene_id         ┆ E003   ┆ label │
│ ---             ┆ ---    ┆ ---   │
│ str             ┆ f64    ┆ i32   │
╞═════════════════╪════════╪═══════╡
│ ENSG00000000003 ┆ 43.985 ┆ 1     │
│ ENSG00000000005 ┆ 1.642  ┆ -1    │
│ ENSG00000000419 ┆ 35.259 ┆ 1     │
│ ENSG00000000457 ┆ 2.596  ┆ -1    │
│ ENSG00000000460 ┆ 6.649  ┆ 1     │
└─────────────────┴────────┴───────┘

In [14]:
gene_exp_E003.describe()

shape: (9, 4)
┌────────────┬─────────────────┬───────────┬──────────┐
│ statistic  ┆ gene_id         ┆ E003      ┆ label    │
│ ---        ┆ ---             ┆ ---       ┆ ---      │
│ str        ┆ str             ┆ f64       ┆ f64      │
╞════════════╪═════════════════╪═══════════╪══════════╡
│ count      ┆ 19795           ┆ 19795.0   ┆ 19795.0  │
│ null_count ┆ 0               ┆ 0.0       ┆ 0.0      │
│ mean       ┆ null            ┆ 15.66969  ┆ 0.000051 │
│ std        ┆ null            ┆ 54.568895 ┆ 1.000025 │
│ min        ┆ ENSG00000000003 ┆ 0.0       ┆ -1.0     │
│ 25%        ┆ null            ┆ 0.118     ┆ -1.0     │
│ 50%        ┆ null            ┆ 3.329     ┆ 1.0      │
│ 75%        ┆ null            ┆ 13.405    ┆ 1.0      │
│ max        ┆ ENSG00000259766 ┆ 2211.915  ┆ 1.0      │
└────────────┴─────────────────┴───────────┴──────────┘

In [15]:
gene_exp_E003["label"].value_counts()

shape: (2, 2)
┌───────┬───────┐
│ label ┆ count │
│ ---   ┆ ---   │
│ i32   ┆ u32   │
╞═══════╪═══════╡
│ 1     ┆ 9898  │
│ -1    ┆ 9897  │
└───────┴───────┘

# Histone Modification Dataset

In [16]:
narrowPeak_schema = {
    "chrom": pl.String,
    "chromStart": pl.Int64,
    "chromEnd": pl.Int64,
    "name": pl.String,
    "score": pl.Float64,
    "strand": pl.String,
    "signalValue": pl.Float64,
    "pValue": pl.Float64,
    "qValue": pl.Float64,
    "peak": pl.Int64
}

## H3K4me3

In [17]:
h3k4me3_df = pl.read_csv(os.path.join(DATASET_PATH, "narrowPeak", "E003-H3K4me3.narrowPeak"), separator='\t', schema=narrowPeak_schema, truncate_ragged_lines=True)

In [18]:
h3k4me3_df.head()

shape: (5, 10)
┌───────┬────────────┬───────────┬────────┬───┬─────────────┬───────────┬───────────┬──────┐
│ chrom ┆ chromStart ┆ chromEnd  ┆ name   ┆ … ┆ signalValue ┆ pValue    ┆ qValue    ┆ peak │
│ ---   ┆ ---        ┆ ---       ┆ ---    ┆   ┆ ---         ┆ ---       ┆ ---       ┆ ---  │
│ str   ┆ i64        ┆ i64       ┆ str    ┆   ┆ f64         ┆ f64       ┆ f64       ┆ i64  │
╞═══════╪════════════╪═══════════╪════════╪═══╪═════════════╪═══════════╪═══════════╪══════╡
│ chr2  ┆ 85764275   ┆ 85768872  ┆ Rank_2 ┆ … ┆ 71.33364    ┆ 354.8743  ┆ 346.6142  ┆ 2158 │
│ chr1  ┆ 110879746  ┆ 110884121 ┆ Rank_3 ┆ … ┆ 80.68906    ┆ 348.62274 ┆ 340.97101 ┆ 2449 │
│ chr17 ┆ 74730355   ┆ 74735029  ┆ Rank_4 ┆ … ┆ 76.60615    ┆ 343.98416 ┆ 336.4848  ┆ 2717 │
│ chr1  ┆ 115298642  ┆ 115301088 ┆ Rank_5 ┆ … ┆ 73.01621    ┆ 341.453   ┆ 334.01932 ┆ 1736 │
│ chr2  ┆ 29116913   ┆ 29119784  ┆ Rank_6 ┆ … ┆ 79.89017    ┆ 338.72272 ┆ 331.44965 ┆ 802  │
└───────┴────────────┴───────────┴────────┴───┴─────────────┴───────────┴───────────┴──────┘

In [19]:
h3k4me3_df.describe()

shape: (9, 11)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ chrom ┆ chromStart ┆ chromEnd   ┆ … ┆ signalVal ┆ pValue    ┆ qValue    ┆ peak      │
│ ---        ┆ ---   ┆ ---        ┆ ---        ┆   ┆ ue        ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str   ┆ f64        ┆ f64        ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│            ┆       ┆            ┆            ┆   ┆ f64       ┆           ┆           ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 42193 ┆ 42193.0    ┆ 42193.0    ┆ … ┆ 42193.0   ┆ 42193.0   ┆ 42193.0   ┆ 42193.0   │
│ null_count ┆ 0     ┆ 0.0        ┆ 0.0        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ null  ┆ 7.4838e7   ┆ 7.4839e7   ┆ … ┆ 16.303091 ┆ 65.962912 ┆ 63.45066  ┆ 502.10781 │
│            ┆       ┆            ┆            ┆   ┆           ┆           ┆           ┆ 4         │
│ std        ┆ null  ┆ 5.5978e7   ┆ 5.5978e7   ┆ … ┆ 15.905437 ┆ 79.847141 ┆ 79.087123 ┆ 583.63922 │
│ min        ┆ chr1  ┆ 9943.0     ┆ 10186.0    ┆ … ┆ 1.37013   ┆ 2.00951   ┆ 0.17888   ┆ 0.0       │
│ 25%        ┆ null  ┆ 3.1043892e ┆ 3.1045851e ┆ … ┆ 3.84125   ┆ 5.73166   ┆ 3.75651   ┆ 104.0     │
│            ┆       ┆ 7          ┆ 7          ┆   ┆           ┆           ┆           ┆           │
│ 50%        ┆ null  ┆ 6.0955501e ┆ 6.0955731e ┆ … ┆ 8.01832   ┆ 19.259    ┆ 17.11383  ┆ 232.0     │
│            ┆       ┆ 7          ┆ 7          ┆   ┆           ┆           ┆           ┆           │
│ 75%        ┆ null  ┆ 1.1276405e ┆ 1.12764431 ┆ … ┆ 26.70851  ┆ 117.42789 ┆ 114.62317 ┆ 767.0     │
│            ┆       ┆ 8          ┆ e8         ┆   ┆           ┆           ┆           ┆           │
│ max        ┆ chrY  ┆ 2.49201882 ┆ 2.49202016 ┆ … ┆ 81.87129  ┆ 354.8743  ┆ 346.6142  ┆ 9715.0    │
│            ┆       ┆ e8         ┆ e8         ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘