# Getting the Chromosome Name from Ensemble Gene Name

## Get the Ensemble Gene Name

In [1]:
import pandas as pd
import polars as pl
import os

In [2]:
DATASET_PATH = '../dataset/E003/'

In [3]:
gene_exp = pl.read_csv(os.path.join(DATASET_PATH, "57epigenomes.RPKM.pc"), separator='\t', truncate_ragged_lines=True)

In [4]:
gene_exp.head()

shape: (5, 58)
┌─────────────────┬────────┬────────┬────────┬───┬────────┬────────┬────────┬────────┐
│ gene_id         ┆ E000   ┆ E003   ┆ E004   ┆ … ┆ E122   ┆ E123   ┆ E127   ┆ E128   │
│ ---             ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str             ┆ f64    ┆ f64    ┆ f64    ┆   ┆ f64    ┆ f64    ┆ f64    ┆ f64    │
╞═════════════════╪════════╪════════╪════════╪═══╪════════╪════════╪════════╪════════╡
│ ENSG00000000003 ┆ 23.265 ┆ 43.985 ┆ 37.413 ┆ … ┆ 43.723 ┆ 0.267  ┆ 13.758 ┆ 15.818 │
│ ENSG00000000005 ┆ 0.872  ┆ 1.642  ┆ 6.498  ┆ … ┆ 0.0    ┆ 0.006  ┆ 0.0    ┆ 0.0    │
│ ENSG00000000419 ┆ 55.208 ┆ 35.259 ┆ 58.308 ┆ … ┆ 16.652 ┆ 73.719 ┆ 56.578 ┆ 56.371 │
│ ENSG00000000457 ┆ 3.237  ┆ 2.596  ┆ 2.345  ┆ … ┆ 2.549  ┆ 7.651  ┆ 4.967  ┆ 3.714  │
│ ENSG00000000460 ┆ 7.299  ┆ 6.649  ┆ 7.838  ┆ … ┆ 4.099  ┆ 22.103 ┆ 3.29   ┆ 2.491  │
└─────────────────┴────────┴────────┴────────┴───┴────────┴────────┴────────┴────────┘

In [68]:
ensg_list = pl.Series(gene_exp.select(["gene_id"])).to_list()
print(len(ensg_list))

19795

## Download the Chromosome Name from BioMart

In [75]:
from biomart import BiomartServer
import pandas as pd

In [84]:
def get_ensemble_data(gene_ids, batch_size=100):
    # Connect to the GRCh37 server
    server = BiomartServer("http://grch37.ensembl.org/biomart")
    
    # Select the dataset
    dataset = server.datasets['hsapiens_gene_ensembl']
    
    all_results = []
    
    # Process genes in batches
    for i in range(0, len(gene_ids), batch_size):
        batch = gene_ids[i:i+batch_size]
        print(f"Processing at i = {i}")
        # Prepare and execute the query
        response = dataset.search({
            'attributes': [
                'ensembl_gene_id',
                'external_gene_name',
                'chromosome_name',
                'start_position',
                'end_position',
                'strand'
            ],
            'filters': {
                'ensembl_gene_id': batch
            }
        })

        response_list = list(response.iter_lines())
        print(f"Requested: {batch_size}, Response: {len(response_list)}")

        with open('biomart_response.txt', 'a') as f:
            for line in response_list:
                f.write(f"{line.decode()}\n")

In [85]:
get_ensemble_data(ensg_list)

Processing at i = 0
Requested: 100, Response: 100
Processing at i = 100
Requested: 100, Response: 100
Processing at i = 200
Requested: 100, Response: 100
Processing at i = 300
Requested: 100, Response: 100
Processing at i = 400
Requested: 100, Response: 100
Processing at i = 500
Requested: 100, Response: 100
Processing at i = 600
Requested: 100, Response: 100
Processing at i = 700
Requested: 100, Response: 100
Processing at i = 800
Requested: 100, Response: 100
Processing at i = 900
Requested: 100, Response: 100
Processing at i = 1000
Requested: 100, Response: 100
Processing at i = 1100
Requested: 100, Response: 100
Processing at i = 1200
Requested: 100, Response: 100
Processing at i = 1300
Requested: 100, Response: 100
Processing at i = 1400
Requested: 100, Response: 100
Processing at i = 1500
Requested: 100, Response: 100
Processing at i = 1600
Requested: 100, Response: 100
Processing at i = 1700
Requested: 100, Response: 100
Processing at i = 1800
Requested: 100, Response: 100
Processing at i = 1900
Requested: 100, Response: 100
Processing at i = 2000
Requested: 100, Response: 99
Processing at i = 2100
Requested: 100, Response: 100
Processing at i = 2200
Requested: 100, Response: 100
Processing at i = 2300
Requested: 100, Response: 100
Processing at i = 2400
Requested: 100, Response: 99
Processing at i = 2500
Requested: 100, Response: 100
Processing at i = 2600
Requested: 100, Response: 100
Processing at i = 2700
Requested: 100, Response: 100
Processing at i = 2800
Requested: 100, Response: 100
Processing at i = 2900
Requested: 100, Response: 100
Processing at i = 3000
Requested: 100, Response: 100
Processing at i = 3100
Requested: 100, Response: 100
Processing at i = 3200
Requested: 100, Response: 100
Processing at i = 3300
Requested: 100, Response: 100
Processing at i = 3400
Requested: 100, Response: 100
Processing at i = 3500
Requested: 100, Response: 100
Processing at i = 3600
Requested: 100, Response: 100
Processing at i = 3700
Requested: 100, Response: 100
Processing at i = 3800
Requested: 100, Response: 100
Processing at i = 3900
Requested: 100, Response: 100
Processing at i = 4000
Requested: 100, Response: 99
Processing at i = 4100
Requested: 100, Response: 100
Processing at i = 4200
Requested: 100, Response: 100
Processing at i = 4300
Requested: 100, Response: 100
Processing at i = 4400
Requested: 100, Response: 100
Processing at i = 4500
Requested: 100, Response: 100
Processing at i = 4600
Requested: 100, Response: 100
Processing at i = 4700
Requested: 100, Response: 100
Processing at i = 4800
Requested: 100, Response: 100
Processing at i = 4900
Requested: 100, Response: 99
Processing at i = 5000
Requested: 100, Response: 99
Processing at i = 5100
Requested: 100, Response: 100
Processing at i = 5200
Requested: 100, Response: 100
Processing at i = 5300
Requested: 100, Response: 100
Processing at i = 5400
Requested: 100, Response: 99
Processing at i = 5500
Requested: 100, Response: 100
Processing at i = 5600
Requested: 100, Response: 100
Processing at i = 5700
Requested: 100, Response: 100
Processing at i = 5800
Requested: 100, Response: 99
Processing at i = 5900
Requested: 100, Response: 100
Processing at i = 6000
Requested: 100, Response: 100
Processing at i = 6100
Requested: 100, Response: 100
Processing at i = 6200
Requested: 100, Response: 100
Processing at i = 6300
Requested: 100, Response: 100
Processing at i = 6400
Requested: 100, Response: 100
Processing at i = 6500
Requested: 100, Response: 100
Processing at i = 6600
Requested: 100, Response: 100
Processing at i = 6700
Requested: 100, Response: 100
Processing at i = 6800
Requested: 100, Response: 100
Processing at i = 6900
Requested: 100, Response: 100
Processing at i = 7000
Requested: 100, Response: 100
Processing at i = 7100
Requested: 100, Response: 100
Processing at i = 7200
Requested: 100, Response: 99
Processing at i = 7300
Requested: 100, Response: 100
Processing at i = 7400
Requested: 100, Response: 100
Processing at i = 7500
Requested: 100, Response: 100
Processing at i = 7600
Requested: 100, Response: 100
Processing at i = 7700
Requested: 100, Response: 99
Processing at i = 7800
Requested: 100, Response: 100
Processing at i = 7900
Requested: 100, Response: 98
Processing at i = 8000
Requested: 100, Response: 100
Processing at i = 8100
Requested: 100, Response: 100
Processing at i = 8200
Requested: 100, Response: 100
Processing at i = 8300
Requested: 100, Response: 100
Processing at i = 8400
Requested: 100, Response: 100
Processing at i = 8500
Requested: 100, Response: 100
Processing at i = 8600
Requested: 100, Response: 100
Processing at i = 8700
Requested: 100, Response: 100
Processing at i = 8800
Requested: 100, Response: 100
Processing at i = 8900
Requested: 100, Response: 100
Processing at i = 9000
Requested: 100, Response: 100
Processing at i = 9100
Requested: 100, Response: 99
Processing at i = 9200
Requested: 100, Response: 100
Processing at i = 9300
Requested: 100, Response: 100
Processing at i = 9400
Requested: 100, Response: 100
Processing at i = 9500
Requested: 100, Response: 100
Processing at i = 9600
Requested: 100, Response: 100
Processing at i = 9700
Requested: 100, Response: 100
Processing at i = 9800
Requested: 100, Response: 100
Processing at i = 9900
Requested: 100, Response: 100
Processing at i = 10000
Requested: 100, Response: 100
Processing at i = 10100
Requested: 100, Response: 100
Processing at i = 10200
Requested: 100, Response: 100
Processing at i = 10300
Requested: 100, Response: 100
Processing at i = 10400
Requested: 100, Response: 100
Processing at i = 10500
Requested: 100, Response: 100
Processing at i = 10600
Requested: 100, Response: 100
Processing at i = 10700
Requested: 100, Response: 100
Processing at i = 10800
Requested: 100, Response: 100
Processing at i = 10900
Requested: 100, Response: 100
Processing at i = 11000
Requested: 100, Response: 100
Processing at i = 11100
Requested: 100, Response: 100
Processing at i = 11200
Requested: 100, Response: 100
Processing at i = 11300
Requested: 100, Response: 100
Processing at i = 11400
Requested: 100, Response: 100
Processing at i = 11500
Requested: 100, Response: 100
Processing at i = 11600
Requested: 100, Response: 100
Processing at i = 11700
Requested: 100, Response: 100
Processing at i = 11800
Requested: 100, Response: 98
Processing at i = 11900
Requested: 100, Response: 100
Processing at i = 12000
Requested: 100, Response: 99
Processing at i = 12100
Requested: 100, Response: 100
Processing at i = 12200
Requested: 100, Response: 99
Processing at i = 12300
Requested: 100, Response: 100
Processing at i = 12400
Requested: 100, Response: 100
Processing at i = 12500
Requested: 100, Response: 100
Processing at i = 12600
Requested: 100, Response: 100
Processing at i = 12700
Requested: 100, Response: 99
Processing at i = 12800
Requested: 100, Response: 100
Processing at i = 12900
Requested: 100, Response: 100
Processing at i = 13000
Requested: 100, Response: 99
Processing at i = 13100
Requested: 100, Response: 100
Processing at i = 13200
Requested: 100, Response: 100
Processing at i = 13300
Requested: 100, Response: 100
Processing at i = 13400
Requested: 100, Response: 100
Processing at i = 13500
Requested: 100, Response: 100
Processing at i = 13600
Requested: 100, Response: 100
Processing at i = 13700
Requested: 100, Response: 99
Processing at i = 13800
Requested: 100, Response: 100
Processing at i = 13900
Requested: 100, Response: 99
Processing at i = 14000
Requested: 100, Response: 100
Processing at i = 14100
Requested: 100, Response: 99
Processing at i = 14200
Requested: 100, Response: 98
Processing at i = 14300
Requested: 100, Response: 100
Processing at i = 14400
Requested: 100, Response: 100
Processing at i = 14500
Requested: 100, Response: 100
Processing at i = 14600
Requested: 100, Response: 98
Processing at i = 14700
Requested: 100, Response: 99
Processing at i = 14800
Requested: 100, Response: 100
Processing at i = 14900
Requested: 100, Response: 100
Processing at i = 15000
Requested: 100, Response: 100
Processing at i = 15100
Requested: 100, Response: 100
Processing at i = 15200
Requested: 100, Response: 100
Processing at i = 15300
Requested: 100, Response: 99
Processing at i = 15400
Requested: 100, Response: 100
Processing at i = 15500
Requested: 100, Response: 100
Processing at i = 15600
Requested: 100, Response: 100
Processing at i = 15700
Requested: 100, Response: 100
Processing at i = 15800
Requested: 100, Response: 100
Processing at i = 15900
Requested: 100, Response: 99
Processing at i = 16000
Requested: 100, Response: 99
Processing at i = 16100
Requested: 100, Response: 99
Processing at i = 16200
Requested: 100, Response: 98
Processing at i = 16300
Requested: 100, Response: 100
Processing at i = 16400
Requested: 100, Response: 99
Processing at i = 16500
Requested: 100, Response: 99
Processing at i = 16600
Requested: 100, Response: 99
Processing at i = 16700
Requested: 100, Response: 98
Processing at i = 16800
Requested: 100, Response: 99
Processing at i = 16900
Requested: 100, Response: 98
Processing at i = 17000
Requested: 100, Response: 99
Processing at i = 17100
Requested: 100, Response: 100
Processing at i = 17200
Requested: 100, Response: 100
Processing at i = 17300
Requested: 100, Response: 98
Processing at i = 17400
Requested: 100, Response: 99
Processing at i = 17500
Requested: 100, Response: 99
Processing at i = 17600
Requested: 100, Response: 96
Processing at i = 17700
Requested: 100, Response: 99
Processing at i = 17800
Requested: 100, Response: 94
Processing at i = 17900
Requested: 100, Response: 99
Processing at i = 18000
Requested: 100, Response: 98
Processing at i = 18100
Requested: 100, Response: 96
Processing at i = 18200
Requested: 100, Response: 94
Processing at i = 18300
Requested: 100, Response: 96
Processing at i = 18400
Requested: 100, Response: 97
Processing at i = 18500
Requested: 100, Response: 95
Processing at i = 18600
Requested: 100, Response: 93
Processing at i = 18700
Requested: 100, Response: 93
Processing at i = 18800
Requested: 100, Response: 92
Processing at i = 18900
Requested: 100, Response: 100
Processing at i = 19000
Requested: 100, Response: 99
Processing at i = 19100
Requested: 100, Response: 98
Processing at i = 19200
Requested: 100, Response: 100
Processing at i = 19300
Requested: 100, Response: 100
Processing at i = 19400
Requested: 100, Response: 99
Processing at i = 19500
Requested: 100, Response: 94
Processing at i = 19600
Requested: 100, Response: 93
Processing at i = 19700
Requested: 100, Response: 65

In [91]:
col_names = ['ensembl_gene_id',
                'external_gene_name',
                'chromosome_name',
                'start_position',
                'end_position',
                'strand']

biomart_df = pd.read_csv("biomart_response.txt", sep='\t', names = col_names)

In [92]:
biomart_df.head()

,ensembl_gene_id,external_gene_name,chromosome_name,start_position,end_position,strand
0,ENSG00000000003,TSPAN6,X,99883667,99894988,-1
1,ENSG00000000005,TNMD,X,99839799,99854882,1
2,ENSG00000000419,DPM1,20,49551404,49575092,-1
3,ENSG00000000457,SCYL3,1,169818772,169863408,-1
4,ENSG00000000460,C1orf112,1,169631245,169823221,1

In [94]:
biomart_df.shape

(19645, 6)

In [95]:
len(ensg_list)

19795

In [96]:
biomart_df.shape[0] - len(ensg_list)

-150

In [97]:
ensg_biomart = biomart_df['ensembl_gene_id'].to_list()

In [99]:
ensg_diff = list(set(ensg_list).difference(ensg_biomart))

In [101]:
len(ensg_diff)

150

In [103]:
ensg_diff

['ENSG00000197689',
 'ENSG00000099749',
 'ENSG00000185068',
 'ENSG00000229377',
 'ENSG00000196690',
 'ENSG00000232317',
 'ENSG00000258832',
 'ENSG00000230344',
 'ENSG00000215019',
 'ENSG00000206197',
 'ENSG00000226511',
 'ENSG00000235153',
 'ENSG00000259210',
 'ENSG00000225607',
 'ENSG00000255953',
 'ENSG00000212950',
 'ENSG00000257606',
 'ENSG00000112664',
 'ENSG00000141048',
 'ENSG00000215897',
 'ENSG00000205233',
 'ENSG00000258865',
 'ENSG00000204561',
 'ENSG00000259131',
 'ENSG00000177461',
 'ENSG00000170941',
 'ENSG00000259765',
 'ENSG00000259566',
 'ENSG00000205873',
 'ENSG00000167744',
 'ENSG00000181877',
 'ENSG00000215204',
 'ENSG00000233488',
 'ENSG00000205036',
 'ENSG00000259355',
 'ENSG00000259391',
 'ENSG00000218328',
 'ENSG00000204823',
 'ENSG00000235471',
 'ENSG00000196333',
 'ENSG00000258852',
 'ENSG00000233389',
 'ENSG00000259253',
 'ENSG00000259220',
 'ENSG00000198230',
 'ENSG00000259741',
 'ENSG00000215494',
 'ENSG00000214117',
 'ENSG00000258974',
 'ENSG00000206171',
 'ENSG00000214899',
 'ENSG00000228344',
 'ENSG00000124455',
 'ENSG00000172070',
 'ENSG00000197049',
 'ENSG00000229070',
 'ENSG00000257755',
 'ENSG00000237240',
 'ENSG00000227975',
 'ENSG00000259578',
 'ENSG00000136805',
 'ENSG00000198567',
 'ENSG00000205011',
 'ENSG00000229450',
 'ENSG00000232103',
 'ENSG00000234516',
 'ENSG00000127688',
 'ENSG00000215570',
 'ENSG00000255212',
 'ENSG00000259662',
 'ENSG00000101321',
 'ENSG00000258961',
 'ENSG00000259197',
 'ENSG00000223526',
 'ENSG00000259766',
 'ENSG00000259574',
 'ENSG00000206252',
 'ENSG00000259373',
 'ENSG00000121083',
 'ENSG00000255604',
 'ENSG00000256895',
 'ENSG00000214112',
 'ENSG00000224453',
 'ENSG00000204343',
 'ENSG00000182356',
 'ENSG00000167141',
 'ENSG00000259718',
 'ENSG00000259386',
 'ENSG00000236557',
 'ENSG00000258518',
 'ENSG00000235935',
 'ENSG00000188682',
 'ENSG00000259625',
 'ENSG00000236112',
 'ENSG00000167159',
 'ENSG00000258447',
 'ENSG00000175892',
 'ENSG00000259487',
 'ENSG00000243608',
 'ENSG00000197426',
 'ENSG00000215099',
 'ENSG00000140660',
 'ENSG00000223796',
 'ENSG00000233745',
 'ENSG00000139617',
 'ENSG00000259272',
 'ENSG00000215857',
 'ENSG00000256872',
 'ENSG00000259141',
 'ENSG00000259559',
 'ENSG00000120087',
 'ENSG00000255738',
 'ENSG00000217340',
 'ENSG00000214780',
 'ENSG00000198229',
 'ENSG00000259226',
 'ENSG00000188126',
 'ENSG00000230786',
 'ENSG00000203951',
 'ENSG00000259667',
 'ENSG00000248354',
 'ENSG00000150086',
 'ENSG00000247097',
 'ENSG00000259491',
 'ENSG00000226593',
 'ENSG00000214014',
 'ENSG00000259486',
 'ENSG00000213993',
 'ENSG00000203945',
 'ENSG00000228394',
 'ENSG00000178110',
 'ENSG00000197511',
 'ENSG00000187939',
 'ENSG00000168597',
 'ENSG00000179251',
 'ENSG00000232856',
 'ENSG00000189203',
 'ENSG00000189093',
 'ENSG00000181784',
 'ENSG00000236954',
 'ENSG00000214294',
 'ENSG00000259576',
 'ENSG00000178932',
 'ENSG00000228006',
 'ENSG00000205014',
 'ENSG00000232769',
 'ENSG00000205783',
 'ENSG00000258508',
 'ENSG00000257076',
 'ENSG00000205785']