In [10]:
import sys

In [11]:
import pandas as pd
import numpy as np
import os

In [12]:
import polars as pl

# Load the E066 Dataset

In [13]:
# Create a schema
column_names = ['chromosome_name',
                'start',
                'end',
                'gene_id',
                'E066',
                'strand',
                'label',
                'external_gene_name',
                'start_position',
                'end_position',
                'tss' 
                ]

In [14]:
DATASET_PATH = '../dataset/E066/'

In [15]:
E066_df = pd.read_csv(os.path.join(DATASET_PATH, "E066.bed"), sep="\t", names = column_names)

In [16]:
E066_df.head()

,chromosome_name,start,end,gene_id,E066,strand,label,external_gene_name,start_position,end_position,tss
0,chrX,99889988,99899988,ENSG00000000003,73.205,-1,1,TSPAN6,99883667,99894988,99894988
1,chrX,99834799,99844799,ENSG00000000005,0.191,1,0,TNMD,99839799,99854882,99839799
2,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,49575092
3,chr1,169858408,169868408,ENSG00000000457,4.733,-1,1,SCYL3,169818772,169863408,169863408
4,chr1,169626245,169636245,ENSG00000000460,0.942,1,0,C1orf112,169631245,169823221,169631245

# Reformatting the Histone

In [17]:
# Two additional histone markers: H3K9ac, H3K27ac
histone_list = ['H3K4me1', 'H3K4me3', 'H3K9me3', 'H3K27me3', 'H3K36me3', 'H3K9ac', 'H3K27ac']

In [18]:
intersect_cols = [  'chromosome_name',
                    'start',
                    'end',
                    'gene_id',
                    'E066',
                    'strand',
                    'label',
                    'external_gene_name',
                    'start_position',
                    'end_position',
                    'tss',
                    'chrom',
                    'chromStart',
                    'chromEnd',
                    'name',
                    'score',
                    'strand_peak',
                    'signalValue',
                    'pValue',
                    'qValue',
                    'peak'
                ]

In [19]:
for name in histone_list:
    print(f"Processing: {name}")
    histone_df = pd.read_csv(os.path.join(DATASET_PATH, "intersect", f"E066_{name}.bed"), sep='\t', names=intersect_cols)
    histone_df.loc[:, 'startBucket'] = (histone_df['chromStart'] - histone_df['start'])/100
    histone_df.loc[:, 'endBucket'] = (histone_df['chromEnd'] - histone_df['start'])/100
    histone_df.to_csv(os.path.join(DATASET_PATH, f"E066_{name}_df.csv"), header=True, index=False)
    print(f"CSV saved!")

Processing: H3K4me1
CSV saved!
Processing: H3K4me3
CSV saved!
Processing: H3K9me3
CSV saved!
Processing: H3K27me3
CSV saved!
Processing: H3K36me3
CSV saved!
Processing: H3K9ac
CSV saved!
Processing: H3K27ac
CSV saved!

# Reading Histone Files

In [20]:
H3K4me1_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K4me1_df.csv"))
H3K4me3_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K4me3_df.csv"))
H3K9me3_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K9me3_df.csv"))
H3K27me3_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K27me3_df.csv"))
H3K36me3_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K36me3_df.csv"))
H3K9ac_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K9ac_df.csv"))
H3K27ac_df = pd.read_csv(os.path.join(DATASET_PATH, "E066_H3K27ac_df.csv"))

In [21]:
print(H3K4me1_df.shape)
print(H3K4me3_df.shape)
print(H3K9me3_df.shape)
print(H3K27me3_df.shape)
print(H3K36me3_df.shape)
print(H3K9ac_df.shape)
print(H3K27ac_df.shape)

(62141, 23)
(34303, 23)
(9301, 23)
(15620, 23)
(25044, 23)
(40854, 23)
(31420, 23)

In [22]:
H3K4me1_df

,chromosome_name,start,end,gene_id,E066,strand,label,external_gene_name,start_position,end_position,...,chromEnd,name,score,strand_peak,signalValue,pValue,qValue,peak,startBucket,endBucket
0,chrX,99889988,99899988,ENSG00000000003,73.205,-1,1,TSPAN6,99883667,99894988,...,99891002,Rank_68310,106,.,5.92171,10.69175,8.59968,462,2.58,10.14
1,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49577113,Rank_14,734,.,20.49891,73.43851,67.02312,620,55.72,70.21
2,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49574573,Rank_188,564,.,18.24062,56.41204,51.06926,350,28.60,44.81
3,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49572915,Rank_71909,102,.,5.67759,10.27033,8.20970,169,19.06,28.23
4,chr20,49570092,49580092,ENSG00000000419,52.609,-1,1,DPM1,49551404,49575092,...,49577379,Rank_159548,51,.,3.58302,5.16452,3.52579,35,70.94,72.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62136,chr14,103584344,103594344,ENSG00000259717,0.000,-1,0,LINC00677,103587184,103589344,...,103585664,Rank_133666,61,.,4.02373,6.15866,4.43337,135,9.49,13.20
62137,chr14,103584344,103594344,ENSG00000259717,0.000,-1,0,LINC00677,103587184,103589344,...,103585231,Rank_139790,58,.,3.18223,5.88999,4.18566,143,1.78,8.87
62138,chr14,103584344,103594344,ENSG00000259717,0.000,-1,0,LINC00677,103587184,103589344,...,103592058,Rank_145378,55,.,3.67747,5.55802,3.87557,247,73.42,77.14
62139,chr14,103584344,103594344,ENSG00000259717,0.000,-1,0,LINC00677,103587184,103589344,...,103592353,Rank_206525,36,.,2.84015,3.69130,2.18960,80,78.35,80.09
62140,chr14,103584344,103594344,ENSG00000259717,0.000,-1,0,LINC00677,103587184,103589344,...,103589588,Rank_231378,24,.,1.89879,2.45456,1.10407,224,45.84,52.44