In [1]:
import os
import polars as pl

In [2]:
DATASET_PATH = '/group/pmc021/amunif/epi-thesis/workflow/11_HepG2_with_DeepChrome_preprocessing/dataset/'

In [3]:
# Define the schema
intersect_schema = pl.Schema({
    # The ensembl_top1.csv columns
    'chrom': pl.String,
    'tss_minus_5k': pl.Int64,
    'tss_plus_5k': pl.Int64, 
    'test_id': pl.String,
    'gene_id': pl.String,
    'chrom_name': pl.String,
    'gene_start': pl.Int64,
    'gene_end': pl.Int64,
    'strand': pl.Int64,
    'gene_name': pl.String,
    'gene_stable_id': pl.String,
    'gene_type': pl.String,
    'tss': pl.Int64,
    'locus': pl.String,
    'orig_start': pl.Int64, 
    'orig_end': pl.Int64,

    # gappedPeak columns
    "chrom_p": pl.String,
    "chromStart_p": pl.Int64, 
    "chromEnd_p": pl.Int64, 
    "name_p": pl.String, 
    "score_p": pl.Float64, 
    "strand_p": pl.String,
    "thickStart": pl.Int64,
    "thickEnd": pl.Int64,
    "itemRgb": pl.Int64,
    "blockCount": pl.Int64,
    "blockSizes": pl.String,
    "blockStarts": pl.String,
    "signalValue": pl.Float64,
    "pValue": pl.Float64,
    "qValue": pl.Float64
})

In [21]:
# Load the ensembl dataset using declared schema
df = pl.read_csv(
    os.path.join(DATASET_PATH, 'H3K27me3.bed'),
    separator="\t",
    has_header=False,
    schema = intersect_schema
)

In [22]:
df

shape: (21_058, 31)
┌───────┬─────────────┬─────────────┬────────────┬───┬────────────┬────────────┬─────────┬─────────┐
│ chrom ┆ tss_minus_5 ┆ tss_plus_5k ┆ test_id    ┆ … ┆ blockStart ┆ signalValu ┆ pValue  ┆ qValue  │
│ ---   ┆ k           ┆ ---         ┆ ---        ┆   ┆ s          ┆ e          ┆ ---     ┆ ---     │
│ str   ┆ ---         ┆ i64         ┆ str        ┆   ┆ ---        ┆ ---        ┆ f64     ┆ f64     │
│       ┆ i64         ┆             ┆            ┆   ┆ str        ┆ f64        ┆         ┆         │
╞═══════╪═════════════╪═════════════╪════════════╪═══╪════════════╪════════════╪═════════╪═════════╡
│ chr1  ┆ 855260      ┆ 865260      ┆ XLOC_00000 ┆ … ┆ 0,52,362,2 ┆ 5.37483    ┆ 10.9776 ┆ 8.06022 │
│       ┆             ┆             ┆ 6          ┆   ┆ 004,4635,6 ┆            ┆         ┆         │
│       ┆             ┆             ┆            ┆   ┆ 101,7888,8 ┆            ┆         ┆         │
│       ┆             ┆             ┆            ┆   ┆ …          ┆            ┆         ┆         │
│ chr1  ┆ 855260      ┆ 865260      ┆ XLOC_00000 ┆ … ┆ 0,52,362,2 ┆ 5.37483    ┆ 10.9776 ┆ 8.06022 │
│       ┆             ┆             ┆ 7          ┆   ┆ 004,4635,6 ┆            ┆         ┆         │
│       ┆             ┆             ┆            ┆   ┆ 101,7888,8 ┆            ┆         ┆         │
│       ┆             ┆             ┆            ┆   ┆ …          ┆            ┆         ┆         │
│ chr1  ┆ 950503      ┆ 960503      ┆ XLOC_00000 ┆ … ┆ 0,95,359   ┆ 3.42463    ┆ 4.66672 ┆ 2.5904  │
│       ┆             ┆             ┆ 9          ┆   ┆            ┆            ┆         ┆         │
│ chr1  ┆ 950503      ┆ 960503      ┆ XLOC_00000 ┆ … ┆ 0,284      ┆ 2.6364     ┆ 2.94694 ┆ 1.20742 │
│       ┆             ┆             ┆ 9          ┆   ┆            ┆            ┆         ┆         │
│ chr1  ┆ 1104264     ┆ 1114264     ┆ XLOC_00001 ┆ … ┆ 0,129,673  ┆ 3.07943    ┆ 4.33705 ┆ 2.33197 │
│       ┆             ┆             ┆ 4          ┆   ┆            ┆            ┆         ┆         │
│ …     ┆ …           ┆ …           ┆ …          ┆ … ┆ …          ┆ …          ┆ …       ┆ …       │
│ chrX  ┆ 109240859   ┆ 109250859   ┆ XLOC_02985 ┆ … ┆ 0,316      ┆ 3.10489    ┆ 3.73349 ┆ 1.80767 │
│       ┆             ┆             ┆ 4          ┆   ┆            ┆            ┆         ┆         │
│ chrX  ┆ 110182513   ┆ 110192513   ┆ XLOC_02985 ┆ … ┆ 0,171      ┆ 2.87367    ┆ 3.40889 ┆ 1.55169 │
│       ┆             ┆             ┆ 5          ┆   ┆            ┆            ┆         ┆         │
│ chrX  ┆ 110182513   ┆ 110192513   ┆ XLOC_02985 ┆ … ┆ 0,171      ┆ 2.87367    ┆ 3.40889 ┆ 1.55169 │
│       ┆             ┆             ┆ 6          ┆   ┆            ┆            ┆         ┆         │
│ chrX  ┆ 110182513   ┆ 110192513   ┆ XLOC_02985 ┆ … ┆ 0,171      ┆ 2.87367    ┆ 3.40889 ┆ 1.55169 │
│       ┆             ┆             ┆ 7          ┆   ┆            ┆            ┆         ┆         │
│ chrY  ┆ 6773727     ┆ 6783727     ┆ XLOC_02991 ┆ … ┆ 0,265,580  ┆ 3.2074     ┆ 3.95842 ┆ 1.99242 │
│       ┆             ┆             ┆ 7          ┆   ┆            ┆            ┆         ┆         │
└───────┴─────────────┴─────────────┴────────────┴───┴────────────┴────────────┴─────────┴─────────┘

In [23]:
df.filter(pl.col("gene_id") == 'XLOC_000006').with_columns((pl.col('chromEnd_p') - pl.col('chromStart_p')).alias('peak_length'))

shape: (1, 32)
┌───────┬─────────────┬─────────────┬────────────┬───┬────────────┬─────────┬─────────┬────────────┐
│ chrom ┆ tss_minus_5 ┆ tss_plus_5k ┆ test_id    ┆ … ┆ signalValu ┆ pValue  ┆ qValue  ┆ peak_lengt │
│ ---   ┆ k           ┆ ---         ┆ ---        ┆   ┆ e          ┆ ---     ┆ ---     ┆ h          │
│ str   ┆ ---         ┆ i64         ┆ str        ┆   ┆ ---        ┆ f64     ┆ f64     ┆ ---        │
│       ┆ i64         ┆             ┆            ┆   ┆ f64        ┆         ┆         ┆ i64        │
╞═══════╪═════════════╪═════════════╪════════════╪═══╪════════════╪═════════╪═════════╪════════════╡
│ chr1  ┆ 855260      ┆ 865260      ┆ XLOC_00000 ┆ … ┆ 5.37483    ┆ 10.9776 ┆ 8.06022 ┆ 20960      │
│       ┆             ┆             ┆ 6          ┆   ┆            ┆         ┆         ┆            │
└───────┴─────────────┴─────────────┴────────────┴───┴────────────┴─────────┴─────────┴────────────┘