In [1]:
import polars as pl
import os

In [4]:
DATASET_PATH = '/group/pmc021/amunif/epi-thesis/workflow/11_HepG2_with_DeepChrome_preprocessing/dataset/'

In [5]:
# Open the features file
test_df = pl.read_parquet(os.path.join(DATASET_PATH, 'HepG2_exp_histones.parquet'))
test_df

shape: (22_154, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gene_id   ┆ H3K9ac    ┆ H3K9ac_wc ┆ H3K9ac_le ┆ … ┆ H3K27me3_ ┆ H3K27me3_ ┆ value_1   ┆ value_2  │
│ ---       ┆ ---       ┆ ---       ┆ n         ┆   ┆ wc        ┆ len       ┆ ---       ┆ ---      │
│ str       ┆ list[f64] ┆ u32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ u32       ┆   ┆ u32       ┆ u32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 01        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 03        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 33        ┆ 100       ┆ … ┆ 100       ┆ 100       ┆ 0.0888452 ┆ 0.136965 │
│ 06        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 33        ┆ 100       ┆ … ┆ 100       ┆ 100       ┆ 4.04743   ┆ 4.16567  │
│ 07        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0000 ┆ [0.0,     ┆ 25        ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 26.7934   ┆ 30.2747  │
│ 08        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 09        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 12        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 14        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 17        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ XLOC_0300 ┆ [0.0,     ┆ 0         ┆ 100       ┆ … ┆ 0         ┆ 100       ┆ 0.0       ┆ 0.0      │
│ 18        ┆ 0.0, …    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.0]      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
test_df.columns

['gene_id',
 'H3K9ac',
 'H3K9ac_wc',
 'H3K9ac_len',
 'H3K9me3',
 'H3K9me3_wc',
 'H3K9me3_len',
 'H3K4me3',
 'H3K4me3_wc',
 'H3K4me3_len',
 'H3K27ac',
 'H3K27ac_wc',
 'H3K27ac_len',
 'H3K27me3',
 'H3K27me3_wc',
 'H3K27me3_len',
 'value_1',
 'value_2']

In [7]:
# Select only the gene_id with histones count
gene_histone_count_df = test_df.select([
     'gene_id',
     'H3K9ac_wc',
     'H3K9me3_wc',
     'H3K4me3_wc',
     'H3K27ac_wc',
     'H3K27me3_wc',
     'value_1',
     'value_2'
])

In [8]:
gene_histone_count_df

shape: (22_154, 8)
┌────────────┬───────────┬────────────┬────────────┬────────────┬───────────┬───────────┬──────────┐
│ gene_id    ┆ H3K9ac_wc ┆ H3K9me3_wc ┆ H3K4me3_wc ┆ H3K27ac_wc ┆ H3K27me3_ ┆ value_1   ┆ value_2  │
│ ---        ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ wc        ┆ ---       ┆ ---      │
│ str        ┆ u32       ┆ u32        ┆ u32        ┆ u32        ┆ ---       ┆ f64       ┆ f64      │
│            ┆           ┆            ┆            ┆            ┆ u32       ┆           ┆          │
╞════════════╪═══════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪══════════╡
│ XLOC_00000 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 1          ┆           ┆            ┆            ┆            ┆           ┆           ┆          │
│ XLOC_00000 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 3          ┆           ┆            ┆            ┆            ┆           ┆           ┆          │
│ XLOC_00000 ┆ 33        ┆ 46         ┆ 23         ┆ 4          ┆ 100       ┆ 0.0888452 ┆ 0.136965 │
│ 6          ┆           ┆            ┆            ┆            ┆           ┆           ┆          │
│ XLOC_00000 ┆ 33        ┆ 46         ┆ 23         ┆ 4          ┆ 100       ┆ 4.04743   ┆ 4.16567  │
│ 7          ┆           ┆            ┆            ┆            ┆           ┆           ┆          │
│ XLOC_00000 ┆ 25        ┆ 3          ┆ 18         ┆ 16         ┆ 0         ┆ 26.7934   ┆ 30.2747  │
│ 8          ┆           ┆            ┆            ┆            ┆           ┆           ┆          │
│ …          ┆ …         ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …        │
│ XLOC_03000 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 9          ┆           ┆            ┆            ┆            ┆           ┆           ┆          │
│ XLOC_03001 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 2          ┆           ┆            ┆            ┆            ┆           ┆           ┆          │
│ XLOC_03001 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 4          ┆           ┆            ┆            ┆            ┆           ┆           ┆          │
│ XLOC_03001 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 7          ┆           ┆            ┆            ┆            ┆           ┆           ┆          │
│ XLOC_03001 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0         ┆ 0.0       ┆ 0.0      │
│ 8          ┆           ┆            ┆            ┆            ┆           ┆           ┆          │
└────────────┴───────────┴────────────┴────────────┴────────────┴───────────┴───────────┴──────────┘

In [9]:
gene_histone_count_df.write_csv("HepG2 with histone count.csv")