In [1]:
import polars as pl
from pybiomart import Server
import os
import numpy as np
import pandas as pd

In [2]:
WORKING_DIR = '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2'
DATASET_DIR = '/group/pmc021/amunif/epi-thesis/dataset'

# Data Loading

## Loading the Dataset

In [3]:
# Open file
df = pl.read_csv(os.path.join(DATASET_DIR, 'GSM3718064_HepG2_exp.txt'), separator="\t")

## Split the locus column into chromosome, start, and end

In [4]:
# Split locus column into 3 columns: chr, start, end
df = df.with_columns([
    pl.col("locus").str.split(":").list.get(0).alias("chromosome"),
    pl.col("locus").str.split(":").list.get(1).str.split_exact("-", 1).struct.rename_fields(["start", "end"]).alias("position")
])

# Unnest the column and convert into integer
df = df.unnest("position")

df = df.with_columns([
    pl.col("start").cast(pl.Int64),
    pl.col("end").cast(pl.Int64)
])

df = df.with_columns([
    pl.col('chromosome').str.replace('chr', '').alias('chr')
])

In [5]:
df

shape: (30_032, 18)
┌─────────────┬─────────────┬────────────┬────────────┬───┬────────────┬──────────┬──────────┬─────┐
│ test_id     ┆ gene_id     ┆ gene       ┆ locus      ┆ … ┆ chromosome ┆ start    ┆ end      ┆ chr │
│ ---         ┆ ---         ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---      ┆ ---      ┆ --- │
│ str         ┆ str         ┆ str        ┆ str        ┆   ┆ str        ┆ i64      ┆ i64      ┆ str │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪════════════╪══════════╪══════════╪═════╡
│ XLOC_000001 ┆ XLOC_000001 ┆ OR4F5      ┆ chr1:69090 ┆ … ┆ chr1       ┆ 69090    ┆ 70008    ┆ 1   │
│             ┆             ┆            ┆ -70008     ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000002 ┆ XLOC_000002 ┆ LOC1001320 ┆ chr1:32389 ┆ … ┆ chr1       ┆ 323891   ┆ 328581   ┆ 1   │
│             ┆             ┆ 62,LOC1001 ┆ 1-328581   ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆ 33331      ┆            ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000003 ┆ XLOC_000003 ┆ OR4F29     ┆ chr1:36765 ┆ … ┆ chr1       ┆ 367658   ┆ 368597   ┆ 1   │
│             ┆             ┆            ┆ 8-368597   ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000004 ┆ XLOC_000004 ┆ LOC643837  ┆ chr1:76158 ┆ … ┆ chr1       ┆ 761585   ┆ 794889   ┆ 1   │
│             ┆             ┆            ┆ 5-794889   ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000005 ┆ XLOC_000005 ┆ -          ┆ chr1:84026 ┆ … ┆ chr1       ┆ 840263   ┆ 843900   ┆ 1   │
│             ┆             ┆            ┆ 3-843900   ┆   ┆            ┆          ┆          ┆     │
│ …           ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …        ┆ …        ┆ …   │
│ XLOC_030028 ┆ XLOC_030028 ┆ -          ┆ chrY:13319 ┆ … ┆ chrY       ┆ 13319431 ┆ 13324829 ┆ Y   │
│             ┆             ┆            ┆ 431-133248 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 29         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030029 ┆ XLOC_030029 ┆ -          ┆ chrY:13325 ┆ … ┆ chrY       ┆ 13325034 ┆ 13326120 ┆ Y   │
│             ┆             ┆            ┆ 034-133261 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 20         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030030 ┆ XLOC_030030 ┆ -          ┆ chrY:13331 ┆ … ┆ chrY       ┆ 13331089 ┆ 13332358 ┆ Y   │
│             ┆             ┆            ┆ 089-133323 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 58         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030031 ┆ XLOC_030031 ┆ -          ┆ chrY:15053 ┆ … ┆ chrY       ┆ 15053270 ┆ 15053343 ┆ Y   │
│             ┆             ┆            ┆ 270-150533 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 43         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030032 ┆ XLOC_030032 ┆ -          ┆ chrY:59001 ┆ … ┆ chrY       ┆ 59001259 ┆ 59003893 ┆ Y   │
│             ┆             ┆            ┆ 259-590038 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 93         ┆   ┆            ┆          ┆          ┆     │
└─────────────┴─────────────┴────────────┴────────────┴───┴────────────┴──────────┴──────────┴─────┘

In [9]:
df.group_by("chromosome").len().sort("len", descending=True)

shape: (46, 2)
┌───────────────────────┬──────┐
│ chromosome            ┆ len  │
│ ---                   ┆ ---  │
│ str                   ┆ u32  │
╞═══════════════════════╪══════╡
│ chr1                  ┆ 2867 │
│ chr2                  ┆ 1880 │
│ chr19                 ┆ 1711 │
│ chr11                 ┆ 1618 │
│ chr17                 ┆ 1581 │
│ …                     ┆ …    │
│ chr17_gl000205_random ┆ 1    │
│ chrUn_gl000219        ┆ 1    │
│ chrUn_gl000212        ┆ 1    │
│ chr1_gl000191_random  ┆ 1    │
│ chrUn_gl000211        ┆ 1    │
└───────────────────────┴──────┘

## Explode multiple gene names into rows

In [6]:
exploded_df = df.with_columns([
    pl.col("gene").str.split(",")
]).explode("gene")

exploded_df

shape: (31_121, 18)
┌─────────────┬─────────────┬────────────┬────────────┬───┬────────────┬──────────┬──────────┬─────┐
│ test_id     ┆ gene_id     ┆ gene       ┆ locus      ┆ … ┆ chromosome ┆ start    ┆ end      ┆ chr │
│ ---         ┆ ---         ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---      ┆ ---      ┆ --- │
│ str         ┆ str         ┆ str        ┆ str        ┆   ┆ str        ┆ i64      ┆ i64      ┆ str │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪════════════╪══════════╪══════════╪═════╡
│ XLOC_000001 ┆ XLOC_000001 ┆ OR4F5      ┆ chr1:69090 ┆ … ┆ chr1       ┆ 69090    ┆ 70008    ┆ 1   │
│             ┆             ┆            ┆ -70008     ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000002 ┆ XLOC_000002 ┆ LOC1001320 ┆ chr1:32389 ┆ … ┆ chr1       ┆ 323891   ┆ 328581   ┆ 1   │
│             ┆             ┆ 62         ┆ 1-328581   ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000002 ┆ XLOC_000002 ┆ LOC1001333 ┆ chr1:32389 ┆ … ┆ chr1       ┆ 323891   ┆ 328581   ┆ 1   │
│             ┆             ┆ 31         ┆ 1-328581   ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000003 ┆ XLOC_000003 ┆ OR4F29     ┆ chr1:36765 ┆ … ┆ chr1       ┆ 367658   ┆ 368597   ┆ 1   │
│             ┆             ┆            ┆ 8-368597   ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000004 ┆ XLOC_000004 ┆ LOC643837  ┆ chr1:76158 ┆ … ┆ chr1       ┆ 761585   ┆ 794889   ┆ 1   │
│             ┆             ┆            ┆ 5-794889   ┆   ┆            ┆          ┆          ┆     │
│ …           ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …        ┆ …        ┆ …   │
│ XLOC_030028 ┆ XLOC_030028 ┆ -          ┆ chrY:13319 ┆ … ┆ chrY       ┆ 13319431 ┆ 13324829 ┆ Y   │
│             ┆             ┆            ┆ 431-133248 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 29         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030029 ┆ XLOC_030029 ┆ -          ┆ chrY:13325 ┆ … ┆ chrY       ┆ 13325034 ┆ 13326120 ┆ Y   │
│             ┆             ┆            ┆ 034-133261 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 20         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030030 ┆ XLOC_030030 ┆ -          ┆ chrY:13331 ┆ … ┆ chrY       ┆ 13331089 ┆ 13332358 ┆ Y   │
│             ┆             ┆            ┆ 089-133323 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 58         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030031 ┆ XLOC_030031 ┆ -          ┆ chrY:15053 ┆ … ┆ chrY       ┆ 15053270 ┆ 15053343 ┆ Y   │
│             ┆             ┆            ┆ 270-150533 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 43         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030032 ┆ XLOC_030032 ┆ -          ┆ chrY:59001 ┆ … ┆ chrY       ┆ 59001259 ┆ 59003893 ┆ Y   │
│             ┆             ┆            ┆ 259-590038 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 93         ┆   ┆            ┆          ┆          ┆     │
└─────────────┴─────────────┴────────────┴────────────┴───┴────────────┴──────────┴──────────┴─────┘

## Saving the original data and exploded data

In [7]:
df.write_csv(os.path.join(WORKING_DIR, 'dataset', 'GSM3718064_HepG2_exp.csv'))
exploded_df.write_csv(os.path.join(WORKING_DIR, 'dataset', 'GSM3718064_HepG2_exp_exploded_gene_name.csv'))

# Data Exploration

## Check the status column

In [8]:
df.group_by(pl.col("status")).len()

shape: (4, 2)
┌────────┬───────┐
│ status ┆ len   │
│ ---    ┆ ---   │
│ str    ┆ u32   │
╞════════╪═══════╡
│ OK     ┆ 13934 │
│ HIDATA ┆ 1     │
│ NOTEST ┆ 16092 │
│ FAIL   ┆ 5     │
└────────┴───────┘

## Check Unique Values by start, end, chr, gene, value_1, and  value_2

In [9]:
unique_loc = df.unique(subset=['start', 'end', 'chr', 'gene', 'value_1', 'value_2'])

In [48]:
unique_loc.sort(['test_id'])

shape: (29_780, 18)
┌─────────────┬─────────────┬────────────┬────────────┬───┬────────────┬──────────┬──────────┬─────┐
│ test_id     ┆ gene_id     ┆ gene       ┆ locus      ┆ … ┆ chromosome ┆ start    ┆ end      ┆ chr │
│ ---         ┆ ---         ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---      ┆ ---      ┆ --- │
│ str         ┆ str         ┆ str        ┆ str        ┆   ┆ str        ┆ i64      ┆ i64      ┆ str │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪════════════╪══════════╪══════════╪═════╡
│ XLOC_000001 ┆ XLOC_000001 ┆ OR4F5      ┆ chr1:69090 ┆ … ┆ chr1       ┆ 69090    ┆ 70008    ┆ 1   │
│             ┆             ┆            ┆ -70008     ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000002 ┆ XLOC_000002 ┆ LOC1001320 ┆ chr1:32389 ┆ … ┆ chr1       ┆ 323891   ┆ 328581   ┆ 1   │
│             ┆             ┆ 62,LOC1001 ┆ 1-328581   ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆ 33331      ┆            ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000003 ┆ XLOC_000003 ┆ OR4F29     ┆ chr1:36765 ┆ … ┆ chr1       ┆ 367658   ┆ 368597   ┆ 1   │
│             ┆             ┆            ┆ 8-368597   ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000004 ┆ XLOC_000004 ┆ LOC643837  ┆ chr1:76158 ┆ … ┆ chr1       ┆ 761585   ┆ 794889   ┆ 1   │
│             ┆             ┆            ┆ 5-794889   ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000005 ┆ XLOC_000005 ┆ -          ┆ chr1:84026 ┆ … ┆ chr1       ┆ 840263   ┆ 843900   ┆ 1   │
│             ┆             ┆            ┆ 3-843900   ┆   ┆            ┆          ┆          ┆     │
│ …           ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …        ┆ …        ┆ …   │
│ XLOC_030028 ┆ XLOC_030028 ┆ -          ┆ chrY:13319 ┆ … ┆ chrY       ┆ 13319431 ┆ 13324829 ┆ Y   │
│             ┆             ┆            ┆ 431-133248 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 29         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030029 ┆ XLOC_030029 ┆ -          ┆ chrY:13325 ┆ … ┆ chrY       ┆ 13325034 ┆ 13326120 ┆ Y   │
│             ┆             ┆            ┆ 034-133261 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 20         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030030 ┆ XLOC_030030 ┆ -          ┆ chrY:13331 ┆ … ┆ chrY       ┆ 13331089 ┆ 13332358 ┆ Y   │
│             ┆             ┆            ┆ 089-133323 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 58         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030031 ┆ XLOC_030031 ┆ -          ┆ chrY:15053 ┆ … ┆ chrY       ┆ 15053270 ┆ 15053343 ┆ Y   │
│             ┆             ┆            ┆ 270-150533 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 43         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030032 ┆ XLOC_030032 ┆ -          ┆ chrY:59001 ┆ … ┆ chrY       ┆ 59001259 ┆ 59003893 ┆ Y   │
│             ┆             ┆            ┆ 259-590038 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 93         ┆   ┆            ┆          ┆          ┆     │
└─────────────┴─────────────┴────────────┴────────────┴───┴────────────┴──────────┴──────────┴─────┘

## Multiple gene names in one locus

In [11]:
# Multiple gene values
df.filter(pl.col('gene').str.contains(","))

shape: (852, 18)
┌─────────────┬─────────────┬────────────┬────────────┬───┬────────────┬──────────┬──────────┬─────┐
│ test_id     ┆ gene_id     ┆ gene       ┆ locus      ┆ … ┆ chromosome ┆ start    ┆ end      ┆ chr │
│ ---         ┆ ---         ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---      ┆ ---      ┆ --- │
│ str         ┆ str         ┆ str        ┆ str        ┆   ┆ str        ┆ i64      ┆ i64      ┆ str │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪════════════╪══════════╪══════════╪═════╡
│ XLOC_000002 ┆ XLOC_000002 ┆ LOC1001320 ┆ chr1:32389 ┆ … ┆ chr1       ┆ 323891   ┆ 328581   ┆ 1   │
│             ┆             ┆ 62,LOC1001 ┆ 1-328581   ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆ 33331      ┆            ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000007 ┆ XLOC_000007 ┆ KLHL17,PLE ┆ chr1:85113 ┆ … ┆ chr1       ┆ 851135   ┆ 917473   ┆ 1   │
│             ┆             ┆ KHN1       ┆ 5-917473   ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000012 ┆ XLOC_000012 ┆ MIR200A,MI ┆ chr1:10583 ┆ … ┆ chr1       ┆ 1058324  ┆ 1105717  ┆ 1   │
│             ┆             ┆ R200B,MIR4 ┆ 24-1105717 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆ 29         ┆            ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000085 ┆ XLOC_000085 ┆ APITD1,API ┆ chr1:10489 ┆ … ┆ chr1       ┆ 10489915 ┆ 10513512 ┆ 1   │
│             ┆             ┆ TD1-CORT,C ┆ 915-105135 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆ ORT        ┆ 12         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000111 ┆ XLOC_000111 ┆ PRAMEF7,PR ┆ chr1:12976 ┆ … ┆ chr1       ┆ 12976449 ┆ 12980568 ┆ 1   │
│             ┆             ┆ AMEF8      ┆ 449-129805 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 68         ┆   ┆            ┆          ┆          ┆     │
│ …           ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …        ┆ …        ┆ …   │
│ XLOC_029992 ┆ XLOC_029992 ┆ NCRNA00230 ┆ chrY:19687 ┆ … ┆ chrY       ┆ 19687040 ┆ 19691353 ┆ Y   │
│             ┆             ┆ A,NCRNA002 ┆ 040-196913 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆ 30B        ┆ 53         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_029994 ┆ XLOC_029994 ┆ CDY2A,CDY2 ┆ chrY:19990 ┆ … ┆ chrY       ┆ 19990139 ┆ 19992100 ┆ Y   │
│             ┆             ┆ B          ┆ 139-199921 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 00         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_029997 ┆ XLOC_029997 ┆ HSFY1,HSFY ┆ chrY:20891 ┆ … ┆ chrY       ┆ 20891767 ┆ 20935621 ┆ Y   │
│             ┆             ┆ 2          ┆ 767-209356 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 21         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030011 ┆ XLOC_030011 ┆ TTTY6,TTTY ┆ chrY:24585 ┆ … ┆ chrY       ┆ 24585736 ┆ 24587606 ┆ Y   │
│             ┆             ┆ 6B         ┆ 736-245876 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 06         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030012 ┆ XLOC_030012 ┆ DAZ1,DAZ4  ┆ chrY:25275 ┆ … ┆ chrY       ┆ 25275501 ┆ 25345239 ┆ Y   │
│             ┆             ┆            ┆ 501-253452 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 39         ┆   ┆            ┆          ┆          ┆     │
└─────────────┴─────────────┴────────────┴────────────┴───┴────────────┴──────────┴──────────┴─────┘

## Empty gene name

In [12]:
# Empty gene name
df.filter(pl.col('gene') == '-')

shape: (6_729, 18)
┌─────────────┬─────────────┬──────┬──────────────────┬───┬────────────┬──────────┬──────────┬─────┐
│ test_id     ┆ gene_id     ┆ gene ┆ locus            ┆ … ┆ chromosome ┆ start    ┆ end      ┆ chr │
│ ---         ┆ ---         ┆ ---  ┆ ---              ┆   ┆ ---        ┆ ---      ┆ ---      ┆ --- │
│ str         ┆ str         ┆ str  ┆ str              ┆   ┆ str        ┆ i64      ┆ i64      ┆ str │
╞═════════════╪═════════════╪══════╪══════════════════╪═══╪════════════╪══════════╪══════════╪═════╡
│ XLOC_000005 ┆ XLOC_000005 ┆ -    ┆ chr1:840263-8439 ┆ … ┆ chr1       ┆ 840263   ┆ 843900   ┆ 1   │
│             ┆             ┆      ┆ 00               ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000010 ┆ XLOC_000010 ┆ -    ┆ chr1:993794-1004 ┆ … ┆ chr1       ┆ 993794   ┆ 1004436  ┆ 1   │
│             ┆             ┆      ┆ 436              ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000011 ┆ XLOC_000011 ┆ -    ┆ chr1:1004537-100 ┆ … ┆ chr1       ┆ 1004537  ┆ 1006002  ┆ 1   │
│             ┆             ┆      ┆ 6002             ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000013 ┆ XLOC_000013 ┆ -    ┆ chr1:1058324-110 ┆ … ┆ chr1       ┆ 1058324  ┆ 1105717  ┆ 1   │
│             ┆             ┆      ┆ 5717             ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000016 ┆ XLOC_000016 ┆ -    ┆ chr1:1176090-117 ┆ … ┆ chr1       ┆ 1176090  ┆ 1177128  ┆ 1   │
│             ┆             ┆      ┆ 7128             ┆   ┆            ┆          ┆          ┆     │
│ …           ┆ …           ┆ …    ┆ …                ┆ … ┆ …          ┆ …        ┆ …        ┆ …   │
│ XLOC_030028 ┆ XLOC_030028 ┆ -    ┆ chrY:13319431-13 ┆ … ┆ chrY       ┆ 13319431 ┆ 13324829 ┆ Y   │
│             ┆             ┆      ┆ 324829           ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030029 ┆ XLOC_030029 ┆ -    ┆ chrY:13325034-13 ┆ … ┆ chrY       ┆ 13325034 ┆ 13326120 ┆ Y   │
│             ┆             ┆      ┆ 326120           ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030030 ┆ XLOC_030030 ┆ -    ┆ chrY:13331089-13 ┆ … ┆ chrY       ┆ 13331089 ┆ 13332358 ┆ Y   │
│             ┆             ┆      ┆ 332358           ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030031 ┆ XLOC_030031 ┆ -    ┆ chrY:15053270-15 ┆ … ┆ chrY       ┆ 15053270 ┆ 15053343 ┆ Y   │
│             ┆             ┆      ┆ 053343           ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030032 ┆ XLOC_030032 ┆ -    ┆ chrY:59001259-59 ┆ … ┆ chrY       ┆ 59001259 ┆ 59003893 ┆ Y   │
│             ┆             ┆      ┆ 003893           ┆   ┆            ┆          ┆          ┆     │
└─────────────┴─────────────┴──────┴──────────────────┴───┴────────────┴──────────┴──────────┴─────┘

## Single locus, multiple test_id

In [13]:
# Single locus, multiple genes
df.group_by('locus')\
.agg(pl.len().alias('count'))\
.sort('count', descending=True)

shape: (24_018, 2)
┌──────────────────────────┬───────┐
│ locus                    ┆ count │
│ ---                      ┆ ---   │
│ str                      ┆ u32   │
╞══════════════════════════╪═══════╡
│ chr15:25226925-25367623  ┆ 25    │
│ chr10:9002423-9312354    ┆ 19    │
│ chr21:45904886-46131495  ┆ 18    │
│ chr16:85202966-85722588  ┆ 16    │
│ chr11:1490684-1785501    ┆ 16    │
│ …                        ┆ …     │
│ chr6:169494202-169495587 ┆ 1     │
│ chrX:150336693-150336798 ┆ 1     │
│ chr17:33700942-33701706  ┆ 1     │
│ chr15:99058149-99059155  ┆ 1     │
│ chr8:25316232-25371834   ┆ 1     │
└──────────────────────────┴───────┘

In [14]:
df.group_by('locus')\
.agg(pl.len().alias('count'))\
.sort('count', descending=True)\
.filter(pl.col('count') > 1)

shape: (3_871, 2)
┌──────────────────────────┬───────┐
│ locus                    ┆ count │
│ ---                      ┆ ---   │
│ str                      ┆ u32   │
╞══════════════════════════╪═══════╡
│ chr15:25226925-25367623  ┆ 25    │
│ chr10:9002423-9312354    ┆ 19    │
│ chr21:45904886-46131495  ┆ 18    │
│ chr11:1490684-1785501    ┆ 16    │
│ chr16:85202966-85722588  ┆ 16    │
│ …                        ┆ …     │
│ chr3:193675160-193721448 ┆ 2     │
│ chr4:83550689-83720010   ┆ 2     │
│ chr14:24407939-24520580  ┆ 2     │
│ chr1:151129104-151138430 ┆ 2     │
│ chrX:123509755-124288856 ┆ 2     │
└──────────────────────────┴───────┘

In [15]:
df.filter(pl.col('locus') == 'chr15:25226925-25367623')

shape: (25, 18)
┌─────────────┬─────────────┬────────────┬────────────┬───┬────────────┬──────────┬──────────┬─────┐
│ test_id     ┆ gene_id     ┆ gene       ┆ locus      ┆ … ┆ chromosome ┆ start    ┆ end      ┆ chr │
│ ---         ┆ ---         ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---      ┆ ---      ┆ --- │
│ str         ┆ str         ┆ str        ┆ str        ┆   ┆ str        ┆ i64      ┆ i64      ┆ str │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪════════════╪══════════╪══════════╪═════╡
│ XLOC_008650 ┆ XLOC_008650 ┆ IPW,PAR-SN ┆ chr15:2522 ┆ … ┆ chr15      ┆ 25226925 ┆ 25367623 ┆ 15  │
│             ┆             ┆ ,PAR5,SNOR ┆ 6925-25367 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆ D109B,SNOR ┆ 623        ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆ …          ┆            ┆   ┆            ┆          ┆          ┆     │
│ XLOC_008651 ┆ XLOC_008651 ┆ SNORD116-1 ┆ chr15:2522 ┆ … ┆ chr15      ┆ 25226925 ┆ 25367623 ┆ 15  │
│             ┆             ┆            ┆ 6925-25367 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 623        ┆   ┆            ┆          ┆          ┆     │
│ XLOC_008652 ┆ XLOC_008652 ┆ SNORD116-2 ┆ chr15:2522 ┆ … ┆ chr15      ┆ 25226925 ┆ 25367623 ┆ 15  │
│             ┆             ┆            ┆ 6925-25367 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 623        ┆   ┆            ┆          ┆          ┆     │
│ XLOC_008653 ┆ XLOC_008653 ┆ SNORD116-3 ┆ chr15:2522 ┆ … ┆ chr15      ┆ 25226925 ┆ 25367623 ┆ 15  │
│             ┆             ┆            ┆ 6925-25367 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 623        ┆   ┆            ┆          ┆          ┆     │
│ XLOC_008654 ┆ XLOC_008654 ┆ SNORD116-7 ┆ chr15:2522 ┆ … ┆ chr15      ┆ 25226925 ┆ 25367623 ┆ 15  │
│             ┆             ┆            ┆ 6925-25367 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 623        ┆   ┆            ┆          ┆          ┆     │
│ …           ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …        ┆ …        ┆ …   │
│ XLOC_008670 ┆ XLOC_008670 ┆ SNORD116-2 ┆ chr15:2522 ┆ … ┆ chr15      ┆ 25226925 ┆ 25367623 ┆ 15  │
│             ┆             ┆ 6          ┆ 6925-25367 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 623        ┆   ┆            ┆          ┆          ┆     │
│ XLOC_008671 ┆ XLOC_008671 ┆ SNORD116-2 ┆ chr15:2522 ┆ … ┆ chr15      ┆ 25226925 ┆ 25367623 ┆ 15  │
│             ┆             ┆ 7          ┆ 6925-25367 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 623        ┆   ┆            ┆          ┆          ┆     │
│ XLOC_008672 ┆ XLOC_008672 ┆ SNORD116-2 ┆ chr15:2522 ┆ … ┆ chr15      ┆ 25226925 ┆ 25367623 ┆ 15  │
│             ┆             ┆ 8          ┆ 6925-25367 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 623        ┆   ┆            ┆          ┆          ┆     │
│ XLOC_008673 ┆ XLOC_008673 ┆ SNORD116-2 ┆ chr15:2522 ┆ … ┆ chr15      ┆ 25226925 ┆ 25367623 ┆ 15  │
│             ┆             ┆ 9          ┆ 6925-25367 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 623        ┆   ┆            ┆          ┆          ┆     │
│ XLOC_009481 ┆ XLOC_009481 ┆ -          ┆ chr15:2522 ┆ … ┆ chr15      ┆ 25226925 ┆ 25367623 ┆ 15  │
│             ┆             ┆            ┆ 6925-25367 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 623        ┆   ┆            ┆          ┆          ┆     │
└─────────────┴─────────────┴────────────┴────────────┴───┴────────────┴──────────┴──────────┴─────┘

# User defined function

## Query all GRCh37/hg19

In [16]:
def query_all():
    # Connect to the GRCh37 archive server
    server = Server(host='http://grch37.ensembl.org')
    
    # Select the human dataset
    dataset = (server.marts['ENSEMBL_MART_ENSEMBL']
               .datasets['hsapiens_gene_ensembl'])

    result = dataset.query(attributes=['chromosome_name', 
                                   'start_position', 
                                   'end_position', 
                                   'strand',
                                   'external_gene_name', 
                                   'ensembl_gene_id',
                                   'gene_biotype'])
    
    result['tss'] = result.apply(lambda row: row['Gene start (bp)'] if row['Strand'] == 1 else row['Gene end (bp)'], axis=1)
    result['tss_2kb_start'] = result['tss'] - 2000
    result['tss_2kb_end'] = result['tss'] + 2000
    return result

In [17]:
all_results = query_all()

## Query by location

In [27]:
def query_ensembl_by_location(item):

    chrom = item[17]
    start = item[15]
    end = item[16]
    gene_name = item[2]
    test_id = item[0]
    locus = item[3]
    
    # Connect to the GRCh37 archive server
    server = Server(host='http://grch37.ensembl.org')
    
    # Select the human dataset
    dataset = (server.marts['ENSEMBL_MART_ENSEMBL']
               .datasets['hsapiens_gene_ensembl'])

    result = dataset.query(attributes=['chromosome_name', 
                                   'start_position', 
                                   'end_position', 
                                   'strand',
                                   'external_gene_name', 
                                   'ensembl_gene_id',
                                   'gene_biotype'],
                       filters={'chromosome_name': chrom,
                                'start': start,
                                'end': end})
    
    result['tss'] = result.apply(lambda row: row['Gene start (bp)'] if row['Strand'] == 1 else row['Gene end (bp)'], axis=1)
    result['tss -2kb'] = result['tss'] - 2000
    result['tss +2kb'] = result['tss'] + 2000
    result['test_id'] = test_id
    result['orig_gene_name'] = gene_name
    result['locus'] = locus
    result['orig_start'] = start
    result['orig_end'] = end
    return result

## Convert Dataframe to Numpy Matrix

In [28]:
exploded_np = exploded_df.to_numpy()

## Query testing

In [35]:
# chr1:323891-328581
# chr1:69090-70008
# chr15:25226925-25367623
# chr10:9002423-9312354
# chr21:45904886-46131495
# chr21:46188604-46224474
# chr1:31184123-31199593
# "PRAMEF7,PRAMEF8"	"chr1:12976449-12980568"
# chr1:993794-1004436 -> empty gene name
# chr1:1058324-1105717 	MIR200A,MIR200B,MIR429
# ARHGEF16	chr1:3366055-3402204 XLOC_000046

test_item = exploded_df.filter(pl.col('gene') == 'MIR200A').to_numpy()[0]

result = query_ensembl_by_location(test_item)
result

,Chromosome/scaffold name,Gene start (bp),Gene end (bp),Strand,Gene name,Gene stable ID,Gene type,tss,tss -2kb,tss +2kb,test_id,orig_gene_name,locus,orig_start,orig_end
0,1,1072397,1079436,1,RP11-465B22.5,ENSG00000223823,lincRNA,1072397,1070397,1074397,XLOC_000012,MIR200A,chr1:1058324-1105717,1058324,1105717
1,1,1102484,1102578,1,MIR200B,ENSG00000207730,miRNA,1102484,1100484,1104484,XLOC_000012,MIR200A,chr1:1058324-1105717,1058324,1105717
2,1,1103243,1103332,1,MIR200A,ENSG00000207607,miRNA,1103243,1101243,1105243,XLOC_000012,MIR200A,chr1:1058324-1105717,1058324,1105717
3,1,1104385,1104467,1,MIR429,ENSG00000198976,miRNA,1104385,1102385,1106385,XLOC_000012,MIR200A,chr1:1058324-1105717,1058324,1105717
4,1,1104737,1105723,1,RP11-465B22.8,ENSG00000272141,lincRNA,1104737,1102737,1106737,XLOC_000012,MIR200A,chr1:1058324-1105717,1058324,1105717

In [47]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Chromosome/scaffold name  1 non-null      object
 1   Gene start (bp)           1 non-null      int64
 2   Gene end (bp)             1 non-null      int64
 3   Strand                    1 non-null      int64
 4   Gene name                 1 non-null      object
 5   Gene stable ID            1 non-null      object
 6   Gene type                 1 non-null      object
 7   tss                       1 non-null      int64
 8   tss -2kb                  1 non-null      int64
 9   tss +2kb                  1 non-null      int64
 10  test_id                   1 non-null      object
 11  orig_gene_name            1 non-null      object
 12  locus                     1 non-null      object
 13  orig_start                1 non-null      int64
 14  orig_end                  1 non-null      int64
dtypes: int64(8), object(7)
memory usage: 252.0+ bytes

In [37]:
exploded_np[0]

array(['XLOC_000001', 'XLOC_000001', 'OR4F5', 'chr1:69090-70008',
       'hepg2_hr2', 'hepg2_hr3', 'NOTEST', 0.0, 0.0, 0.0, 0.0, 1.0, 1.0,
       'no', 'chr1', 69090, 70008, '1'], dtype=object)

# Query for all items

In [42]:
output_path = os.path.join(WORKING_DIR, 'dataset', 'ensembl.csv')

i = 1
total = exploded_np.shape[0]

for item in exploded_np:

    if ((i % 100 == 0) or (i == total)):
        print(f"{i}/{total} - {item[0]} - {item[2]}")
    
    result = query_ensembl_by_location(item)
    result.to_csv(output_path, mode='a', header=(not os.path.exists(output_path)), index=False)
    i += 1

100/31121 - XLOC_000094 - AGTRAP
200/31121 - XLOC_000190 - RPL11
300/31121 - XLOC_000284 - PHC2
400/31121 - XLOC_000380 - LOC400752
500/31121 - XLOC_000477 - HHLA3
600/31121 - XLOC_000569 - HEJ1
700/31121 - XLOC_000667 - -
800/31121 - XLOC_000761 - LCE3C
900/31121 - XLOC_000855 - PYHIN1
1000/31121 - XLOC_000951 - GPR52
1100/31121 - XLOC_001050 - -
1200/31121 - XLOC_001149 - EPHX1
1300/31121 - XLOC_001246 - OR2T5
1400/31121 - XLOC_001341 - -
1500/31121 - XLOC_001435 - LUZP1
1600/31121 - XLOC_001531 - -
1700/31121 - XLOC_001627 - STIL
1800/31121 - XLOC_001726 - MCOLN3
1900/31121 - XLOC_001823 - SLC16A1
2000/31121 - XLOC_001915 - ANP32E
2100/31121 - XLOC_002007 - C1orf104
2200/31121 - XLOC_002101 - LMX1A
2300/31121 - XLOC_002199 - PDC
2400/31121 - XLOC_002296 - RD3
2500/31121 - XLOC_002393 - TOMM20
2600/31121 - XLOC_002492 - -
2700/31121 - XLOC_002592 - -
2800/31121 - XLOC_002692 - -
2900/31121 - XLOC_002792 - -
3000/31121 - XLOC_002892 - ANKRD16
3100/31121 - XLOC_002990 - RET
3200/31121 - XLOC_003089 - CCDC109A
3300/31121 - XLOC_003185 - CYP2C19
3400/31121 - XLOC_003282 - C10orf96
3500/31121 - XLOC_003379 - CALML5
3600/31121 - XLOC_003479 - SEPT7L
3700/31121 - XLOC_003575 - C10orf54
3800/31121 - XLOC_003672 - ARHGAP19
3900/31121 - XLOC_003769 - RGS10
4000/31121 - XLOC_003866 - -
4100/31121 - XLOC_003966 - -
4200/31121 - XLOC_004066 - EPS8L2
4300/31121 - XLOC_004161 - EIF3F
4400/31121 - XLOC_004261 - LOC729799
4500/31121 - XLOC_004355 - OR4D11
4600/31121 - XLOC_004449 - CDC42EP2
4700/31121 - XLOC_004539 - P2RY2
4800/31121 - XLOC_004636 - -
4900/31121 - XLOC_004731 - OR8G5
5000/31121 - XLOC_004827 - MRGPRG
5100/31121 - XLOC_004925 - DKK3
5200/31121 - XLOC_005019 - -
5300/31121 - XLOC_005117 - BSCL2
5400/31121 - XLOC_005204 - LOC645332
5500/31121 - XLOC_005302 - TRIM49
5600/31121 - XLOC_005399 - AMICA1
5700/31121 - XLOC_005497 - -
5800/31121 - XLOC_005597 - -
5900/31121 - XLOC_005697 - KCNA6
6000/31121 - XLOC_005791 - DERA
6100/31121 - XLOC_005889 - DIP2B
6200/31121 - XLOC_005979 - LRP1
6300/31121 - XLOC_006078 - -
6400/31121 - XLOC_006176 - SDSL
6500/31121 - XLOC_006273 - SLC6A12
6600/31121 - XLOC_006368 - TAS2R30
6700/31121 - XLOC_006468 - ENDOU
6800/31121 - XLOC_006562 - NFE2
6900/31121 - XLOC_006658 - KRR1
7000/31121 - XLOC_006755 - MMAB
7100/31121 - XLOC_006855 - LOC440117
7200/31121 - XLOC_006954 - -
7300/31121 - XLOC_007054 - -
7400/31121 - XLOC_007154 - NUDT15
7500/31121 - XLOC_007244 - LOC728192
7600/31121 - XLOC_007341 - ALG5
7700/31121 - XLOC_007440 - LOC642345
7800/31121 - XLOC_007540 - -
7900/31121 - XLOC_007639 - RPGRIP1
8000/31121 - XLOC_007730 - ARF6
8100/31121 - XLOC_007828 - ZNF410
8200/31121 - XLOC_007928 - MIR770
8300/31121 - XLOC_008028 - AMN
8400/31121 - XLOC_008124 - C14orf165
8500/31121 - XLOC_008217 - GMFB
8600/31121 - XLOC_008313 - C14orf4
8700/31121 - XLOC_008412 - SIVA1
8800/31121 - XLOC_008512 - -
8900/31121 - XLOC_008612 - -
9000/31121 - XLOC_008696 - SNORD115-24
9100/31121 - XLOC_008789 - TTBK2
9200/31121 - XLOC_008886 - SMAD3
9300/31121 - XLOC_008984 - LOC440297
9400/31121 - XLOC_009082 - HERC2P3
9500/31121 - XLOC_009179 - EPB42
9600/31121 - XLOC_009279 - PIF1
9700/31121 - XLOC_009373 - CHRNB4
9800/31121 - XLOC_009466 - -
9900/31121 - XLOC_009565 - -
10000/31121 - XLOC_009657 - HN1L
10100/31121 - XLOC_009751 - MIR365-1
10200/31121 - XLOC_009841 - MVP
10300/31121 - XLOC_009932 - MIR138-2
10400/31121 - XLOC_010024 - HP
10500/31121 - XLOC_010118 - AXIN1
10600/31121 - XLOC_010212 - GLYR1
10700/31121 - XLOC_010310 - XPO6
10800/31121 - XLOC_010404 - AKTIP
10900/31121 - XLOC_010497 - TAT
11000/31121 - XLOC_010594 - -
11100/31121 - XLOC_010694 - -
11200/31121 - XLOC_010793 - ASPA
11300/31121 - XLOC_010883 - MAP2K4
11400/31121 - XLOC_010979 - BLMH
11500/31121 - XLOC_011077 - RARA
11600/31121 - XLOC_011172 - LRRC46
11700/31121 - XLOC_011269 - C17orf60
11800/31121 - XLOC_011367 - CCDC40
11900/31121 - XLOC_011460 - MYBBP1A
12000/31121 - XLOC_011550 - CDRT15
12100/31121 - XLOC_011643 - C17orf79
12200/31121 - XLOC_011739 - LOC730755
12300/31121 - XLOC_011837 - LOC100128977
12400/31121 - XLOC_011930 - SKA2
12500/31121 - XLOC_012027 - RECQL5
12600/31121 - XLOC_012122 - -
12700/31121 - XLOC_012222 - -
12800/31121 - XLOC_012322 - -
12900/31121 - XLOC_012417 - RNMT
13000/31121 - XLOC_012517 - PHLPP1
13100/31121 - XLOC_012616 - AQP4
13200/31121 - XLOC_012713 - -
13300/31121 - XLOC_012813 - -
13400/31121 - XLOC_012908 - MIR7-3
13500/31121 - XLOC_013000 - ZNF69
13600/31121 - XLOC_013095 - MIR3188
13700/31121 - XLOC_013191 - RBM42
13800/31121 - XLOC_013289 - CEACAM5
13900/31121 - XLOC_013387 - SNAR-C3
14000/31121 - XLOC_013481 - ZNF528
14100/31121 - XLOC_013581 - TMEM190
14200/31121 - XLOC_013674 - MEX3D
14300/31121 - XLOC_013771 - CD209
14400/31121 - XLOC_013858 - CACNA1A
14500/31121 - XLOC_013952 - ZNF43
14600/31121 - XLOC_014048 - SYCN
14700/31121 - XLOC_014141 - PPP1R13L
14800/31121 - XLOC_014234 - AKT1S1
14900/31121 - XLOC_014321 - LILRB2
15000/31121 - XLOC_014417 - -
15100/31121 - XLOC_014517 - -
15200/31121 - XLOC_014614 - KCNK3
15300/31121 - XLOC_014708 - CHAC2
15400/31121 - XLOC_014807 - TCF7L1
15500/31121 - XLOC_014905 - CCDC138
15600/31121 - XLOC_014999 - UBXN4
15700/31121 - XLOC_015094 - DFNB59
15800/31121 - XLOC_015194 - ABCA12
15900/31121 - XLOC_015284 - UGT1A9
16000/31121 - XLOC_015383 - RAD51AP2
16100/31121 - XLOC_015478 - ZFP36L2
16200/31121 - XLOC_015576 - DUSP11
16300/31121 - XLOC_015670 - AFF3
16400/31121 - XLOC_015767 - NCKAP5
16500/31121 - XLOC_015865 - NFE2L2
16600/31121 - XLOC_015965 - ABCA12
16700/31121 - XLOC_016061 - MGC16025
16800/31121 - XLOC_016161 - -
16900/31121 - XLOC_016261 - -
17000/31121 - XLOC_016361 - -
17100/31121 - XLOC_016457 - HSPA12B
17200/31121 - XLOC_016556 - XKR7
17300/31121 - XLOC_016651 - RBPJL
17400/31121 - XLOC_016747 - OGFR
17500/31121 - XLOC_016841 - ANKRD5
17600/31121 - XLOC_016938 - UQCC
17700/31121 - XLOC_017030 - KCNG1
17800/31121 - XLOC_017128 - -
17900/31121 - XLOC_017227 - CHODL
18000/31121 - XLOC_017325 - RRP1
18100/31121 - XLOC_017420 - KRTAP19-7
18200/31121 - XLOC_017518 - C21orf67
18300/31121 - XLOC_017618 - -
18400/31121 - XLOC_017715 - GGT1
18500/31121 - XLOC_017811 - GTPBP1
18600/31121 - XLOC_017903 - ACR
18700/31121 - XLOC_018000 - MN1
18800/31121 - XLOC_018097 - CBX6
18900/31121 - XLOC_018192 - -
19000/31121 - XLOC_018292 - BHLHE40
19100/31121 - XLOC_018389 - ITGA9
19200/31121 - XLOC_018484 - RBM6
19300/31121 - XLOC_018582 - NSUN3
19400/31121 - XLOC_018679 - PARP15
19500/31121 - XLOC_018778 - RNF13
19600/31121 - XLOC_018876 - EIF4G1
19700/31121 - XLOC_018972 - SEC13
19800/31121 - XLOC_019071 - SLC6A20
19900/31121 - XLOC_019157 - TWF2
20000/31121 - XLOC_019253 - TOMM70A
20100/31121 - XLOC_019351 - C3orf27
20200/31121 - XLOC_019451 - PLCH1
20300/31121 - XLOC_019549 - -
20400/31121 - XLOC_019648 - -
20500/31121 - XLOC_019748 - -
20600/31121 - XLOC_019848 - -
20700/31121 - XLOC_019946 - MIR572
20800/31121 - XLOC_020045 - LOC550112
20900/31121 - XLOC_020143 - RAP1GDS1
21000/31121 - XLOC_020243 - EDNRA
21100/31121 - XLOC_020343 - DUX4
21200/31121 - XLOC_020439 - TLR1
21300/31121 - XLOC_020538 - CXCL11
21400/31121 - XLOC_020636 - NEUROG2
21500/31121 - XLOC_020734 - NAF1
21600/31121 - XLOC_020834 - -
21700/31121 - XLOC_020934 - -
21800/31121 - XLOC_021031 - LOC255167
21900/31121 - XLOC_021128 - C5orf43
22000/31121 - XLOC_021225 - NR2F1
22100/31121 - XLOC_021324 - DDX46
22200/31121 - XLOC_021381 - PCDHGB7
22300/31121 - XLOC_021476 - NPM1
22400/31121 - XLOC_021573 - -
22500/31121 - XLOC_021672 - EMB
22600/31121 - XLOC_021771 - LOC645323
22700/31121 - XLOC_021867 - PITX1
22800/31121 - XLOC_021962 - ATOX1
22900/31121 - XLOC_022060 - RNF130
23000/31121 - XLOC_022160 - -
23100/31121 - XLOC_022260 - -
23200/31121 - XLOC_022360 - PPP1R3G
23300/31121 - XLOC_022456 - HIST1H3H
23400/31121 - XLOC_022547 - CYP21A2
23500/31121 - XLOC_022641 - POLR1C
23600/31121 - XLOC_022741 - C6orf162
23700/31121 - XLOC_022840 - -
23800/31121 - XLOC_022940 - MAS1
23900/31121 - XLOC_023037 - -
24000/31121 - XLOC_023135 - KIAA1949
24100/31121 - XLOC_023220 - C6orf222
24200/31121 - XLOC_023316 - -
24300/31121 - XLOC_023415 - SNX3
24400/31121 - XLOC_023514 - CCDC28A
24500/31121 - XLOC_023613 - -
24600/31121 - XLOC_023713 - -
24700/31121 - XLOC_023813 - -
24800/31121 - XLOC_023913 - TRIM15
24900/31121 - XLOC_024010 - HLA-J
25000/31121 - XLOC_024108 - GNL1
25100/31121 - XLOC_024205 - RPP21
25200/31121 - XLOC_024303 - PSORS1C2
25300/31121 - XLOC_024400 - MICA
25400/31121 - XLOC_024499 - TAP2
25500/31121 - XLOC_024596 - OR5V1
25600/31121 - XLOC_024694 - HLA-H
25700/31121 - XLOC_024792 - GNL1
25800/31121 - XLOC_024888 - ATAT1
25900/31121 - XLOC_024988 - VARS
26000/31121 - XLOC_025085 - BZW2
26100/31121 - XLOC_025183 - OGDH
26200/31121 - XLOC_025280 - GTF2IRD2B
26300/31121 - XLOC_025377 - AGFG2
26400/31121 - XLOC_025473 - ATP6V1F
26500/31121 - XLOC_025571 - ZNF282
26600/31121 - XLOC_025667 - COL28A1
26700/31121 - XLOC_025763 - GLI3
26800/31121 - XLOC_025860 - CLDN3
26900/31121 - XLOC_025956 - CYP3A7
27000/31121 - XLOC_026053 - FEZF1
27100/31121 - XLOC_026151 - CTAGE4
27200/31121 - XLOC_026250 - -
27300/31121 - XLOC_026350 - -
27400/31121 - XLOC_026450 - MYOM2
27500/31121 - XLOC_026545 - BNIP3L
27600/31121 - XLOC_026644 - SGK3
27700/31121 - XLOC_026743 - EBAG9
27800/31121 - XLOC_026838 - PPP1R16A
27900/31121 - XLOC_026938 - LGI3
28000/31121 - XLOC_027036 - RB1CC1
28100/31121 - XLOC_027136 - TMEM64
28200/31121 - XLOC_027236 - LOC728724
28300/31121 - XLOC_027329 - -
28400/31121 - XLOC_027429 - -
28500/31121 - XLOC_027529 - -
28600/31121 - XLOC_027628 - ATP8B5P
28700/31121 - XLOC_027728 - SPIN1
28800/31121 - XLOC_027821 - DNAJC25-GNG10
28900/31121 - XLOC_027919 - PPP2R4
29000/31121 - XLOC_028011 - MRPL41
29100/31121 - XLOC_028111 - -
29200/31121 - XLOC_028205 - -
29300/31121 - XLOC_028303 - -
29400/31121 - XLOC_028403 - NR6A1
29500/31121 - XLOC_028499 - SNAPC4
29600/31121 - XLOC_028595 - -
29700/31121 - XLOC_028695 - -
29800/31121 - XLOC_028793 - CD99P1
29900/31121 - XLOC_028891 - -
30000/31121 - XLOC_028972 - FAM156A
30100/31121 - XLOC_029070 - SRPX2
30200/31121 - XLOC_029165 - SH2D1A
30300/31121 - XLOC_029261 - -
30400/31121 - XLOC_029358 - MIR23C
30500/31121 - XLOC_029449 - XAGE3
30600/31121 - XLOC_029545 - PCDH19
30700/31121 - XLOC_029640 - DCAF12L2
30800/31121 - XLOC_029738 - CXorf40B
30900/31121 - XLOC_029832 - -
31000/31121 - XLOC_029928 - USP9Y
31100/31121 - XLOC_030012 - DAZ1
31121/31121 - XLOC_030032 - -