In [1]:
import polars as pl
from pybiomart import Server
import os
import numpy as np
import pandas as pd

In [2]:
WORKING_DIR = '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2'
DATASET_DIR = '/group/pmc021/amunif/epi-thesis/dataset'

In [3]:
def query_ensembl_by_location(item):

    chrom = item[17]
    chromosome = item[14]
    start = item[15]
    end = item[16]
    test_id = item[0]
    gene_id = item[1]
    locus = item[3]
    
    # Connect to the GRCh37 archive server
    server = Server(host='http://grch37.ensembl.org')
    
    # Select the human dataset
    dataset = (server.marts['ENSEMBL_MART_ENSEMBL']
               .datasets['hsapiens_gene_ensembl'])

    result = dataset.query(attributes=['chromosome_name', 
                                   'start_position', 
                                   'end_position', 
                                   'strand',
                                   'external_gene_name', 
                                   'ensembl_gene_id',
                                   'gene_biotype'],
                       filters={'chromosome_name': chrom,
                                'start': start,
                                'end': end})
    
    result['tss'] = result.apply(lambda row: row['Gene start (bp)'] if row['Strand'] == 1 else row['Gene end (bp)'], axis=1)
    result['tss -2kb'] = result['tss'] - 2000
    result['tss +2kb'] = result['tss'] + 2000
    result['test_id'] = test_id
    result['gene_id'] = gene_id
    result['locus'] = locus
    result['chromosome'] = chromosome
    result['orig_start'] = start
    result['orig_end'] = end
    return result

In [4]:
# Open file
df = pl.read_csv(os.path.join(DATASET_DIR, 'GSM3718064_HepG2_exp.txt'), separator="\t")

In [5]:
# Split locus column into 3 columns: chr, start, end
df = df.with_columns([
    pl.col("locus").str.split(":").list.get(0).alias("chromosome"),
    pl.col("locus").str.split(":").list.get(1).str.split_exact("-", 1).struct.rename_fields(["start", "end"]).alias("position")
])

# Unnest the column and convert into integer
df = df.unnest("position")

df = df.with_columns([
    pl.col("start").cast(pl.Int64),
    pl.col("end").cast(pl.Int64)
])

df = df.with_columns([
    pl.col('chromosome').str.replace('chr', '').alias('chr')
])

df

shape: (30_032, 18)
┌─────────────┬─────────────┬────────────┬────────────┬───┬────────────┬──────────┬──────────┬─────┐
│ test_id     ┆ gene_id     ┆ gene       ┆ locus      ┆ … ┆ chromosome ┆ start    ┆ end      ┆ chr │
│ ---         ┆ ---         ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---      ┆ ---      ┆ --- │
│ str         ┆ str         ┆ str        ┆ str        ┆   ┆ str        ┆ i64      ┆ i64      ┆ str │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪════════════╪══════════╪══════════╪═════╡
│ XLOC_000001 ┆ XLOC_000001 ┆ OR4F5      ┆ chr1:69090 ┆ … ┆ chr1       ┆ 69090    ┆ 70008    ┆ 1   │
│             ┆             ┆            ┆ -70008     ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000002 ┆ XLOC_000002 ┆ LOC1001320 ┆ chr1:32389 ┆ … ┆ chr1       ┆ 323891   ┆ 328581   ┆ 1   │
│             ┆             ┆ 62,LOC1001 ┆ 1-328581   ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆ 33331      ┆            ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000003 ┆ XLOC_000003 ┆ OR4F29     ┆ chr1:36765 ┆ … ┆ chr1       ┆ 367658   ┆ 368597   ┆ 1   │
│             ┆             ┆            ┆ 8-368597   ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000004 ┆ XLOC_000004 ┆ LOC643837  ┆ chr1:76158 ┆ … ┆ chr1       ┆ 761585   ┆ 794889   ┆ 1   │
│             ┆             ┆            ┆ 5-794889   ┆   ┆            ┆          ┆          ┆     │
│ XLOC_000005 ┆ XLOC_000005 ┆ -          ┆ chr1:84026 ┆ … ┆ chr1       ┆ 840263   ┆ 843900   ┆ 1   │
│             ┆             ┆            ┆ 3-843900   ┆   ┆            ┆          ┆          ┆     │
│ …           ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …        ┆ …        ┆ …   │
│ XLOC_030028 ┆ XLOC_030028 ┆ -          ┆ chrY:13319 ┆ … ┆ chrY       ┆ 13319431 ┆ 13324829 ┆ Y   │
│             ┆             ┆            ┆ 431-133248 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 29         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030029 ┆ XLOC_030029 ┆ -          ┆ chrY:13325 ┆ … ┆ chrY       ┆ 13325034 ┆ 13326120 ┆ Y   │
│             ┆             ┆            ┆ 034-133261 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 20         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030030 ┆ XLOC_030030 ┆ -          ┆ chrY:13331 ┆ … ┆ chrY       ┆ 13331089 ┆ 13332358 ┆ Y   │
│             ┆             ┆            ┆ 089-133323 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 58         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030031 ┆ XLOC_030031 ┆ -          ┆ chrY:15053 ┆ … ┆ chrY       ┆ 15053270 ┆ 15053343 ┆ Y   │
│             ┆             ┆            ┆ 270-150533 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 43         ┆   ┆            ┆          ┆          ┆     │
│ XLOC_030032 ┆ XLOC_030032 ┆ -          ┆ chrY:59001 ┆ … ┆ chrY       ┆ 59001259 ┆ 59003893 ┆ Y   │
│             ┆             ┆            ┆ 259-590038 ┆   ┆            ┆          ┆          ┆     │
│             ┆             ┆            ┆ 93         ┆   ┆            ┆          ┆          ┆     │
└─────────────┴─────────────┴────────────┴────────────┴───┴────────────┴──────────┴──────────┴─────┘

In [6]:
df_np = df.to_numpy()

In [7]:
df_np

array([['XLOC_000001', 'XLOC_000001', 'OR4F5', ..., 69090, 70008, '1'],
       ['XLOC_000002', 'XLOC_000002', 'LOC100132062,LOC100133331', ...,
        323891, 328581, '1'],
       ['XLOC_000003', 'XLOC_000003', 'OR4F29', ..., 367658, 368597, '1'],
       ...,
       ['XLOC_030030', 'XLOC_030030', '-', ..., 13331089, 13332358, 'Y'],
       ['XLOC_030031', 'XLOC_030031', '-', ..., 15053270, 15053343, 'Y'],
       ['XLOC_030032', 'XLOC_030032', '-', ..., 59001259, 59003893, 'Y']],
      dtype=object)

In [8]:
df_np.shape

(30032, 18)

In [9]:
df_np[0]

array(['XLOC_000001', 'XLOC_000001', 'OR4F5', 'chr1:69090-70008',
       'hepg2_hr2', 'hepg2_hr3', 'NOTEST', 0.0, 0.0, 0.0, 0.0, 1.0, 1.0,
       'no', 'chr1', 69090, 70008, '1'], dtype=object)

In [10]:
output_path = os.path.join(WORKING_DIR, 'dataset', 'ensembl_by_test_id.csv')

i = 1
total = df_np.shape[0]

for item in df_np:

    if ((i % 100 == 0) or (i == total)):
        print(f"{i}/{total} - {item[0]}")
    
    result = query_ensembl_by_location(item)
    result.to_csv(output_path, mode='a', header=(not os.path.exists(output_path)), index=False)
    i += 1

100/30032 - XLOC_000100
200/30032 - XLOC_000200
300/30032 - XLOC_000300
400/30032 - XLOC_000400
500/30032 - XLOC_000500
600/30032 - XLOC_000600
700/30032 - XLOC_000700
800/30032 - XLOC_000800
900/30032 - XLOC_000900
1000/30032 - XLOC_001000
1100/30032 - XLOC_001100
1200/30032 - XLOC_001200
1300/30032 - XLOC_001300
1400/30032 - XLOC_001400
1500/30032 - XLOC_001500
1600/30032 - XLOC_001600
1700/30032 - XLOC_001700
1800/30032 - XLOC_001800
1900/30032 - XLOC_001900
2000/30032 - XLOC_002000
2100/30032 - XLOC_002100
2200/30032 - XLOC_002200
2300/30032 - XLOC_002300
2400/30032 - XLOC_002400
2500/30032 - XLOC_002500
2600/30032 - XLOC_002600
2700/30032 - XLOC_002700
2800/30032 - XLOC_002800
2900/30032 - XLOC_002900
3000/30032 - XLOC_003000
3100/30032 - XLOC_003100
3200/30032 - XLOC_003200
3300/30032 - XLOC_003300
3400/30032 - XLOC_003400
3500/30032 - XLOC_003500
3600/30032 - XLOC_003600
3700/30032 - XLOC_003700
3800/30032 - XLOC_003800
3900/30032 - XLOC_003900
4000/30032 - XLOC_004000
4100/30032 - XLOC_004100
4200/30032 - XLOC_004200
4300/30032 - XLOC_004300
4400/30032 - XLOC_004400
4500/30032 - XLOC_004500
4600/30032 - XLOC_004600
4700/30032 - XLOC_004700
4800/30032 - XLOC_004800
4900/30032 - XLOC_004900
5000/30032 - XLOC_005000
5100/30032 - XLOC_005100
5200/30032 - XLOC_005200
5300/30032 - XLOC_005300
5400/30032 - XLOC_005400
5500/30032 - XLOC_005500
5600/30032 - XLOC_005600
5700/30032 - XLOC_005700
5800/30032 - XLOC_005800
5900/30032 - XLOC_005900
6000/30032 - XLOC_006000
6100/30032 - XLOC_006100
6200/30032 - XLOC_006200
6300/30032 - XLOC_006300
6400/30032 - XLOC_006400
6500/30032 - XLOC_006500
6600/30032 - XLOC_006600
6700/30032 - XLOC_006700
6800/30032 - XLOC_006800
6900/30032 - XLOC_006900
7000/30032 - XLOC_007000
7100/30032 - XLOC_007100
7200/30032 - XLOC_007200
7300/30032 - XLOC_007300
7400/30032 - XLOC_007400
7500/30032 - XLOC_007500
7600/30032 - XLOC_007600
7700/30032 - XLOC_007700
7800/30032 - XLOC_007800
7900/30032 - XLOC_007900
8000/30032 - XLOC_008000
8100/30032 - XLOC_008100
8200/30032 - XLOC_008200
8300/30032 - XLOC_008300
8400/30032 - XLOC_008400
8500/30032 - XLOC_008500
8600/30032 - XLOC_008600
8700/30032 - XLOC_008700
8800/30032 - XLOC_008800
8900/30032 - XLOC_008900
9000/30032 - XLOC_009000
9100/30032 - XLOC_009100
9200/30032 - XLOC_009200
9300/30032 - XLOC_009300
9400/30032 - XLOC_009400
9500/30032 - XLOC_009500
9600/30032 - XLOC_009600
9700/30032 - XLOC_009700
9800/30032 - XLOC_009800
9900/30032 - XLOC_009900
10000/30032 - XLOC_010000
10100/30032 - XLOC_010100
10200/30032 - XLOC_010200
10300/30032 - XLOC_010300
10400/30032 - XLOC_010400
10500/30032 - XLOC_010500
10600/30032 - XLOC_010600
10700/30032 - XLOC_010700
10800/30032 - XLOC_010800
10900/30032 - XLOC_010900
11000/30032 - XLOC_011000
11100/30032 - XLOC_011100
11200/30032 - XLOC_011200
11300/30032 - XLOC_011300
11400/30032 - XLOC_011400
11500/30032 - XLOC_011500
11600/30032 - XLOC_011600
11700/30032 - XLOC_011700
11800/30032 - XLOC_011800
11900/30032 - XLOC_011900
12000/30032 - XLOC_012000
12100/30032 - XLOC_012100
12200/30032 - XLOC_012200
12300/30032 - XLOC_012300
12400/30032 - XLOC_012400
12500/30032 - XLOC_012500
12600/30032 - XLOC_012600
12700/30032 - XLOC_012700
12800/30032 - XLOC_012800
12900/30032 - XLOC_012900
13000/30032 - XLOC_013000
13100/30032 - XLOC_013100
13200/30032 - XLOC_013200
13300/30032 - XLOC_013300
13400/30032 - XLOC_013400
13500/30032 - XLOC_013500
13600/30032 - XLOC_013600
13700/30032 - XLOC_013700
13800/30032 - XLOC_013800
13900/30032 - XLOC_013900
14000/30032 - XLOC_014000
14100/30032 - XLOC_014100
14200/30032 - XLOC_014200
14300/30032 - XLOC_014300
14400/30032 - XLOC_014400
14500/30032 - XLOC_014500
14600/30032 - XLOC_014600
14700/30032 - XLOC_014700
14800/30032 - XLOC_014800
14900/30032 - XLOC_014900
15000/30032 - XLOC_015000
15100/30032 - XLOC_015100
15200/30032 - XLOC_015200
15300/30032 - XLOC_015300
15400/30032 - XLOC_015400
15500/30032 - XLOC_015500
15600/30032 - XLOC_015600
15700/30032 - XLOC_015700
15800/30032 - XLOC_015800
15900/30032 - XLOC_015900
16000/30032 - XLOC_016000
16100/30032 - XLOC_016100
16200/30032 - XLOC_016200
16300/30032 - XLOC_016300
16400/30032 - XLOC_016400
16500/30032 - XLOC_016500
16600/30032 - XLOC_016600
16700/30032 - XLOC_016700
16800/30032 - XLOC_016800
16900/30032 - XLOC_016900
17000/30032 - XLOC_017000
17100/30032 - XLOC_017100
17200/30032 - XLOC_017200
17300/30032 - XLOC_017300
17400/30032 - XLOC_017400
17500/30032 - XLOC_017500
17600/30032 - XLOC_017600
17700/30032 - XLOC_017700
17800/30032 - XLOC_017800
17900/30032 - XLOC_017900
18000/30032 - XLOC_018000
18100/30032 - XLOC_018100
18200/30032 - XLOC_018200
18300/30032 - XLOC_018300
18400/30032 - XLOC_018400
18500/30032 - XLOC_018500
18600/30032 - XLOC_018600
18700/30032 - XLOC_018700
18800/30032 - XLOC_018800
18900/30032 - XLOC_018900
19000/30032 - XLOC_019000
19100/30032 - XLOC_019100
19200/30032 - XLOC_019200
19300/30032 - XLOC_019300
19400/30032 - XLOC_019400
19500/30032 - XLOC_019500
19600/30032 - XLOC_019600
19700/30032 - XLOC_019700
19800/30032 - XLOC_019800
19900/30032 - XLOC_019900
20000/30032 - XLOC_020000
20100/30032 - XLOC_020100
20200/30032 - XLOC_020200
20300/30032 - XLOC_020300
20400/30032 - XLOC_020400
20500/30032 - XLOC_020500
20600/30032 - XLOC_020600
20700/30032 - XLOC_020700
20800/30032 - XLOC_020800
20900/30032 - XLOC_020900
21000/30032 - XLOC_021000
21100/30032 - XLOC_021100
21200/30032 - XLOC_021200
21300/30032 - XLOC_021300
21400/30032 - XLOC_021400
21500/30032 - XLOC_021500
21600/30032 - XLOC_021600
21700/30032 - XLOC_021700
21800/30032 - XLOC_021800
21900/30032 - XLOC_021900
22000/30032 - XLOC_022000
22100/30032 - XLOC_022100
22200/30032 - XLOC_022200
22300/30032 - XLOC_022300
22400/30032 - XLOC_022400
22500/30032 - XLOC_022500
22600/30032 - XLOC_022600
22700/30032 - XLOC_022700
22800/30032 - XLOC_022800
22900/30032 - XLOC_022900
23000/30032 - XLOC_023000
23100/30032 - XLOC_023100
23200/30032 - XLOC_023200
23300/30032 - XLOC_023300
23400/30032 - XLOC_023400
23500/30032 - XLOC_023500
23600/30032 - XLOC_023600
23700/30032 - XLOC_023700
23800/30032 - XLOC_023800
23900/30032 - XLOC_023900
24000/30032 - XLOC_024000
24100/30032 - XLOC_024100
24200/30032 - XLOC_024200
24300/30032 - XLOC_024300
24400/30032 - XLOC_024400
24500/30032 - XLOC_024500
24600/30032 - XLOC_024600
24700/30032 - XLOC_024700
24800/30032 - XLOC_024800
24900/30032 - XLOC_024900
25000/30032 - XLOC_025000
25100/30032 - XLOC_025100
25200/30032 - XLOC_025200
25300/30032 - XLOC_025300
25400/30032 - XLOC_025400
25500/30032 - XLOC_025500
25600/30032 - XLOC_025600
25700/30032 - XLOC_025700
25800/30032 - XLOC_025800
25900/30032 - XLOC_025900
26000/30032 - XLOC_026000
26100/30032 - XLOC_026100
26200/30032 - XLOC_026200
26300/30032 - XLOC_026300
26400/30032 - XLOC_026400
26500/30032 - XLOC_026500
26600/30032 - XLOC_026600
26700/30032 - XLOC_026700
26800/30032 - XLOC_026800
26900/30032 - XLOC_026900
27000/30032 - XLOC_027000
27100/30032 - XLOC_027100
27200/30032 - XLOC_027200
27300/30032 - XLOC_027300
27400/30032 - XLOC_027400
27500/30032 - XLOC_027500
27600/30032 - XLOC_027600
27700/30032 - XLOC_027700
27800/30032 - XLOC_027800
27900/30032 - XLOC_027900
28000/30032 - XLOC_028000
28100/30032 - XLOC_028100
28200/30032 - XLOC_028200
28300/30032 - XLOC_028300
28400/30032 - XLOC_028400
28500/30032 - XLOC_028500
28600/30032 - XLOC_028600
28700/30032 - XLOC_028700
28800/30032 - XLOC_028800
28900/30032 - XLOC_028900
29000/30032 - XLOC_029000
29100/30032 - XLOC_029100
29200/30032 - XLOC_029200
29300/30032 - XLOC_029300
29400/30032 - XLOC_029400
29500/30032 - XLOC_029500
29600/30032 - XLOC_029600
29700/30032 - XLOC_029700
29800/30032 - XLOC_029800
29900/30032 - XLOC_029900
30000/30032 - XLOC_030000
30032/30032 - XLOC_030032

In [11]:
schema = pl.Schema({
    "Chromosome/scaffold name"  : pl.String(),
    "Gene start (bp)"           : pl.Int64(),
    "Gene end (bp)"             : pl.Int64(),
    "Strand"                    : pl.Int64(),
    "Gene name"                 : pl.String(),
    "Gene stable ID"            : pl.String(),
    "Gene type"                 : pl.String(),
    "tss"                       : pl.Int64(),
    "tss -2kb"                  : pl.Int64(),
    "tss +2kb"                  : pl.Int64(),
    "test_id"                   : pl.String(),
    "gene_id"                   : pl.String(),
    "locus"                     : pl.String(),
    "chromosome"                : pl.String(),
    "orig_start"                : pl.Int64(),
    "orig_end"                  : pl.Int64(),
})

In [12]:
ensembl_df = pl.read_csv(os.path.join(WORKING_DIR, "dataset", "ensembl_by_gen_id.csv"), schema=schema)

In [13]:
ensembl_df

shape: (72_827, 16)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Chromosome ┆ Gene start ┆ Gene end   ┆ Strand ┆ … ┆ locus     ┆ chromosom ┆ orig_star ┆ orig_end │
│ /scaffold  ┆ (bp)       ┆ (bp)       ┆ ---    ┆   ┆ ---       ┆ e         ┆ t         ┆ ---      │
│ name       ┆ ---        ┆ ---        ┆ i64    ┆   ┆ str       ┆ ---       ┆ ---       ┆ i64      │
│ ---        ┆ i64        ┆ i64        ┆        ┆   ┆           ┆ str       ┆ i64       ┆          │
│ str        ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆          │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1          ┆ 69091      ┆ 70008      ┆ 1      ┆ … ┆ chr1:6909 ┆ chr1      ┆ 69090     ┆ 70008    │
│            ┆            ┆            ┆        ┆   ┆ 0-70008   ┆           ┆           ┆          │
│ 1          ┆ 317720     ┆ 453948     ┆ 1      ┆ … ┆ chr1:3238 ┆ chr1      ┆ 323891    ┆ 328581   │
│            ┆            ┆            ┆        ┆   ┆ 91-328581 ┆           ┆           ┆          │
│ 1          ┆ 326096     ┆ 328112     ┆ 1      ┆ … ┆ chr1:3238 ┆ chr1      ┆ 323891    ┆ 328581   │
│            ┆            ┆            ┆        ┆   ┆ 91-328581 ┆           ┆           ┆          │
│ 1          ┆ 317720     ┆ 453948     ┆ 1      ┆ … ┆ chr1:3676 ┆ chr1      ┆ 367658    ┆ 368597   │
│            ┆            ┆            ┆        ┆   ┆ 58-368597 ┆           ┆           ┆          │
│ 1          ┆ 367640     ┆ 368634     ┆ 1      ┆ … ┆ chr1:3676 ┆ chr1      ┆ 367658    ┆ 368597   │
│            ┆            ┆            ┆        ┆   ┆ 58-368597 ┆           ┆           ┆          │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Y          ┆ 27209230   ┆ 27246039   ┆ -1     ┆ … ┆ chrY:2720 ┆ chrY      ┆ 27209229  ┆ 27246039 │
│            ┆            ┆            ┆        ┆   ┆ 9229-2724 ┆           ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆ 6039      ┆           ┆           ┆          │
│ Y          ┆ 27329790   ┆ 27330920   ┆ -1     ┆ … ┆ chrY:2732 ┆ chrY      ┆ 27329789  ┆ 27330920 │
│            ┆            ┆            ┆        ┆   ┆ 9789-2733 ┆           ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆ 0920      ┆           ┆           ┆          │
│ Y          ┆ 10037764   ┆ 10037915   ┆ 1      ┆ … ┆ chrY:1003 ┆ chrY      ┆ 10037791  ┆ 10037910 │
│            ┆            ┆            ┆        ┆   ┆ 7791-1003 ┆           ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆ 7910      ┆           ┆           ┆          │
│ Y          ┆ 15042075   ┆ 15060090   ┆ -1     ┆ … ┆ chrY:1505 ┆ chrY      ┆ 15053270  ┆ 15053343 │
│            ┆            ┆            ┆        ┆   ┆ 3270-1505 ┆           ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆ 3343      ┆           ┆           ┆          │
│ Y          ┆ 59001391   ┆ 59001635   ┆ 1      ┆ … ┆ chrY:5900 ┆ chrY      ┆ 59001259  ┆ 59003893 │
│            ┆            ┆            ┆        ┆   ┆ 1259-5900 ┆           ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆ 3893      ┆           ┆           ┆          │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
ensembl_df.select(pl.col('gene_id').n_unique())

shape: (1, 1)
┌─────────┐
│ gene_id │
│ ---     │
│ u32     │
╞═════════╡
│ 25929   │
└─────────┘

In [15]:
# Filter only the 'protein_coding' gene
pc_df = ensembl_df.filter(pl.col('Gene type') == 'protein_coding')

In [16]:
pc_df

shape: (35_903, 16)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Chromosome ┆ Gene start ┆ Gene end   ┆ Strand ┆ … ┆ locus     ┆ chromosom ┆ orig_star ┆ orig_end │
│ /scaffold  ┆ (bp)       ┆ (bp)       ┆ ---    ┆   ┆ ---       ┆ e         ┆ t         ┆ ---      │
│ name       ┆ ---        ┆ ---        ┆ i64    ┆   ┆ str       ┆ ---       ┆ ---       ┆ i64      │
│ ---        ┆ i64        ┆ i64        ┆        ┆   ┆           ┆ str       ┆ i64       ┆          │
│ str        ┆            ┆            ┆        ┆   ┆           ┆           ┆           ┆          │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1          ┆ 69091      ┆ 70008      ┆ 1      ┆ … ┆ chr1:6909 ┆ chr1      ┆ 69090     ┆ 70008    │
│            ┆            ┆            ┆        ┆   ┆ 0-70008   ┆           ┆           ┆          │
│ 1          ┆ 367640     ┆ 368634     ┆ 1      ┆ … ┆ chr1:3676 ┆ chr1      ┆ 367658    ┆ 368597   │
│            ┆            ┆            ┆        ┆   ┆ 58-368597 ┆           ┆           ┆          │
│ 1          ┆ 860260     ┆ 879955     ┆ 1      ┆ … ┆ chr1:8511 ┆ chr1      ┆ 851135    ┆ 917473   │
│            ┆            ┆            ┆        ┆   ┆ 35-917473 ┆           ┆           ┆          │
│ 1          ┆ 861264     ┆ 866445     ┆ -1     ┆ … ┆ chr1:8511 ┆ chr1      ┆ 851135    ┆ 917473   │
│            ┆            ┆            ┆        ┆   ┆ 35-917473 ┆           ┆           ┆          │
│ 1          ┆ 879584     ┆ 894689     ┆ -1     ┆ … ┆ chr1:8511 ┆ chr1      ┆ 851135    ┆ 917473   │
│            ┆            ┆            ┆        ┆   ┆ 35-917473 ┆           ┆           ┆          │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Y          ┆ 24314689   ┆ 24329129   ┆ -1     ┆ … ┆ chrY:2431 ┆ chrY      ┆ 24314688  ┆ 24329089 │
│            ┆            ┆            ┆        ┆   ┆ 4688-2432 ┆           ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆ 9089      ┆           ┆           ┆          │
│ Y          ┆ 25275502   ┆ 25345241   ┆ -1     ┆ … ┆ chrY:2527 ┆ chrY      ┆ 25275501  ┆ 25345239 │
│            ┆            ┆            ┆        ┆   ┆ 5501-2534 ┆           ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆ 5239      ┆           ┆           ┆          │
│ Y          ┆ 26191376   ┆ 26194166   ┆ -1     ┆ … ┆ chrY:2619 ┆ chrY      ┆ 26191376  ┆ 26194161 │
│            ┆            ┆            ┆        ┆   ┆ 1376-2619 ┆           ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆ 4161      ┆           ┆           ┆          │
│ Y          ┆ 26909216   ┆ 26959626   ┆ -1     ┆ … ┆ chrY:2690 ┆ chrY      ┆ 26909221  ┆ 26959517 │
│            ┆            ┆            ┆        ┆   ┆ 9221-2695 ┆           ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆ 9517      ┆           ┆           ┆          │
│ Y          ┆ 27177048   ┆ 27208695   ┆ -1     ┆ … ┆ chrY:2717 ┆ chrY      ┆ 27177049  ┆ 27198251 │
│            ┆            ┆            ┆        ┆   ┆ 7049-2719 ┆           ┆           ┆          │
│            ┆            ┆            ┆        ┆   ┆ 8251      ┆           ┆           ┆          │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [17]:
# Select top 1
pc_top1_df = pc_df.group_by("gene_id", maintain_order=True).agg(pl.all().first())

In [18]:
pc_top1_df.shape

(22154, 16)

In [19]:
pc_top1_df

shape: (22_154, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gene_id   ┆ Chromosom ┆ Gene      ┆ Gene end  ┆ … ┆ locus     ┆ chromosom ┆ orig_star ┆ orig_end │
│ ---       ┆ e/scaffol ┆ start     ┆ (bp)      ┆   ┆ ---       ┆ e         ┆ t         ┆ ---      │
│ str       ┆ d name    ┆ (bp)      ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ i64      │
│           ┆ ---       ┆ ---       ┆ i64       ┆   ┆           ┆ str       ┆ i64       ┆          │
│           ┆ str       ┆ i64       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ XLOC_0000 ┆ 1         ┆ 69091     ┆ 70008     ┆ … ┆ chr1:6909 ┆ chr1      ┆ 69090     ┆ 70008    │
│ 01        ┆           ┆           ┆           ┆   ┆ 0-70008   ┆           ┆           ┆          │
│ XLOC_0000 ┆ 1         ┆ 367640    ┆ 368634    ┆ … ┆ chr1:3676 ┆ chr1      ┆ 367658    ┆ 368597   │
│ 03        ┆           ┆           ┆           ┆   ┆ 58-368597 ┆           ┆           ┆          │
│ XLOC_0000 ┆ 1         ┆ 860260    ┆ 879955    ┆ … ┆ chr1:8511 ┆ chr1      ┆ 851135    ┆ 917473   │
│ 06        ┆           ┆           ┆           ┆   ┆ 35-917473 ┆           ┆           ┆          │
│ XLOC_0000 ┆ 1         ┆ 860260    ┆ 879955    ┆ … ┆ chr1:8511 ┆ chr1      ┆ 851135    ┆ 917473   │
│ 07        ┆           ┆           ┆           ┆   ┆ 35-917473 ┆           ┆           ┆          │
│ XLOC_0000 ┆ 1         ┆ 948803    ┆ 949920    ┆ … ┆ chr1:9488 ┆ chr1      ┆ 948846    ┆ 949919   │
│ 08        ┆           ┆           ┆           ┆   ┆ 46-949919 ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ XLOC_0300 ┆ Y         ┆ 24314689  ┆ 24329129  ┆ … ┆ chrY:2431 ┆ chrY      ┆ 24314688  ┆ 24329089 │
│ 09        ┆           ┆           ┆           ┆   ┆ 4688-2432 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 9089      ┆           ┆           ┆          │
│ XLOC_0300 ┆ Y         ┆ 25275502  ┆ 25345241  ┆ … ┆ chrY:2527 ┆ chrY      ┆ 25275501  ┆ 25345239 │
│ 12        ┆           ┆           ┆           ┆   ┆ 5501-2534 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 5239      ┆           ┆           ┆          │
│ XLOC_0300 ┆ Y         ┆ 26191376  ┆ 26194166  ┆ … ┆ chrY:2619 ┆ chrY      ┆ 26191376  ┆ 26194161 │
│ 14        ┆           ┆           ┆           ┆   ┆ 1376-2619 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 4161      ┆           ┆           ┆          │
│ XLOC_0300 ┆ Y         ┆ 26909216  ┆ 26959626  ┆ … ┆ chrY:2690 ┆ chrY      ┆ 26909221  ┆ 26959517 │
│ 17        ┆           ┆           ┆           ┆   ┆ 9221-2695 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 9517      ┆           ┆           ┆          │
│ XLOC_0300 ┆ Y         ┆ 27177048  ┆ 27208695  ┆ … ┆ chrY:2717 ┆ chrY      ┆ 27177049  ┆ 27198251 │
│ 18        ┆           ┆           ┆           ┆   ┆ 7049-2719 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 8251      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
pc_top1_df.columns

['gene_id',
 'Chromosome/scaffold name',
 'Gene start (bp)',
 'Gene end (bp)',
 'Strand',
 'Gene name',
 'Gene stable ID',
 'Gene type',
 'tss',
 'tss -2kb',
 'tss +2kb',
 'test_id',
 'locus',
 'chromosome',
 'orig_start',
 'orig_end']

In [26]:
# Reorder the column
ordered_cols = ['chromosome', 'tss -2kb', 'tss +2kb', 'test_id', 'gene_id',
                'Chromosome/scaffold name', 'Gene start (bp)', 'Gene end (bp)', 
                'Strand', 'Gene name', 'Gene stable ID', 'Gene type', 'tss', 
                'locus', 'orig_start', 'orig_end']

In [22]:
pc_top1_df = pc_top1_df.select(ordered_cols)

In [23]:
pc_top1_df

shape: (22_154, 16)
┌────────────┬──────────┬──────────┬────────────┬───┬──────────┬────────────┬───────────┬──────────┐
│ chromosome ┆ tss -2kb ┆ tss +2kb ┆ gene_id    ┆ … ┆ tss      ┆ locus      ┆ orig_star ┆ orig_end │
│ ---        ┆ ---      ┆ ---      ┆ ---        ┆   ┆ ---      ┆ ---        ┆ t         ┆ ---      │
│ str        ┆ i64      ┆ i64      ┆ str        ┆   ┆ i64      ┆ str        ┆ ---       ┆ i64      │
│            ┆          ┆          ┆            ┆   ┆          ┆            ┆ i64       ┆          │
╞════════════╪══════════╪══════════╪════════════╪═══╪══════════╪════════════╪═══════════╪══════════╡
│ chr1       ┆ 67091    ┆ 71091    ┆ XLOC_00000 ┆ … ┆ 69091    ┆ chr1:69090 ┆ 69090     ┆ 70008    │
│            ┆          ┆          ┆ 1          ┆   ┆          ┆ -70008     ┆           ┆          │
│ chr1       ┆ 365640   ┆ 369640   ┆ XLOC_00000 ┆ … ┆ 367640   ┆ chr1:36765 ┆ 367658    ┆ 368597   │
│            ┆          ┆          ┆ 3          ┆   ┆          ┆ 8-368597   ┆           ┆          │
│ chr1       ┆ 858260   ┆ 862260   ┆ XLOC_00000 ┆ … ┆ 860260   ┆ chr1:85113 ┆ 851135    ┆ 917473   │
│            ┆          ┆          ┆ 6          ┆   ┆          ┆ 5-917473   ┆           ┆          │
│ chr1       ┆ 858260   ┆ 862260   ┆ XLOC_00000 ┆ … ┆ 860260   ┆ chr1:85113 ┆ 851135    ┆ 917473   │
│            ┆          ┆          ┆ 7          ┆   ┆          ┆ 5-917473   ┆           ┆          │
│ chr1       ┆ 946803   ┆ 950803   ┆ XLOC_00000 ┆ … ┆ 948803   ┆ chr1:94884 ┆ 948846    ┆ 949919   │
│            ┆          ┆          ┆ 8          ┆   ┆          ┆ 6-949919   ┆           ┆          │
│ …          ┆ …        ┆ …        ┆ …          ┆ … ┆ …        ┆ …          ┆ …         ┆ …        │
│ chrY       ┆ 24327129 ┆ 24331129 ┆ XLOC_03000 ┆ … ┆ 24329129 ┆ chrY:24314 ┆ 24314688  ┆ 24329089 │
│            ┆          ┆          ┆ 9          ┆   ┆          ┆ 688-243290 ┆           ┆          │
│            ┆          ┆          ┆            ┆   ┆          ┆ 89         ┆           ┆          │
│ chrY       ┆ 25343241 ┆ 25347241 ┆ XLOC_03001 ┆ … ┆ 25345241 ┆ chrY:25275 ┆ 25275501  ┆ 25345239 │
│            ┆          ┆          ┆ 2          ┆   ┆          ┆ 501-253452 ┆           ┆          │
│            ┆          ┆          ┆            ┆   ┆          ┆ 39         ┆           ┆          │
│ chrY       ┆ 26192166 ┆ 26196166 ┆ XLOC_03001 ┆ … ┆ 26194166 ┆ chrY:26191 ┆ 26191376  ┆ 26194161 │
│            ┆          ┆          ┆ 4          ┆   ┆          ┆ 376-261941 ┆           ┆          │
│            ┆          ┆          ┆            ┆   ┆          ┆ 61         ┆           ┆          │
│ chrY       ┆ 26957626 ┆ 26961626 ┆ XLOC_03001 ┆ … ┆ 26959626 ┆ chrY:26909 ┆ 26909221  ┆ 26959517 │
│            ┆          ┆          ┆ 7          ┆   ┆          ┆ 221-269595 ┆           ┆          │
│            ┆          ┆          ┆            ┆   ┆          ┆ 17         ┆           ┆          │
│ chrY       ┆ 27206695 ┆ 27210695 ┆ XLOC_03001 ┆ … ┆ 27208695 ┆ chrY:27177 ┆ 27177049  ┆ 27198251 │
│            ┆          ┆          ┆ 8          ┆   ┆          ┆ 049-271982 ┆           ┆          │
│            ┆          ┆          ┆            ┆   ┆          ┆ 51         ┆           ┆          │
└────────────┴──────────┴──────────┴────────────┴───┴──────────┴────────────┴───────────┴──────────┘

In [24]:
pc_top1_df.write_csv(os.path.join(WORKING_DIR, "dataset", "ensembl_top1.csv"), include_header=False, separator="\t")

In [27]:
pc_top1_df.head(100).write_csv(os.path.join(WORKING_DIR, "dataset", "ensembl_100.csv"), include_header=False, separator="\t")