In [25]:
import os
import glob

import numpy as np
import polars as pl
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, roc_curve, auc

In [2]:
WORKING_DIR = '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2/'

In [4]:
# Check CUDA device
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda device

In [6]:
# Load dataset
gene_pl = pl.read_parquet(os.path.join(WORKING_DIR, 'dataset', 'gene_w_label_value_1.parquet'))
gene_pl

shape: (22_154, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ gene_id    ┆ H3K4me3    ┆ H3K4me3_co ┆ H3K9ac    ┆ … ┆ H3K27me3  ┆ H3K27me3_ ┆ value_1   ┆ label │
│ ---        ┆ ---        ┆ unt        ┆ ---       ┆   ┆ ---       ┆ count     ┆ ---       ┆ ---   │
│ str        ┆ list[f64]  ┆ ---        ┆ list[f64] ┆   ┆ list[f64] ┆ ---       ┆ f64       ┆ i32   │
│            ┆            ┆ i64        ┆           ┆   ┆           ┆ i64       ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 1          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 3          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0888452 ┆ 0     │
│ 6          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 4.04743   ┆ 1     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_00000 ┆ [0.0, 0.0, ┆ 6          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 26.7934   ┆ 1     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …     │
│ XLOC_03000 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 9          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 2          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 4          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 7          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
│ XLOC_03001 ┆ [0.0, 0.0, ┆ 0          ┆ [0.0,     ┆ … ┆ [0.0,     ┆ 0         ┆ 0.0       ┆ 0     │
│ 8          ┆ … 0.0]     ┆            ┆ 0.0, …    ┆   ┆ 0.0, …    ┆           ┆           ┆       │
│            ┆            ┆            ┆ 0.0]      ┆   ┆ 0.0]      ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

In [10]:
# Load permutation list
permutations = pl.read_parquet('permutation.parquet')['markers_perm'].to_list()
len(permutations)

325

In [12]:
item = permutations[100]
item_name = '-'.join(item)
print(item)
print(item_name)

['H3K9me3', 'H3K9ac', 'H3K27ac', 'H3K4me3']
H3K9me3-H3K9ac-H3K27ac-H3K4me3

In [13]:
# Create dataframe based on histone marker permutation item
gene_perm_pl = gene_pl.with_columns(
    pl.struct(item).map_elements(
        lambda x: [x[col_name] for col_name in item],
        return_dtype = pl.List(pl.List(pl.Float64))
    )
    .alias('histone')
)

In [15]:
# Select X and y column
X = gene_perm_pl.select(pl.col('histone')).to_series().to_list()
y = gene_perm_pl.select(pl.col('label')).to_series().to_list()

In [16]:
# Convert to Numpy array
X = np.array(X)
y = np.array(y)

In [17]:
# Split the dataset into training, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.666, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

In [18]:
print("Train set shape:", X_train.shape, y_train.shape)
print("Validation set shape:", X_val.shape, y_val.shape)
print("Test set shape:", X_test.shape, y_test.shape)

Train set shape: (7399, 4, 4000) (7399,)
Validation set shape: (7377, 4, 4000) (7377,)
Test set shape: (7378, 4, 4000) (7378,)

In [19]:
# Convert numpy arrays to PyTorch tensors
X_train = torch.from_numpy(X_train).float().unsqueeze(1).to(device)
X_val = torch.from_numpy(X_val).float().unsqueeze(1).to(device)
X_test = torch.from_numpy(X_test).float().unsqueeze(1).to(device)

y_train = torch.from_numpy(y_train).float().to(device)
y_val = torch.from_numpy(y_val).float().to(device)
y_test = torch.from_numpy(y_test).float().to(device)

In [20]:
# Create DataLoaders
batch_size = 32

train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

val_dataset = TensorDataset(X_val, y_val)
val_loader = DataLoader(val_dataset, batch_size=batch_size)

test_dataset = TensorDataset(X_test, y_test)
test_loader = DataLoader(test_dataset, batch_size=batch_size)

In [21]:
# Define DeepClassifer Class
class DeepClassifier(nn.Module):
    def __init__(self, input_dim = [5, 4000], out_channels = 50, conv_kernel_size = 10, max_pooling_kernel_size = 5):
        super(DeepClassifier, self).__init__()
        
        flatten_dim = out_channels * ((input_dim[1] - conv_kernel_size + 1) // max_pooling_kernel_size)

        self.conv = nn.Conv2d(1, out_channels, kernel_size=(input_dim[0], conv_kernel_size))
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d((1, max_pooling_kernel_size))
        self.dropout = nn.Dropout(0.5)
        self.flatten = nn.Flatten()
        self.linear1 = nn.Linear(flatten_dim, 625)
        self.linear2 = nn.Linear(625, 125)
        self.linear3 = nn.Linear(125, 2)
        self.softmax = nn.LogSoftmax(dim=1)
        

    def forward(self, x):
        # Stage 1: filter bank -> squashing -> max pooling
        x = self.conv(x)
        x = self.relu(x)
        x = self.pool(x)

        # Stage 2: standar 2-layer neural network        
        x = self.flatten(x)
        x = self.dropout(x)
        x = self.linear1(x)
        x = self.relu(x)
        x = self.linear2(x)
        x = self.relu(x)
        x = self.linear3(x)
        x = self.softmax(x)
        return x

In [22]:
# Find the feature's number of row from histone permutation item
n_rows_item = len(item)
print(n_rows_item)

4

In [28]:
# Initialize the model
model = DeepClassifier(input_dim = [n_rows_item, 4000]).to(device)
criterion = nn.NLLLoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)
num_epochs = 100

# For tracking train and validation
train_losses, val_losses = [], []
train_accuracies, val_accuracies = [], []
train_aucs, val_aucs = [], []

# For saving the best model
best_val_metric = float('-inf')
best_model_path = os.path.join(WORKING_DIR, "experiments", "model", f'{item_name}.pth')

In [52]:
# Preparing the output dataframe
output_df = pd.DataFrame(columns=[
    "item_name",
    "train_loss_min", "train_loss_avg", "train_loss_max",
    "train_acc_min", "train_acc_avg", "train_acc_max",
    "train_auc_min", "train_auc_avg", "train_auc_max",
    "val_loss_min", "val_loss_avg", "val_loss_max",
    "val_acc_min", "val_acc_avg", "val_acc_max",
    "val_auc_min", "val_auc_avg", "val_auc_max",
])

In [30]:
# Run the training and validation phase
for epoch in range(num_epochs):
    # Training phase
    model.train()  # Set the model to training mode
    train_loss = 0.0
    train_correct = 0
    train_total = 0
    train_true_labels = []
    train_predicted_probs = []
    
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs.cuda(), labels.type(torch.LongTensor).cuda())
        loss.backward()
        optimizer.step()
        train_loss += loss.item()

        _, predicted = torch.max(outputs.data, 1)
        train_total += labels.size(0)
        train_correct += (predicted == labels).sum().item()

        train_true_labels.extend(labels.cpu().numpy())
        train_predicted_probs.extend(predicted.cpu().numpy())
    
    avg_train_loss = train_loss / len(train_loader)
    train_accuracy = 100 * train_correct / train_total
    train_auc_score = roc_auc_score(train_true_labels, train_predicted_probs)
    
    train_losses.append(round(avg_train_loss, 4))
    train_accuracies.append(round(train_accuracy, 2))
    train_aucs.append(round(train_auc_score, 2))
    
    # Validation phase
    model.eval()  # Set the model to evaluation mode
    val_loss = 0.0
    val_correct = 0
    val_total = 0
    val_metric = 0
    val_true_labels = []
    val_predicted_probs = []
    
    with torch.no_grad():  # Disable gradient computation
        for inputs, labels in val_loader:
            outputs = model(inputs)
            loss = criterion(outputs.cuda(), labels.type(torch.LongTensor).cuda())
            val_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            val_total += labels.size(0)
            val_correct += (predicted == labels).sum().item()

            val_true_labels.extend(labels.cpu().numpy())
            val_predicted_probs.extend(predicted.cpu().numpy())

    avg_val_loss = val_loss / len(val_loader)
    val_accuracy = 100 * val_correct / val_total
    val_metric = val_correct / len(val_loader)

    # Save the best model
    if val_metric > best_val_metric:
        best_val_metric = val_metric
        torch.save(model.state_dict(), best_model_path)
        print(f"New best model saved with validation metric: {best_val_metric:.4f}")
    
    val_true_labels = np.array(val_true_labels)
    val_predicted_probs = np.array(val_predicted_probs)
    val_auc_score = roc_auc_score(val_true_labels, val_predicted_probs)

    val_losses.append(round(avg_val_loss, 4))
    val_accuracies.append(round(val_accuracy, 2))
    val_aucs.append(round(val_auc_score, 2))
    
    print(f'Epoch [{epoch+1}/{num_epochs}] - '
          f'[TRAIN] Loss: {avg_train_loss:.4f}, Accuracy: {train_accuracy:.2f}%, AUC: {train_auc_score:.2f} - '
          f'[VAL] Loss: {avg_val_loss:.4f}, Accuracy: {val_accuracy:.2f}%, AUC: {val_auc_score:.2f}')
print("Training finished!")

New best model saved with validation metric: 19.4242
Epoch [1/100] - [TRAIN] Loss: 0.6457, Accuracy: 61.21%, AUC: 0.53 - [VAL] Loss: 0.6005, Accuracy: 60.82%, AUC: 0.50
Epoch [2/100] - [TRAIN] Loss: 0.5837, Accuracy: 60.82%, AUC: 0.50 - [VAL] Loss: 0.5662, Accuracy: 60.82%, AUC: 0.50
New best model saved with validation metric: 24.7749
Epoch [3/100] - [TRAIN] Loss: 0.5595, Accuracy: 66.41%, AUC: 0.58 - [VAL] Loss: 0.5478, Accuracy: 77.58%, AUC: 0.76
New best model saved with validation metric: 24.9827
Epoch [4/100] - [TRAIN] Loss: 0.5462, Accuracy: 78.09%, AUC: 0.76 - [VAL] Loss: 0.5372, Accuracy: 78.23%, AUC: 0.77
New best model saved with validation metric: 25.0303
Epoch [5/100] - [TRAIN] Loss: 0.5376, Accuracy: 78.50%, AUC: 0.77 - [VAL] Loss: 0.5315, Accuracy: 78.38%, AUC: 0.78
Epoch [6/100] - [TRAIN] Loss: 0.5342, Accuracy: 78.61%, AUC: 0.78 - [VAL] Loss: 0.5274, Accuracy: 78.11%, AUC: 0.78
Epoch [7/100] - [TRAIN] Loss: 0.5287, Accuracy: 78.47%, AUC: 0.78 - [VAL] Loss: 0.5239, Accuracy: 78.23%, AUC: 0.78
Epoch [8/100] - [TRAIN] Loss: 0.5251, Accuracy: 78.36%, AUC: 0.78 - [VAL] Loss: 0.5205, Accuracy: 78.26%, AUC: 0.78
Epoch [9/100] - [TRAIN] Loss: 0.5231, Accuracy: 78.38%, AUC: 0.78 - [VAL] Loss: 0.5183, Accuracy: 77.97%, AUC: 0.78
Epoch [10/100] - [TRAIN] Loss: 0.5187, Accuracy: 78.32%, AUC: 0.78 - [VAL] Loss: 0.5156, Accuracy: 77.97%, AUC: 0.78
Epoch [11/100] - [TRAIN] Loss: 0.5157, Accuracy: 78.33%, AUC: 0.78 - [VAL] Loss: 0.5136, Accuracy: 77.88%, AUC: 0.78
Epoch [12/100] - [TRAIN] Loss: 0.5140, Accuracy: 78.21%, AUC: 0.78 - [VAL] Loss: 0.5122, Accuracy: 77.71%, AUC: 0.78
Epoch [13/100] - [TRAIN] Loss: 0.5127, Accuracy: 78.28%, AUC: 0.78 - [VAL] Loss: 0.5112, Accuracy: 77.71%, AUC: 0.78
Epoch [14/100] - [TRAIN] Loss: 0.5111, Accuracy: 78.28%, AUC: 0.78 - [VAL] Loss: 0.5098, Accuracy: 77.81%, AUC: 0.78
Epoch [15/100] - [TRAIN] Loss: 0.5087, Accuracy: 78.29%, AUC: 0.78 - [VAL] Loss: 0.5085, Accuracy: 77.84%, AUC: 0.78
Epoch [16/100] - [TRAIN] Loss: 0.5082, Accuracy: 78.29%, AUC: 0.78 - [VAL] Loss: 0.5076, Accuracy: 78.00%, AUC: 0.78
Epoch [17/100] - [TRAIN] Loss: 0.5068, Accuracy: 78.24%, AUC: 0.78 - [VAL] Loss: 0.5067, Accuracy: 78.08%, AUC: 0.78
Epoch [18/100] - [TRAIN] Loss: 0.5076, Accuracy: 78.54%, AUC: 0.78 - [VAL] Loss: 0.5066, Accuracy: 78.00%, AUC: 0.78
Epoch [19/100] - [TRAIN] Loss: 0.5053, Accuracy: 78.32%, AUC: 0.78 - [VAL] Loss: 0.5055, Accuracy: 78.13%, AUC: 0.78
Epoch [20/100] - [TRAIN] Loss: 0.5039, Accuracy: 78.46%, AUC: 0.78 - [VAL] Loss: 0.5049, Accuracy: 78.16%, AUC: 0.78
Epoch [21/100] - [TRAIN] Loss: 0.5035, Accuracy: 78.48%, AUC: 0.78 - [VAL] Loss: 0.5045, Accuracy: 78.15%, AUC: 0.78
Epoch [22/100] - [TRAIN] Loss: 0.5020, Accuracy: 78.51%, AUC: 0.78 - [VAL] Loss: 0.5048, Accuracy: 78.05%, AUC: 0.78
Epoch [23/100] - [TRAIN] Loss: 0.5016, Accuracy: 78.47%, AUC: 0.78 - [VAL] Loss: 0.5036, Accuracy: 78.26%, AUC: 0.78
Epoch [24/100] - [TRAIN] Loss: 0.5008, Accuracy: 78.50%, AUC: 0.78 - [VAL] Loss: 0.5031, Accuracy: 78.28%, AUC: 0.78
Epoch [25/100] - [TRAIN] Loss: 0.5007, Accuracy: 78.65%, AUC: 0.78 - [VAL] Loss: 0.5030, Accuracy: 78.30%, AUC: 0.78
Epoch [26/100] - [TRAIN] Loss: 0.5017, Accuracy: 78.59%, AUC: 0.78 - [VAL] Loss: 0.5022, Accuracy: 78.35%, AUC: 0.78
Epoch [27/100] - [TRAIN] Loss: 0.4985, Accuracy: 78.77%, AUC: 0.78 - [VAL] Loss: 0.5021, Accuracy: 78.27%, AUC: 0.78
Epoch [28/100] - [TRAIN] Loss: 0.4981, Accuracy: 78.65%, AUC: 0.78 - [VAL] Loss: 0.5015, Accuracy: 78.32%, AUC: 0.78
Epoch [29/100] - [TRAIN] Loss: 0.4985, Accuracy: 78.73%, AUC: 0.78 - [VAL] Loss: 0.5012, Accuracy: 78.26%, AUC: 0.78
Epoch [30/100] - [TRAIN] Loss: 0.4985, Accuracy: 78.70%, AUC: 0.78 - [VAL] Loss: 0.5009, Accuracy: 78.30%, AUC: 0.78
Epoch [31/100] - [TRAIN] Loss: 0.4986, Accuracy: 78.74%, AUC: 0.78 - [VAL] Loss: 0.5012, Accuracy: 78.26%, AUC: 0.78
Epoch [32/100] - [TRAIN] Loss: 0.4982, Accuracy: 78.81%, AUC: 0.78 - [VAL] Loss: 0.5008, Accuracy: 78.24%, AUC: 0.78
New best model saved with validation metric: 25.0563
Epoch [33/100] - [TRAIN] Loss: 0.4951, Accuracy: 78.79%, AUC: 0.78 - [VAL] Loss: 0.4999, Accuracy: 78.46%, AUC: 0.78
Epoch [34/100] - [TRAIN] Loss: 0.4949, Accuracy: 78.85%, AUC: 0.78 - [VAL] Loss: 0.5005, Accuracy: 78.26%, AUC: 0.78
Epoch [35/100] - [TRAIN] Loss: 0.4952, Accuracy: 78.88%, AUC: 0.78 - [VAL] Loss: 0.5002, Accuracy: 78.26%, AUC: 0.78
Epoch [36/100] - [TRAIN] Loss: 0.4936, Accuracy: 78.83%, AUC: 0.78 - [VAL] Loss: 0.4998, Accuracy: 78.37%, AUC: 0.78
New best model saved with validation metric: 25.0606
Epoch [37/100] - [TRAIN] Loss: 0.4956, Accuracy: 78.85%, AUC: 0.78 - [VAL] Loss: 0.4990, Accuracy: 78.47%, AUC: 0.78
New best model saved with validation metric: 25.0823
Epoch [38/100] - [TRAIN] Loss: 0.4932, Accuracy: 78.90%, AUC: 0.78 - [VAL] Loss: 0.4986, Accuracy: 78.54%, AUC: 0.78
New best model saved with validation metric: 25.0866
Epoch [39/100] - [TRAIN] Loss: 0.4941, Accuracy: 78.93%, AUC: 0.78 - [VAL] Loss: 0.4985, Accuracy: 78.55%, AUC: 0.78
Epoch [40/100] - [TRAIN] Loss: 0.4927, Accuracy: 78.85%, AUC: 0.78 - [VAL] Loss: 0.4984, Accuracy: 78.53%, AUC: 0.78
Epoch [41/100] - [TRAIN] Loss: 0.4920, Accuracy: 79.05%, AUC: 0.78 - [VAL] Loss: 0.4983, Accuracy: 78.55%, AUC: 0.78
Epoch [42/100] - [TRAIN] Loss: 0.4930, Accuracy: 78.82%, AUC: 0.78 - [VAL] Loss: 0.4983, Accuracy: 78.53%, AUC: 0.78
Epoch [43/100] - [TRAIN] Loss: 0.4910, Accuracy: 78.97%, AUC: 0.78 - [VAL] Loss: 0.4980, Accuracy: 78.51%, AUC: 0.78
Epoch [44/100] - [TRAIN] Loss: 0.4905, Accuracy: 78.86%, AUC: 0.78 - [VAL] Loss: 0.4978, Accuracy: 78.53%, AUC: 0.78
Epoch [45/100] - [TRAIN] Loss: 0.4903, Accuracy: 78.93%, AUC: 0.78 - [VAL] Loss: 0.4981, Accuracy: 78.49%, AUC: 0.78
Epoch [46/100] - [TRAIN] Loss: 0.4905, Accuracy: 78.98%, AUC: 0.78 - [VAL] Loss: 0.4985, Accuracy: 78.50%, AUC: 0.78
New best model saved with validation metric: 25.0996
Epoch [47/100] - [TRAIN] Loss: 0.4910, Accuracy: 78.93%, AUC: 0.78 - [VAL] Loss: 0.4973, Accuracy: 78.60%, AUC: 0.78
Epoch [48/100] - [TRAIN] Loss: 0.4882, Accuracy: 78.90%, AUC: 0.78 - [VAL] Loss: 0.4966, Accuracy: 78.60%, AUC: 0.78
Epoch [49/100] - [TRAIN] Loss: 0.4887, Accuracy: 78.90%, AUC: 0.78 - [VAL] Loss: 0.4972, Accuracy: 78.60%, AUC: 0.78
Epoch [50/100] - [TRAIN] Loss: 0.4894, Accuracy: 79.06%, AUC: 0.78 - [VAL] Loss: 0.4966, Accuracy: 78.60%, AUC: 0.78
New best model saved with validation metric: 25.1299
Epoch [51/100] - [TRAIN] Loss: 0.4881, Accuracy: 79.02%, AUC: 0.78 - [VAL] Loss: 0.4962, Accuracy: 78.69%, AUC: 0.78
Epoch [52/100] - [TRAIN] Loss: 0.4879, Accuracy: 79.02%, AUC: 0.78 - [VAL] Loss: 0.4963, Accuracy: 78.69%, AUC: 0.78
Epoch [53/100] - [TRAIN] Loss: 0.4881, Accuracy: 79.06%, AUC: 0.78 - [VAL] Loss: 0.4967, Accuracy: 78.64%, AUC: 0.78
Epoch [54/100] - [TRAIN] Loss: 0.4882, Accuracy: 79.05%, AUC: 0.78 - [VAL] Loss: 0.4979, Accuracy: 78.50%, AUC: 0.78
Epoch [55/100] - [TRAIN] Loss: 0.4858, Accuracy: 79.01%, AUC: 0.78 - [VAL] Loss: 0.4961, Accuracy: 78.69%, AUC: 0.78
Epoch [56/100] - [TRAIN] Loss: 0.4852, Accuracy: 79.12%, AUC: 0.78 - [VAL] Loss: 0.4964, Accuracy: 78.66%, AUC: 0.78
Epoch [57/100] - [TRAIN] Loss: 0.4853, Accuracy: 79.31%, AUC: 0.79 - [VAL] Loss: 0.4966, Accuracy: 78.51%, AUC: 0.78
Epoch [58/100] - [TRAIN] Loss: 0.4846, Accuracy: 79.16%, AUC: 0.78 - [VAL] Loss: 0.4958, Accuracy: 78.66%, AUC: 0.78
Epoch [59/100] - [TRAIN] Loss: 0.4845, Accuracy: 79.24%, AUC: 0.79 - [VAL] Loss: 0.4976, Accuracy: 78.50%, AUC: 0.78
New best model saved with validation metric: 25.1429
Epoch [60/100] - [TRAIN] Loss: 0.4846, Accuracy: 79.16%, AUC: 0.78 - [VAL] Loss: 0.4955, Accuracy: 78.73%, AUC: 0.78
Epoch [61/100] - [TRAIN] Loss: 0.4841, Accuracy: 79.29%, AUC: 0.79 - [VAL] Loss: 0.4962, Accuracy: 78.62%, AUC: 0.78
Epoch [62/100] - [TRAIN] Loss: 0.4828, Accuracy: 79.09%, AUC: 0.78 - [VAL] Loss: 0.4957, Accuracy: 78.65%, AUC: 0.78
Epoch [63/100] - [TRAIN] Loss: 0.4834, Accuracy: 79.13%, AUC: 0.78 - [VAL] Loss: 0.4965, Accuracy: 78.61%, AUC: 0.78
Epoch [64/100] - [TRAIN] Loss: 0.4826, Accuracy: 79.23%, AUC: 0.78 - [VAL] Loss: 0.4964, Accuracy: 78.64%, AUC: 0.78
Epoch [65/100] - [TRAIN] Loss: 0.4817, Accuracy: 79.19%, AUC: 0.78 - [VAL] Loss: 0.4967, Accuracy: 78.65%, AUC: 0.78
Epoch [66/100] - [TRAIN] Loss: 0.4821, Accuracy: 79.38%, AUC: 0.79 - [VAL] Loss: 0.4960, Accuracy: 78.64%, AUC: 0.78
Epoch [67/100] - [TRAIN] Loss: 0.4807, Accuracy: 79.27%, AUC: 0.79 - [VAL] Loss: 0.4958, Accuracy: 78.64%, AUC: 0.78
Epoch [68/100] - [TRAIN] Loss: 0.4799, Accuracy: 79.34%, AUC: 0.79 - [VAL] Loss: 0.4956, Accuracy: 78.72%, AUC: 0.78
Epoch [69/100] - [TRAIN] Loss: 0.4818, Accuracy: 79.28%, AUC: 0.79 - [VAL] Loss: 0.4956, Accuracy: 78.70%, AUC: 0.78
Epoch [70/100] - [TRAIN] Loss: 0.4807, Accuracy: 79.35%, AUC: 0.79 - [VAL] Loss: 0.4974, Accuracy: 78.60%, AUC: 0.78
Epoch [71/100] - [TRAIN] Loss: 0.4796, Accuracy: 79.36%, AUC: 0.79 - [VAL] Loss: 0.4957, Accuracy: 78.73%, AUC: 0.78
New best model saved with validation metric: 25.1558
Epoch [72/100] - [TRAIN] Loss: 0.4790, Accuracy: 79.31%, AUC: 0.79 - [VAL] Loss: 0.4956, Accuracy: 78.77%, AUC: 0.78
Epoch [73/100] - [TRAIN] Loss: 0.4781, Accuracy: 79.35%, AUC: 0.79 - [VAL] Loss: 0.4957, Accuracy: 78.76%, AUC: 0.78
Epoch [74/100] - [TRAIN] Loss: 0.4786, Accuracy: 79.31%, AUC: 0.79 - [VAL] Loss: 0.4957, Accuracy: 78.76%, AUC: 0.78
Epoch [75/100] - [TRAIN] Loss: 0.4806, Accuracy: 79.46%, AUC: 0.79 - [VAL] Loss: 0.4985, Accuracy: 78.49%, AUC: 0.78
Epoch [76/100] - [TRAIN] Loss: 0.4790, Accuracy: 79.31%, AUC: 0.79 - [VAL] Loss: 0.4963, Accuracy: 78.65%, AUC: 0.78
Epoch [77/100] - [TRAIN] Loss: 0.4783, Accuracy: 79.25%, AUC: 0.79 - [VAL] Loss: 0.4958, Accuracy: 78.73%, AUC: 0.78
Epoch [78/100] - [TRAIN] Loss: 0.4781, Accuracy: 79.39%, AUC: 0.79 - [VAL] Loss: 0.4970, Accuracy: 78.72%, AUC: 0.78
New best model saved with validation metric: 25.1775
Epoch [79/100] - [TRAIN] Loss: 0.4779, Accuracy: 79.48%, AUC: 0.79 - [VAL] Loss: 0.4961, Accuracy: 78.84%, AUC: 0.78
Epoch [80/100] - [TRAIN] Loss: 0.4786, Accuracy: 79.43%, AUC: 0.79 - [VAL] Loss: 0.4962, Accuracy: 78.76%, AUC: 0.78
Epoch [81/100] - [TRAIN] Loss: 0.4764, Accuracy: 79.48%, AUC: 0.79 - [VAL] Loss: 0.4959, Accuracy: 78.84%, AUC: 0.78
Epoch [82/100] - [TRAIN] Loss: 0.4784, Accuracy: 79.55%, AUC: 0.79 - [VAL] Loss: 0.4974, Accuracy: 78.60%, AUC: 0.78
Epoch [83/100] - [TRAIN] Loss: 0.4756, Accuracy: 79.54%, AUC: 0.79 - [VAL] Loss: 0.4974, Accuracy: 78.55%, AUC: 0.78
Epoch [84/100] - [TRAIN] Loss: 0.4764, Accuracy: 79.62%, AUC: 0.79 - [VAL] Loss: 0.4962, Accuracy: 78.74%, AUC: 0.78
Epoch [85/100] - [TRAIN] Loss: 0.4749, Accuracy: 79.56%, AUC: 0.79 - [VAL] Loss: 0.4976, Accuracy: 78.61%, AUC: 0.78
Epoch [86/100] - [TRAIN] Loss: 0.4762, Accuracy: 79.54%, AUC: 0.79 - [VAL] Loss: 0.4973, Accuracy: 78.65%, AUC: 0.78
Epoch [87/100] - [TRAIN] Loss: 0.4742, Accuracy: 79.67%, AUC: 0.79 - [VAL] Loss: 0.4975, Accuracy: 78.60%, AUC: 0.78
Epoch [88/100] - [TRAIN] Loss: 0.4736, Accuracy: 79.55%, AUC: 0.79 - [VAL] Loss: 0.4970, Accuracy: 78.64%, AUC: 0.78
New best model saved with validation metric: 25.2078
Epoch [89/100] - [TRAIN] Loss: 0.4769, Accuracy: 79.58%, AUC: 0.79 - [VAL] Loss: 0.4966, Accuracy: 78.93%, AUC: 0.78
Epoch [90/100] - [TRAIN] Loss: 0.4757, Accuracy: 79.52%, AUC: 0.79 - [VAL] Loss: 0.4968, Accuracy: 78.74%, AUC: 0.78
Epoch [91/100] - [TRAIN] Loss: 0.4759, Accuracy: 79.61%, AUC: 0.79 - [VAL] Loss: 0.4980, Accuracy: 78.57%, AUC: 0.78
New best model saved with validation metric: 25.2294
Epoch [92/100] - [TRAIN] Loss: 0.4734, Accuracy: 79.61%, AUC: 0.79 - [VAL] Loss: 0.4969, Accuracy: 79.00%, AUC: 0.78
Epoch [93/100] - [TRAIN] Loss: 0.4734, Accuracy: 79.66%, AUC: 0.79 - [VAL] Loss: 0.4969, Accuracy: 78.79%, AUC: 0.78
Epoch [94/100] - [TRAIN] Loss: 0.4751, Accuracy: 79.66%, AUC: 0.79 - [VAL] Loss: 0.4989, Accuracy: 78.51%, AUC: 0.78
Epoch [95/100] - [TRAIN] Loss: 0.4736, Accuracy: 79.58%, AUC: 0.79 - [VAL] Loss: 0.4977, Accuracy: 78.88%, AUC: 0.78
Epoch [96/100] - [TRAIN] Loss: 0.4723, Accuracy: 79.69%, AUC: 0.79 - [VAL] Loss: 0.4979, Accuracy: 78.79%, AUC: 0.78
Epoch [97/100] - [TRAIN] Loss: 0.4719, Accuracy: 79.58%, AUC: 0.79 - [VAL] Loss: 0.4976, Accuracy: 78.83%, AUC: 0.78
Epoch [98/100] - [TRAIN] Loss: 0.4721, Accuracy: 79.62%, AUC: 0.79 - [VAL] Loss: 0.4976, Accuracy: 78.85%, AUC: 0.78
Epoch [99/100] - [TRAIN] Loss: 0.4723, Accuracy: 79.75%, AUC: 0.79 - [VAL] Loss: 0.4973, Accuracy: 78.95%, AUC: 0.78
Epoch [100/100] - [TRAIN] Loss: 0.4718, Accuracy: 79.65%, AUC: 0.79 - [VAL] Loss: 0.4973, Accuracy: 78.95%, AUC: 0.78
Training finished!

In [33]:
# Load the best model
best_model = DeepClassifier(input_dim = [n_rows_item, 4000]).to(device)
best_model.load_state_dict(torch.load(best_model_path))
best_model.eval()

# Predict on test set
test_predictions = []
test_true_labels = []

with torch.no_grad():
    for inputs, labels in test_loader:
        outputs = best_model(inputs)
        # probabilities = torch.softmax(outputs, dim=1)
        _, predicted = torch.max(outputs.data, 1)
        test_predictions.extend(predicted.cpu().numpy())
        test_true_labels.extend(labels.cpu().numpy())

# Calculate evaluation metric
test_acc_score = round(accuracy_score(test_true_labels, test_predictions) * 100, 2)
print(f"Accuracy Score on test set: {test_acc_score:.2f} %")
test_auc_score = round(roc_auc_score(test_true_labels, test_predictions), 2)
print(f"AUC Score on test set: {test_auc_score:.2f}")

Accuracy Score on test set: 79.24 %
AUC Score on test set: 0.79

In [34]:
# Create dataframe from array
experiment_results = {
    'train_loss': train_losses,
    'train_accuracy': train_accuracies,
    'train_auc': train_aucs,
    'val_loss': val_losses,
    'val_accuracy': val_accuracies,
    'val_auc': val_aucs
}

In [64]:
experiment_pl = pl.DataFrame(experiment_results)

In [65]:
experiment_pl.write_csv(os.path.join(WORKING_DIR, 'experiments', 'details', f'{item_name}.csv'))

In [37]:
def min_avg_max(lst):
    return round(min(lst), 2), round(sum(lst)/len(lst), 2), round(max(lst), 2)

In [38]:
train_loss_min, train_loss_avg, train_loss_max = min_avg_max(train_losses)
train_acc_min, train_acc_avg, train_acc_max = min_avg_max(train_accuracies)
train_auc_min, train_auc_avg, train_auc_max = min_avg_max(train_aucs)

print(f"{train_loss_min:.2f}, {train_loss_avg:.2f}, {train_loss_max:.2f}")
print(f"{train_acc_min}, {train_acc_avg}, {train_acc_max}")
print(f"{train_auc_min}, {train_auc_avg}, {train_auc_max}")

0.47, 0.49, 0.65
60.82, 78.54, 79.75
0.5, 0.78, 0.79

In [39]:
val_loss_min, val_loss_avg, val_loss_max = min_avg_max(val_losses)
val_acc_min, val_acc_avg, val_acc_max = min_avg_max(val_accuracies)
val_auc_min, val_auc_avg, val_auc_max = min_avg_max(val_aucs)

print(f"{val_loss_min:.2f}, {val_loss_avg:.2f}, {val_loss_max:.2f}")
print(f"{val_acc_min}, {val_acc_avg}, {val_acc_max}")
print(f"{val_auc_min}, {val_auc_avg}, {val_auc_max}")

0.50, 0.50, 0.60
60.82, 78.13, 79.0
0.5, 0.77, 0.78

In [40]:
print(f"{test_acc_score}, {test_auc_score}")

79.24, 0.79

In [53]:
# Prepare the output file
output_rows = []

output_rows.append([
    item_name,
    train_loss_min, train_loss_avg, train_loss_max,
    train_acc_min, train_acc_avg, train_acc_max,
    train_auc_min, train_auc_avg, train_auc_max,
    val_loss_min, val_loss_avg, val_loss_max,
    val_acc_min, val_acc_avg, val_acc_max,
    val_auc_min, val_auc_avg, val_auc_max,
    
])

output_rows_df = pd.DataFrame(output_rows, 
    columns=[
        "item_name",
        "train_loss_min", "train_loss_avg", "train_loss_max",
        "train_acc_min", "train_acc_avg", "train_acc_max",
        "train_auc_min", "train_auc_avg", "train_auc_max",
        "val_loss_min", "val_loss_avg", "val_loss_max",
        "val_acc_min", "val_acc_avg", "val_acc_max",
        "val_auc_min", "val_auc_avg", "val_auc_max",
    ]
)

output_df = pd.concat([output_df, output_rows_df], ignore_index=True)

output_df

/tmp/ipykernel_387165/3815267995.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_df = pd.concat([output_df, output_rows_df], ignore_index=True)

,item_name,train_loss_min,train_loss_avg,train_loss_max,train_acc_min,train_acc_avg,train_acc_max,train_auc_min,train_auc_avg,train_auc_max,val_loss_min,val_loss_avg,val_loss_max,val_acc_min,val_acc_avg,val_acc_max,val_auc_min,val_auc_avg,val_auc_max
0,H3K9me3-H3K9ac-H3K27ac-H3K4me3,0.47,0.49,0.65,60.82,78.54,79.75,0.5,0.78,0.79,0.5,0.5,0.6,60.82,78.13,79.0,0.5,0.77,0.78

In [54]:
start = 0
end = 50

output_df.to_csv(os.path.join(WORKING_DIR, "experiments", "min-avg-max", 
                              f"batch-{str(start + 1).rjust(3, '0')}-{str(end).rjust(3, '0')}.csv"), 
                 header=True, index=False)

In [71]:
# Get CSV files list from a folder
csv_files = glob.glob(os.path.join(WORKING_DIR, "experiments", "min-avg-max", "*.csv"))
print(csv_files)

['/group/pmc021/amunif/epi-thesis/workflow/08_HepG2/experiments/min-avg-max/batch-301-350.csv', '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2/experiments/min-avg-max/batch-001-050.csv', '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2/experiments/min-avg-max/batch-051-100.csv', '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2/experiments/min-avg-max/batch-151-200.csv', '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2/experiments/min-avg-max/batch-101-150.csv', '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2/experiments/min-avg-max/batch-201-250.csv', '/group/pmc021/amunif/epi-thesis/workflow/08_HepG2/experiments/min-avg-max/batch-251-300.csv']

In [72]:
# Read each CSV file into DataFrame
# This creates a list of dataframes
df_list = (pd.read_csv(file) for file in csv_files)

In [73]:
# Concatenate all DataFrames
big_df = pd.concat(df_list, ignore_index=True)

In [74]:
big_df.to_csv(os.path.join(WORKING_DIR, "experiments", "all_results.csv"), header=True, index=False)

In [66]:
def min_avg_max(lst):
    return round(min(lst), 2), round(sum(lst)/len(lst), 2), round(max(lst), 2)

In [70]:
start = 0
end = 1

output_rows = []

for item in permutations[start:end]:
    # Generate item name
    item_name = '-'.join(item)
    print(f"Item: {item_name}")

    # Create dataframe based on histone marker permutation item
    gene_perm_pl = gene_pl.with_columns(
        pl.struct(item).map_elements(
            lambda x: [x[col_name] for col_name in item],
            return_dtype = pl.List(pl.List(pl.Float64))
        )
        .alias('histone')
    )

    # Select X and y column
    X = gene_perm_pl.select(pl.col('histone')).to_series().to_list()
    y = gene_perm_pl.select(pl.col('label')).to_series().to_list()

    # Convert to Numpy array
    X = np.array(X)
    y = np.array(y)

    # Split the dataset into training, validation, and test sets
    X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.666, random_state=42, stratify=y)
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)
    print("Train set shape:", X_train.shape, y_train.shape)
    print("Validation set shape:", X_val.shape, y_val.shape)
    print("Test set shape:", X_test.shape, y_test.shape)

    # Convert numpy arrays to PyTorch tensors
    X_train = torch.from_numpy(X_train).float().unsqueeze(1).to(device)
    X_val = torch.from_numpy(X_val).float().unsqueeze(1).to(device)
    X_test = torch.from_numpy(X_test).float().unsqueeze(1).to(device)

    y_train = torch.from_numpy(y_train).float().to(device)
    y_val = torch.from_numpy(y_val).float().to(device)
    y_test = torch.from_numpy(y_test).float().to(device)

    # Create DataLoaders
    batch_size = 32

    train_dataset = TensorDataset(X_train, y_train)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

    val_dataset = TensorDataset(X_val, y_val)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)

    test_dataset = TensorDataset(X_test, y_test)
    test_loader = DataLoader(test_dataset, batch_size=batch_size)

    # Initialize the model
    model = DeepClassifier(input_dim = [len(item), 4000]).to(device)
    criterion = nn.NLLLoss()
    optimizer = optim.SGD(model.parameters(), lr=0.001)
    num_epochs = 10

    # For tracking train and validation
    train_losses, val_losses = [], []
    train_accuracies, val_accuracies = [], []
    train_aucs, val_aucs = [], []

    # Preparing the output dataframe
    output_df = pd.DataFrame(columns=[
        "item_name",
        "train_loss_min", "train_loss_avg", "train_loss_max",
        "train_acc_min", "train_acc_avg", "train_acc_max",
        "train_auc_min", "train_auc_avg", "train_auc_max",
        "val_loss_min", "val_loss_avg", "val_loss_max",
        "val_acc_min", "val_acc_avg", "val_acc_max",
        "val_auc_min", "val_auc_avg", "val_auc_max",
    ])

    # For saving the best model
    best_val_metric = float('-inf')
    best_model_path = os.path.join(WORKING_DIR, "experiments", "model", f'{item_name}.pth')

    # Run the training and validation phase
    for epoch in range(num_epochs):
        # Training phase
        model.train()  # Set the model to training mode
        train_loss = 0.0
        train_correct = 0
        train_total = 0
        train_true_labels = []
        train_predicted_probs = []
        
        for inputs, labels in train_loader:
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs.cuda(), labels.type(torch.LongTensor).cuda())
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

            _, predicted = torch.max(outputs.data, 1)
            train_total += labels.size(0)
            train_correct += (predicted == labels).sum().item()

            train_true_labels.extend(labels.cpu().numpy())
            train_predicted_probs.extend(predicted.cpu().numpy())
        
        avg_train_loss = train_loss / len(train_loader)
        train_accuracy = 100 * train_correct / train_total
        train_auc_score = roc_auc_score(train_true_labels, train_predicted_probs)
        
        train_losses.append(round(avg_train_loss, 4))
        train_accuracies.append(round(train_accuracy, 2))
        train_aucs.append(round(train_auc_score, 2))
        
        # Validation phase
        model.eval()  # Set the model to evaluation mode
        val_loss = 0.0
        val_correct = 0
        val_total = 0
        val_metric = 0
        val_true_labels = []
        val_predicted_probs = []
        
        with torch.no_grad():  # Disable gradient computation
            for inputs, labels in val_loader:
                outputs = model(inputs)
                loss = criterion(outputs.cuda(), labels.type(torch.LongTensor).cuda())
                val_loss += loss.item()
                _, predicted = torch.max(outputs.data, 1)
                val_total += labels.size(0)
                val_correct += (predicted == labels).sum().item()

                val_true_labels.extend(labels.cpu().numpy())
                val_predicted_probs.extend(predicted.cpu().numpy())

        avg_val_loss = val_loss / len(val_loader)
        val_accuracy = 100 * val_correct / val_total
        val_metric = val_correct / len(val_loader)

        # Save the best model
        if val_metric > best_val_metric:
            best_val_metric = val_metric
            torch.save(model.state_dict(), best_model_path)
            print(f"New best model saved with validation metric: {best_val_metric:.4f}")
        
        val_true_labels = np.array(val_true_labels)
        val_predicted_probs = np.array(val_predicted_probs)
        val_auc_score = roc_auc_score(val_true_labels, val_predicted_probs)

        val_losses.append(round(avg_val_loss, 4))
        val_accuracies.append(round(val_accuracy, 2))
        val_aucs.append(round(val_auc_score, 2))
        
        print(f'Epoch [{epoch+1}/{num_epochs}] - '
            f'[TRAIN] Loss: {avg_train_loss:.4f}, Accuracy: {train_accuracy:.2f}%, AUC: {train_auc_score:.2f} - '
            f'[VAL] Loss: {avg_val_loss:.4f}, Accuracy: {val_accuracy:.2f}%, AUC: {val_auc_score:.2f}')
    print("Training finished!")

    # Load the best model
    best_model = DeepClassifier(input_dim = [len(item), 4000]).to(device)
    best_model.load_state_dict(torch.load(best_model_path))
    best_model.eval()

    # Predict on test set
    test_predictions = []
    test_true_labels = []

    with torch.no_grad():
        for inputs, labels in test_loader:
            outputs = best_model(inputs)
            # probabilities = torch.softmax(outputs, dim=1)
            _, predicted = torch.max(outputs.data, 1)
            test_predictions.extend(predicted.cpu().numpy())
            test_true_labels.extend(labels.cpu().numpy())

    # Calculate evaluation metric
    test_acc_score = round(accuracy_score(test_true_labels, test_predictions) * 100, 2)
    print(f"Accuracy Score on test set: {test_acc_score:.2f} %")
    test_auc_score = round(roc_auc_score(test_true_labels, test_predictions), 2)
    print(f"AUC Score on test set: {test_auc_score:.2f}")

    # Create dataframe from array
    experiment_results = {
        'train_loss': train_losses,
        'train_accuracy': train_accuracies,
        'train_auc': train_aucs,
        'val_loss': val_losses,
        'val_accuracy': val_accuracies,
        'val_auc': val_aucs
    }

    # Save the experiment results
    experiment_pl = pl.DataFrame(experiment_results)
    experiment_pl.write_csv(os.path.join(WORKING_DIR, 'experiments', 'details', f'{item_name}.csv'))

    # Find the min, avg, max for training and validation step
    train_loss_min, train_loss_avg, train_loss_max = min_avg_max(train_losses)
    train_acc_min, train_acc_avg, train_acc_max = min_avg_max(train_accuracies)
    train_auc_min, train_auc_avg, train_auc_max = min_avg_max(train_aucs)

    val_loss_min, val_loss_avg, val_loss_max = min_avg_max(val_losses)
    val_acc_min, val_acc_avg, val_acc_max = min_avg_max(val_accuracies)
    val_auc_min, val_auc_avg, val_auc_max = min_avg_max(val_aucs)

    output_rows.append([
        item_name,
        train_loss_min, train_loss_avg, train_loss_max,
        train_acc_min, train_acc_avg, train_acc_max,
        train_auc_min, train_auc_avg, train_auc_max,
        val_loss_min, val_loss_avg, val_loss_max,
        val_acc_min, val_acc_avg, val_acc_max,
        val_auc_min, val_auc_avg, val_auc_max,
        
    ])

# Saving current batch results
output_rows_df = pd.DataFrame(output_rows, 
    columns=[
        "item_name",
        "train_loss_min", "train_loss_avg", "train_loss_max",
        "train_acc_min", "train_acc_avg", "train_acc_max",
        "train_auc_min", "train_auc_avg", "train_auc_max",
        "val_loss_min", "val_loss_avg", "val_loss_max",
        "val_acc_min", "val_acc_avg", "val_acc_max",
        "val_auc_min", "val_auc_avg", "val_auc_max",
    ]
)

output_rows_df.to_csv(os.path.join(WORKING_DIR, "experiments", "min-avg-max", 
                              f"batch-{str(start + 1).rjust(3, '0')}-{str(end).rjust(3, '0')}.csv"), 
                 header=True, index=False)

print("Batch FINISHED!!!")

Item: H3K4me3
Train set shape: (7399, 1, 4000) (7399,)
Validation set shape: (7377, 1, 4000) (7377,)
Test set shape: (7378, 1, 4000) (7378,)
New best model saved with validation metric: 19.4242
Epoch [1/10] - [TRAIN] Loss: 0.6315, Accuracy: 60.82%, AUC: 0.50 - [VAL] Loss: 0.5934, Accuracy: 60.82%, AUC: 0.50
New best model saved with validation metric: 24.8095
Epoch [2/10] - [TRAIN] Loss: 0.5749, Accuracy: 64.68%, AUC: 0.56 - [VAL] Loss: 0.5524, Accuracy: 77.69%, AUC: 0.76
Epoch [3/10] - [TRAIN] Loss: 0.5468, Accuracy: 77.88%, AUC: 0.76 - [VAL] Loss: 0.5357, Accuracy: 77.58%, AUC: 0.77
Epoch [4/10] - [TRAIN] Loss: 0.5349, Accuracy: 77.71%, AUC: 0.77 - [VAL] Loss: 0.5298, Accuracy: 77.55%, AUC: 0.77
New best model saved with validation metric: 24.8312
Epoch [5/10] - [TRAIN] Loss: 0.5266, Accuracy: 77.77%, AUC: 0.77 - [VAL] Loss: 0.5250, Accuracy: 77.76%, AUC: 0.77
Epoch [6/10] - [TRAIN] Loss: 0.5269, Accuracy: 77.85%, AUC: 0.77 - [VAL] Loss: 0.5225, Accuracy: 77.70%, AUC: 0.77
Epoch [7/10] - [TRAIN] Loss: 0.5225, Accuracy: 77.88%, AUC: 0.77 - [VAL] Loss: 0.5207, Accuracy: 77.58%, AUC: 0.77
Epoch [8/10] - [TRAIN] Loss: 0.5183, Accuracy: 77.74%, AUC: 0.77 - [VAL] Loss: 0.5190, Accuracy: 77.57%, AUC: 0.77
Epoch [9/10] - [TRAIN] Loss: 0.5180, Accuracy: 77.96%, AUC: 0.77 - [VAL] Loss: 0.5200, Accuracy: 77.12%, AUC: 0.77
Epoch [10/10] - [TRAIN] Loss: 0.5163, Accuracy: 77.86%, AUC: 0.77 - [VAL] Loss: 0.5164, Accuracy: 77.66%, AUC: 0.77
Training finished!
Accuracy Score on test set: 78.14 %
AUC Score on test set: 0.78
Batch FINISHED!!!