In [30]:
import polars as pl
import os

from pathlib import Path

In [31]:
WORKING_PATH = Path('/group/pmc021/amunif/epi-thesis/workflow/18_Pairwise Ranking HepG2 REMC/')
DATASET_PATH = WORKING_PATH / 'dataset'
OUTPUT_PATH  = WORKING_PATH / 'output' / 'combined'

# Merge the experiment results

In [32]:
# Read all CSV into single dataframe
pl_df = pl.read_csv(OUTPUT_PATH / 'test' / "*-test-metrics.csv")

In [33]:
pl_df

shape: (620, 13)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬─────────┬────────────┐
│ model      ┆ seed ┆ histone_ma ┆ epochs_tra ┆ … ┆ test_preci ┆ test_recal ┆ test_f1 ┆ antisymmet │
│ ---        ┆ ---  ┆ rker       ┆ ined       ┆   ┆ sion       ┆ l          ┆ ---     ┆ ry         │
│ str        ┆ i64  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64     ┆ ---        │
│            ┆      ┆ str        ┆ i64        ┆   ┆ f64        ┆ f64        ┆         ┆ f64        │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪═════════╪════════════╡
│ DirectRank ┆ 1011 ┆ H3K4me3    ┆ 12         ┆ … ┆ 0.7218     ┆ 0.7745     ┆ 0.7472  ┆ 0.922      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7966     ┆ 0.6868     ┆ 0.7377  ┆ 0.797      │
│ gression   ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7898     ┆ 0.714      ┆ 0.75    ┆ 0.788      │
│ st         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7976     ┆ 0.691      ┆ 0.7405  ┆ 0.794      │
│ DirectRank ┆ 123  ┆ H3K4me3    ┆ 14         ┆ … ┆ 0.7097     ┆ 0.7857     ┆ 0.7458  ┆ 0.922      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …       ┆ …          │
│ SVM_Linear ┆ 456  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7665     ┆ 0.7337     ┆ 0.7497  ┆ 0.759      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ DirectRank ┆ 789  ┆ H3K4me3-H3 ┆ 54         ┆ … ┆ 0.7436     ┆ 0.7835     ┆ 0.7631  ┆ 0.989      │
│ er         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7238     ┆ 0.7134     ┆ 0.7186  ┆ 0.777      │
│ gression   ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7996     ┆ 0.7402     ┆ 0.7687  ┆ 0.833      │
│ st         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7201     ┆ 0.6948     ┆ 0.7072  ┆ 0.777      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴─────────┴────────────┘

In [34]:
# Save the results by model 
MODEL_RESULT_FOLDER = OUTPUT_PATH / 'model_results'
os.makedirs(MODEL_RESULT_FOLDER, exist_ok=True)

for model_name in pl_df["model"].unique():
    pl_df.filter(pl_df["model"] == model_name).write_csv(MODEL_RESULT_FOLDER / f"{model_name}.csv", include_header=True)

In [35]:
# Save the results for all models and all seeds
pl_df.write_csv(OUTPUT_PATH / "HepG2 ENCSR134DWG_all_results.csv", include_header=True)

In [36]:
summary_df = (
    pl_df
    .group_by(["histone_marker", "model"])
    .agg([
        pl.col("val_accuracy").mean().alias("val_accuracy_mean"),
        pl.col("val_accuracy").std().alias("val_accuracy_std"),
        pl.col("val_auc").mean().alias("val_auc_mean"),
        pl.col("val_auc").std().alias("val_auc_std"),
        pl.col("test_accuracy").mean().alias("test_accuracy_mean"),
        pl.col("test_accuracy").std().alias("test_accuracy_std"),
        pl.col("test_auc").mean().alias("test_auc_mean"),
        pl.col("test_auc").std().alias("test_auc_std"),
        pl.col("test_aucprc").mean().alias("test_aucprc_mean"),
        pl.col("test_aucprc").std().alias("test_aucprc_std"),
        pl.col("antisymmetry").mean().alias("antisymmetry_mean"),
        pl.col("antisymmetry").std().alias("antisymmetry_std")
    ])
    .sort(["histone_marker", "test_accuracy_mean"], descending=[False, True])
    .with_columns(pl.col(pl.Float64).round(4))
)

In [37]:
summary_df

shape: (124, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ model     ┆ val_accur ┆ val_accur ┆ … ┆ test_aucp ┆ test_aucp ┆ antisymme ┆ antisymm │
│ arker     ┆ ---       ┆ acy_mean  ┆ acy_std   ┆   ┆ rc_mean   ┆ rc_std    ┆ try_mean  ┆ etry_std │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K27ac   ┆ RandomFor ┆ 77.06     ┆ 1.1739    ┆ … ┆ 0.8319    ┆ 0.0087    ┆ 0.724     ┆ 0.0157   │
│           ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ SVM_Linea ┆ 75.04     ┆ 1.417     ┆ … ┆ 0.7725    ┆ 0.0187    ┆ 0.6894    ┆ 0.0105   │
│           ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ LogisticR ┆ 75.16     ┆ 1.1696    ┆ … ┆ 0.7715    ┆ 0.0204    ┆ 0.6924    ┆ 0.0093   │
│           ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ DirectRan ┆ 73.1      ┆ 2.1378    ┆ … ┆ 0.8056    ┆ 0.0171    ┆ 0.7822    ┆ 0.0102   │
│           ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac-H ┆ RandomFor ┆ 77.14     ┆ 1.6772    ┆ … ┆ 0.8379    ┆ 0.0079    ┆ 0.7886    ┆ 0.0234   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K9me3-H ┆ SVM_Linea ┆ 71.62     ┆ 1.3755    ┆ … ┆ 0.7443    ┆ 0.0231    ┆ 0.754     ┆ 0.0189   │
│ 3K27ac-H3 ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27me3    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ RandomFor ┆ 67.38     ┆ 1.3664    ┆ … ┆ 0.6947    ┆ 0.0166    ┆ 0.8124    ┆ 0.0125   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ DirectRan ┆ 66.0      ┆ 1.4422    ┆ … ┆ 0.6945    ┆ 0.0207    ┆ 0.9586    ┆ 0.0026   │
│ 3K27me3   ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ SVM_Linea ┆ 61.1      ┆ 2.2594    ┆ … ┆ 0.6161    ┆ 0.019     ┆ 0.7018    ┆ 0.0084   │
│ 3K27me3   ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ LogisticR ┆ 61.52     ┆ 2.4356    ┆ … ┆ 0.6227    ┆ 0.0199    ┆ 0.7488    ┆ 0.0104   │
│ 3K27me3   ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [38]:
summary_df.write_csv(OUTPUT_PATH/ f"HepG2 ENCSR134DWG Ranking.csv", include_header=True)

In [39]:
for model_name in summary_df["model"].unique():
    summary_df.filter(summary_df["model"] == model_name).write_csv(MODEL_RESULT_FOLDER / f"{model_name}_summary.csv", include_header=True)

# Merge the label distribution

In [40]:
# Read all label distribution CSV into single dataframe
label_df = pl.read_csv(OUTPUT_PATH / 'test' / "*-label-distribution.csv")

In [41]:
label_df

shape: (930, 7)
┌──────┬─────────────────────────────────┬───────┬───────┬───────┬───────┬────────────┐
│ seed ┆ histone_marker                  ┆ split ┆ label ┆ count ┆ total ┆ percentage │
│ ---  ┆ ---                             ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---        │
│ i64  ┆ str                             ┆ str   ┆ i64   ┆ i64   ┆ i64   ┆ f64        │
╞══════╪═════════════════════════════════╪═══════╪═══════╪═══════╪═══════╪════════════╡
│ 1011 ┆ H3K4me3                         ┆ Train ┆ 0     ┆ 4140  ┆ 8000  ┆ 51.75      │
│ 1011 ┆ H3K4me3                         ┆ Train ┆ 1     ┆ 3860  ┆ 8000  ┆ 48.25      │
│ 1011 ┆ H3K4me3                         ┆ Val   ┆ 0     ┆ 553   ┆ 1000  ┆ 55.3       │
│ 1011 ┆ H3K4me3                         ┆ Val   ┆ 1     ┆ 447   ┆ 1000  ┆ 44.7       │
│ 1011 ┆ H3K4me3                         ┆ Test  ┆ 0     ┆ 521   ┆ 1000  ┆ 52.1       │
│ …    ┆ …                               ┆ …     ┆ …     ┆ …     ┆ …     ┆ …          │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Train ┆ 1     ┆ 3903  ┆ 8000  ┆ 48.79      │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Val   ┆ 0     ┆ 536   ┆ 1000  ┆ 53.6       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Val   ┆ 1     ┆ 464   ┆ 1000  ┆ 46.4       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Test  ┆ 0     ┆ 515   ┆ 1000  ┆ 51.5       │
│ 789  ┆ H3K4me3-H3K9ac-H3K9me3-H3K27ac… ┆ Test  ┆ 1     ┆ 485   ┆ 1000  ┆ 48.5       │
└──────┴─────────────────────────────────┴───────┴───────┴───────┴───────┴────────────┘

In [42]:
# Make the summary by seed, split and label
label_summary_df = (
    label_df
    .group_by(['split', 'label'])
    .agg(pl.col('percentage').mean().round(2).alias('average_percentage_%'))
    .sort(['split', 'label'])
)

In [43]:
label_summary_df

shape: (6, 3)
┌───────┬───────┬──────────────────────┐
│ split ┆ label ┆ average_percentage_% │
│ ---   ┆ ---   ┆ ---                  │
│ str   ┆ i64   ┆ f64                  │
╞═══════╪═══════╪══════════════════════╡
│ Test  ┆ 0     ┆ 50.98                │
│ Test  ┆ 1     ┆ 49.02                │
│ Train ┆ 0     ┆ 51.59                │
│ Train ┆ 1     ┆ 48.41                │
│ Val   ┆ 0     ┆ 53.3                 │
│ Val   ┆ 1     ┆ 46.7                 │
└───────┴───────┴──────────────────────┘