In [8]:
import polars as pl
import os

from pathlib import Path

In [9]:
WORKING_PATH = Path('/group/pmc021/amunif/epi-thesis/workflow/18_Pairwise Ranking HepG2 REMC/')
DATASET_PATH = WORKING_PATH / 'dataset'
OUTPUT_PATH  = WORKING_PATH / 'output' / 'combined'

In [10]:
### Merge the results into single CSV file

# Read all CSV into single dataframe
pl_df = pl.read_csv(OUTPUT_PATH / 'test' / "*-test-metrics.csv")

In [11]:
pl_df

shape: (620, 12)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬─────────┬────────────┐
│ model      ┆ seed ┆ histone_ma ┆ epochs_tra ┆ … ┆ test_preci ┆ test_recal ┆ test_f1 ┆ antisymmet │
│ ---        ┆ ---  ┆ rker       ┆ ined       ┆   ┆ sion       ┆ l          ┆ ---     ┆ ry         │
│ str        ┆ i64  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64     ┆ ---        │
│            ┆      ┆ str        ┆ i64        ┆   ┆ f64        ┆ f64        ┆         ┆ f64        │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪═════════╪════════════╡
│ DirectRank ┆ 1011 ┆ H3K4me3    ┆ 12         ┆ … ┆ 0.7218     ┆ 0.7745     ┆ 0.7472  ┆ 0.922      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7966     ┆ 0.6868     ┆ 0.7377  ┆ 0.797      │
│ gression   ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7898     ┆ 0.714      ┆ 0.75    ┆ 0.788      │
│ st         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 1011 ┆ H3K4me3    ┆ null       ┆ … ┆ 0.7976     ┆ 0.691      ┆ 0.7405  ┆ 0.794      │
│ DirectRank ┆ 123  ┆ H3K4me3    ┆ 14         ┆ … ┆ 0.7097     ┆ 0.7857     ┆ 0.7458  ┆ 0.922      │
│ er         ┆      ┆            ┆            ┆   ┆            ┆            ┆         ┆            │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …       ┆ …          │
│ SVM_Linear ┆ 456  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7665     ┆ 0.7337     ┆ 0.7497  ┆ 0.759      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ DirectRank ┆ 789  ┆ H3K4me3-H3 ┆ 54         ┆ … ┆ 0.7436     ┆ 0.7835     ┆ 0.7631  ┆ 0.989      │
│ er         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ LogisticRe ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7238     ┆ 0.7134     ┆ 0.7186  ┆ 0.777      │
│ gression   ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ RandomFore ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7996     ┆ 0.7402     ┆ 0.7687  ┆ 0.833      │
│ st         ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
│ SVM_Linear ┆ 789  ┆ H3K4me3-H3 ┆ null       ┆ … ┆ 0.7201     ┆ 0.6948     ┆ 0.7072  ┆ 0.777      │
│            ┆      ┆ K9ac-H3K9m ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ e3-H3K27ac ┆            ┆   ┆            ┆            ┆         ┆            │
│            ┆      ┆ …          ┆            ┆   ┆            ┆            ┆         ┆            │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴─────────┴────────────┘

In [12]:
summary_df = (
    pl_df
    .group_by(["histone_marker", "model"])
    .agg([
        pl.col("val_accuracy").mean().alias("val_accuracy_mean"),
        pl.col("val_accuracy").std().alias("val_accuracy_std"),
        pl.col("val_auc").mean().alias("val_auc_mean"),
        pl.col("val_auc").std().alias("val_auc_std"),
        pl.col("test_accuracy").mean().alias("test_accuracy_mean"),
        pl.col("test_accuracy").std().alias("test_accuracy_std"),
        pl.col("test_auc").mean().alias("test_auc_mean"),
        pl.col("test_auc").std().alias("test_auc_std"),
    ])
    .sort(["histone_marker", "test_accuracy_mean"], descending=[False, True])
    .with_columns(pl.col(pl.Float64).round(4))
)

In [13]:
summary_df

shape: (124, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ histone_m ┆ model     ┆ val_accur ┆ val_accur ┆ … ┆ test_accu ┆ test_accu ┆ test_auc_ ┆ test_auc │
│ arker     ┆ ---       ┆ acy_mean  ┆ acy_std   ┆   ┆ racy_mean ┆ racy_std  ┆ mean      ┆ _std     │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ H3K27ac   ┆ RandomFor ┆ 77.06     ┆ 1.1739    ┆ … ┆ 75.74     ┆ 1.4673    ┆ 0.8446    ┆ 0.0143   │
│           ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ LogisticR ┆ 75.16     ┆ 1.1696    ┆ … ┆ 73.18     ┆ 1.3161    ┆ 0.7987    ┆ 0.0141   │
│           ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ SVM_Linea ┆ 75.04     ┆ 1.417     ┆ … ┆ 73.18     ┆ 1.4464    ┆ 0.8009    ┆ 0.0134   │
│           ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac   ┆ DirectRan ┆ 73.1      ┆ 2.1378    ┆ … ┆ 71.96     ┆ 1.6965    ┆ 0.8254    ┆ 0.014    │
│           ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K27ac-H ┆ RandomFor ┆ 77.14     ┆ 1.6772    ┆ … ┆ 74.38     ┆ 1.1345    ┆ 0.8412    ┆ 0.0121   │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ H3K9me3-H ┆ SVM_Linea ┆ 71.62     ┆ 1.3755    ┆ … ┆ 70.68     ┆ 1.7922    ┆ 0.7751    ┆ 0.0179   │
│ 3K27ac-H3 ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ K27me3    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ RandomFor ┆ 67.38     ┆ 1.3664    ┆ … ┆ 65.38     ┆ 2.3339    ┆ 0.7163    ┆ 0.026    │
│ 3K27me3   ┆ est       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ DirectRan ┆ 66.0      ┆ 1.4422    ┆ … ┆ 65.06     ┆ 2.2188    ┆ 0.7139    ┆ 0.0242   │
│ 3K27me3   ┆ ker       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ SVM_Linea ┆ 61.1      ┆ 2.2594    ┆ … ┆ 62.36     ┆ 1.1082    ┆ 0.6521    ┆ 0.0201   │
│ 3K27me3   ┆ r         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ H3K9me3-H ┆ LogisticR ┆ 61.52     ┆ 2.4356    ┆ … ┆ 62.06     ┆ 1.5534    ┆ 0.6559    ┆ 0.0207   │
│ 3K27me3   ┆ egression ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
summary_df.write_csv(OUTPUT_PATH/ f"HepG2 REMC E118 Ranking.csv", include_header=True)