In [1]:
import polars as pl
import os

In [2]:
DATASET_PATH = "/group/pmc021/amunif/epi-thesis/workflow/13_Healthy liver with manual preprocessing/dataset/donor_4"

In [3]:
# Open the features file
test_df = pl.read_parquet(os.path.join(DATASET_PATH, 'donor4_exp_histones.parquet'))
test_df

shape: (19_645, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ gene_id    ┆ H3K9ac     ┆ H3K9ac_wc ┆ H3K9ac_le ┆ … ┆ H3K27me3  ┆ H3K27me3_ ┆ H3K27me3_ ┆ value  │
│ ---        ┆ ---        ┆ ---       ┆ n         ┆   ┆ ---       ┆ wc        ┆ len       ┆ ---    │
│ str        ┆ list[f64]  ┆ u32       ┆ ---       ┆   ┆ list[f64] ┆ ---       ┆ ---       ┆ f64    │
│            ┆            ┆           ┆ u32       ┆   ┆           ┆ u32       ┆ u32       ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ ENSG000000 ┆ [0.0, 0.0, ┆ 17        ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 73.205 │
│ 00003      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.191  │
│ 00005      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 25        ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 52.609 │
│ 00419      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 42        ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 4.733  │
│ 00457      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000000 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.942  │
│ 00460      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.212  │
│ 59658      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.0    │
│ 59664      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.071  │
│ 59680      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.0    │
│ 59717      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
│ ENSG000002 ┆ [0.0, 0.0, ┆ 0         ┆ 100       ┆ … ┆ [0.0,     ┆ 0         ┆ 100       ┆ 0.0    │
│ 59752      ┆ … 0.0]     ┆           ┆           ┆   ┆ 0.0, …    ┆           ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆ 0.0]      ┆           ┆           ┆        │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [4]:
test_df.columns

['gene_id',
 'H3K9ac',
 'H3K9ac_wc',
 'H3K9ac_len',
 'H3K9me3',
 'H3K9me3_wc',
 'H3K9me3_len',
 'H3K4me3',
 'H3K4me3_wc',
 'H3K4me3_len',
 'H3K27ac',
 'H3K27ac_wc',
 'H3K27ac_len',
 'H3K27me3',
 'H3K27me3_wc',
 'H3K27me3_len',
 'value']

In [5]:
# Select only the gene_id with histones count
gene_histone_count_df = test_df.select([
     'gene_id',
     'H3K9ac_wc',
     'H3K9me3_wc',
     'H3K4me3_wc',
     'H3K27ac_wc',
     'H3K27me3_wc',
     'value'
])

In [6]:
gene_histone_count_df

shape: (19_645, 7)
┌─────────────────┬───────────┬────────────┬────────────┬────────────┬─────────────┬────────┐
│ gene_id         ┆ H3K9ac_wc ┆ H3K9me3_wc ┆ H3K4me3_wc ┆ H3K27ac_wc ┆ H3K27me3_wc ┆ value  │
│ ---             ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ ---         ┆ ---    │
│ str             ┆ u32       ┆ u32        ┆ u32        ┆ u32        ┆ u32         ┆ f64    │
╞═════════════════╪═══════════╪════════════╪════════════╪════════════╪═════════════╪════════╡
│ ENSG00000000003 ┆ 17        ┆ 0          ┆ 18         ┆ 18         ┆ 0           ┆ 73.205 │
│ ENSG00000000005 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.191  │
│ ENSG00000000419 ┆ 25        ┆ 0          ┆ 33         ┆ 28         ┆ 0           ┆ 52.609 │
│ ENSG00000000457 ┆ 42        ┆ 0          ┆ 42         ┆ 44         ┆ 0           ┆ 4.733  │
│ ENSG00000000460 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.942  │
│ …               ┆ …         ┆ …          ┆ …          ┆ …          ┆ …           ┆ …      │
│ ENSG00000259658 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.212  │
│ ENSG00000259664 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.0    │
│ ENSG00000259680 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.071  │
│ ENSG00000259717 ┆ 0         ┆ 0          ┆ 14         ┆ 52         ┆ 0           ┆ 0.0    │
│ ENSG00000259752 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.0    │
└─────────────────┴───────────┴────────────┴────────────┴────────────┴─────────────┴────────┘

In [8]:
gene_histone_count_df = gene_histone_count_df.sort(['value'], descending=True)

In [9]:
gene_histone_count_df

shape: (19_645, 7)
┌─────────────────┬───────────┬────────────┬────────────┬────────────┬─────────────┬──────────┐
│ gene_id         ┆ H3K9ac_wc ┆ H3K9me3_wc ┆ H3K4me3_wc ┆ H3K27ac_wc ┆ H3K27me3_wc ┆ value    │
│ ---             ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ ---         ┆ ---      │
│ str             ┆ u32       ┆ u32        ┆ u32        ┆ u32        ┆ u32         ┆ f64      │
╞═════════════════╪═══════════╪════════════╪════════════╪════════════╪═════════════╪══════════╡
│ ENSG00000163631 ┆ 81        ┆ 0          ┆ 59         ┆ 53         ┆ 0           ┆ 102156.0 │
│ ENSG00000257017 ┆ 42        ┆ 0          ┆ 56         ┆ 72         ┆ 0           ┆ 38313.3  │
│ ENSG00000110245 ┆ 92        ┆ 0          ┆ 60         ┆ 97         ┆ 0           ┆ 30359.8  │
│ ENSG00000130208 ┆ 42        ┆ 0          ┆ 49         ┆ 82         ┆ 0           ┆ 28759.1  │
│ ENSG00000158874 ┆ 89        ┆ 0          ┆ 96         ┆ 100        ┆ 0           ┆ 18798.6  │
│ …               ┆ …         ┆ …          ┆ …          ┆ …          ┆ …           ┆ …        │
│ ENSG00000259571 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.0      │
│ ENSG00000259645 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.0      │
│ ENSG00000259664 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.0      │
│ ENSG00000259717 ┆ 0         ┆ 0          ┆ 14         ┆ 52         ┆ 0           ┆ 0.0      │
│ ENSG00000259752 ┆ 0         ┆ 0          ┆ 0          ┆ 0          ┆ 0           ┆ 0.0      │
└─────────────────┴───────────┴────────────┴────────────┴────────────┴─────────────┴──────────┘

In [10]:
gene_histone_count_df.write_csv("Donor 4 with histone count.csv")